### ISSUE TITLE
[BUG] [beA] j-l friert beim Laden einer Nachricht ein

### ISSUE THREAD

**Issue by stm9x9** [jlawyerorg/j-lawyer-org#1001]
**Describe the bug / Fehlerbeschreibung**
(todo: a description of the bug / eine Beschreibung des Fehlers)

j-l friert ein, es kann nichts mehr gemacht werden

**To Reproduce / Schritte zum Nachvollziehen**

1. Start j-l
2. Wechsel zu beA mit Zertifikat
3. Wechsel in Posteingang
4. Anklicken einer Nachricht

nach Neustart mit zweiter Nachricht probiert, wieder dasselbe

**Expected behavior / Erwartetes Verhalten**

Nachricht wird geöffnet / dargestellt

**Environment / verwendete Umgebung:**
 - OS / Betriebssystem: Win 10 Pro 64
 - j-lawyer.org Version: 1.13.0.5

**Additional context / Sonstiges**

2020-12-04 15:25:07,936 INFO  [org.jlawyer.bea.BeaWrapper] Connecting to beA using endpoint https://ksw.bea-brak.de
2020-12-04 15:25:23,168 ERROR [com.jdimension.jlawyer.client.settings.UserSettings] Value is null when setting user properties with key client.desktop.onlymycases
2020-12-04 15:25:23,798 ERROR [com.jdimension.jlawyer.client.settings.UserSettings] Value is null when setting user properties with key client.desktop.onlymyreviews
2020-12-04 15:25:25,513 INFO  [de.governikus.bea.kswtoolkit.socketactions.impl.LoginUser] alias: Importiertes Zertifikat
2020-12-04 15:25:25,704 ERROR [com.jdimension.jlawyer.client.settings.UserSettings] Value is null when setting user properties with key client.desktop.lastfiltertag
2020-12-04 15:25:25,704 ERROR [com.jdimension.jlawyer.client.settings.UserSettings] Value is null when setting user properties with key client.desktop.lastfiltertag
2020-12-04 15:25:25,704 ERROR [com.jdimension.jlawyer.client.settings.UserSettings] Value is null when setting user properties with key client.desktop.lastfilterdocumenttag
2020-12-04 15:25:25,720 ERROR [com.jdimension.jlawyer.client.settings.UserSettings] Value is null when setting user properties with key client.desktop.lastfilterdocumenttag
2020-12-04 15:25:25,752 ERROR [com.jdimension.jlawyer.client.settings.UserSettings] Value is null when setting user properties with key client.desktop.onlymytagged
2020-12-04 15:25:28,983 INFO  [de.governikus.bea.kswtoolkit.socketactions.impl.DecryptSessionKey] alias: Importiertes Zertifikat
2020-12-04 15:25:30,177 INFO  [org.jlawyer.bea.BeaWrapper] sender information is null - loading entire message
2020-12-04 15:25:30,610 INFO  [org.jlawyer.bea.BeaWrapper] sender information is null - loading entire message
2020-12-04 15:25:31,812 ERROR [org.jlawyer.bea.BeaWrapper] Unable to retrieve recipient data for DE.Justiz.c42f3833-af57-4aa9-b1ea-766f8b93ad99.08a2
de.brak.bea.application.dto.soap.types5.BeaFault: 0601 - Identity couldn't been found!
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.sun.xml.internal.ws.fault.SOAPFaultBuilder.createException(SOAPFaultBuilder.java:135)
	at com.sun.xml.internal.ws.client.sei.StubHandler.readResponse(StubHandler.java:238)
	at com.sun.xml.internal.ws.db.DatabindingImpl.deserializeResponse(DatabindingImpl.java:189)
	at com.sun.xml.internal.ws.db.DatabindingImpl.deserializeResponse(DatabindingImpl.java:276)
	at com.sun.xml.internal.ws.client.sei.SyncMethodHandler.invoke(SyncMethodHandler.java:104)
	at com.sun.xml.internal.ws.client.sei.SyncMethodHandler.invoke(SyncMethodHandler.java:77)
	at com.sun.xml.internal.ws.client.sei.SEIStub.invoke(SEIStub.java:147)
	at com.sun.proxy.$Proxy65.getRecipientData(Unknown Source)
	at org.jlawyer.bea.BeaWrapper.getRecipientName(BeaWrapper.java:1208)
	at org.jlawyer.bea.BeaWrapper.getFolderOverview(BeaWrapper.java:1576)
	at org.jlawyer.bea.BeaWrapper.getFolderStructure(BeaWrapper.java:1351)
	at com.jdimension.jlawyer.client.bea.BeaAccess.getFolderStructure(BeaAccess.java:942)
	at com.jdimension.jlawyer.client.bea.BeaInboxPanel.refreshFolders(BeaInboxPanel.java:921)
	at com.jdimension.jlawyer.client.bea.BeaInboxPanel$31$1.run(BeaInboxPanel.java:2434)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
2020-12-04 15:25:33,977 ERROR [org.jlawyer.bea.BeaWrapper] Unable to retrieve recipient data for DE.Justiz.c42f3833-af57-4aa9-b1ea-766f8b93ad99.08a2
de.brak.bea.application.dto.soap.types5.BeaFault: 0601 - Identity couldn't been found!
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.sun.xml.internal.ws.fault.SOAPFaultBuilder.createException(SOAPFaultBuilder.java:135)
	at com.sun.xml.internal.ws.client.sei.StubHandler.readResponse(StubHandler.java:238)
	at com.sun.xml.internal.ws.db.DatabindingImpl.deserializeResponse(DatabindingImpl.java:189)
	at com.sun.xml.internal.ws.db.DatabindingImpl.deserializeResponse(DatabindingImpl.java:276)
	at com.sun.xml.internal.ws.client.sei.SyncMethodHandler.invoke(SyncMethodHandler.java:104)
	at com.sun.xml.internal.ws.client.sei.SyncMethodHandler.invoke(SyncMethodHandler.java:77)
	at com.sun.xml.internal.ws.client.sei.SEIStub.invoke(SEIStub.java:147)
	at com.sun.proxy.$Proxy65.getRecipientData(Unknown Source)
	at org.jlawyer.bea.BeaWrapper.getRecipientName(BeaWrapper.java:1208)
	at org.jlawyer.bea.BeaWrapper.getFolderOverview(BeaWrapper.java:1576)
	at org.jlawyer.bea.BeaWrapper.getFolderOverview(BeaWrapper.java:1389)
	at com.jdimension.jlawyer.client.bea.BeaAccess.getFolderOverview(BeaAccess.java:995)
	at com.jdimension.jlawyer.client.bea.BeaInboxPanel$4.run(BeaInboxPanel.java:983)
	at java.util.TimerThread.mainLoop(Timer.java:555)
	at java.util.TimerThread.run(Timer.java:505)
2020-12-04 15:25:50,752 ERROR [com.jdimension.jlawyer.client.settings.UserSettings] Value is null when setting user properties with key client.desktop.onlymycases
2020-12-04 15:25:54,753 ERROR [com.jdimension.jlawyer.client.settings.UserSettings] Value is null when setting user properties with key client.desktop.onlymyreviews
2020-12-04 15:25:58,704 ERROR [com.jdimension.jlawyer.client.settings.UserSettings] Value is null when setting user properties with key client.desktop.lastfiltertag
2020-12-04 15:25:58,704 ERROR [com.jdimension.jlawyer.client.settings.UserSettings] Value is null when setting user properties with key client.desktop.lastfiltertag
2020-12-04 15:25:58,704 ERROR [com.jdimension.jlawyer.client.settings.UserSettings] Value is null when setting user properties with key client.desktop.lastfilterdocumenttag
2020-12-04 15:25:58,704 ERROR [com.jdimension.jlawyer.client.settings.UserSettings] Value is null when setting user properties with key client.desktop.lastfilterdocumenttag
2020-12-04 15:25:58,727 ERROR [com.jdimension.jlawyer.client.settings.UserSettings] Value is null when setting user properties with key client.desktop.onlymytagged
2020-12-04 15:26:19,738 ERROR [com.jdimension.jlawyer.client.settings.UserSettings] Value is null when setting user properties with key client.desktop.onlymycases
2020-12-04 15:26:25,767 ERROR [com.jdimension.jlawyer.client.settings.UserSettings] Value is null when setting user properties with key client.desktop.onlymyreviews
2020-12-04 15:26:31,704 ERROR [com.jdimension.jlawyer.client.settings.UserSettings] Value is null when setting user properties with key client.desktop.lastfiltertag
2020-12-04 15:26:31,704 ERROR [com.jdimension.jlawyer.client.settings.UserSettings] Value is null when setting user properties with key client.desktop.lastfiltertag
2020-12-04 15:26:31,704 ERROR [com.jdimension.jlawyer.client.settings.UserSettings] Value is null when setting user properties with key client.desktop.lastfilterdocumenttag
2020-12-04 15:26:31,704 ERROR [com.jdimension.jlawyer.client.settings.UserSettings] Value is null when setting user properties with key client.desktop.lastfilterdocumenttag
2020-12-04 15:26:31,733 ERROR [com.jdimension.jlawyer.client.settings.UserSettings] Value is null when setting user properties with key client.desktop.onlymytagged
2020-12-04 15:26:48,739 ERROR [com.jdimension.jlawyer.client.settings.UserSettings] Value is null when setting user properties with key client.desktop.onlymycases
2020-12-04 15:26:56,748 ERROR [com.jdimension.jlawyer.client.settings.UserSettings] Value is null when setting user properties with key client.desktop.onlymyreviews
2020-12-04 15:27:04,704 ERROR [com.jdimension.jlawyer.client.settings.UserSettings] Value is null when setting user properties with key client.desktop.lastfiltertag
2020-12-04 15:27:04,704 ERROR [com.jdimension.jlawyer.client.settings.UserSettings] Value is null when setting user properties with key client.desktop.lastfiltertag
2020-12-04 15:27:04,704 ERROR [com.jdimension.jlawyer.client.settings.UserSettings] Value is null when setting user properties with key client.desktop.lastfilterdocumenttag
2020-12-04 15:27:04,704 ERROR [com.jdimension.jlawyer.client.settings.UserSettings] Value is null when setting user properties with key client.desktop.lastfilterdocumenttag
2020-12-04 15:27:04,730 ERROR [com.jdimension.jlawyer.client.settings.UserSettings] Value is null when setting user properties with key client.desktop.onlymytagged
2020-12-04 15:27:17,742 ERROR [com.jdimension.jlawyer.client.settings.UserSettings] Value is null when setting user properties with key client.desktop.onlymycases
2020-12-04 15:27:27,750 ERROR [com.jdimension.jlawyer.client.settings.UserSettings] Value is null when setting user properties with key client.desktop.onlymyreviews
2020-12-04 15:27:37,705 ERROR [com.jdimension.jlawyer.client.settings.UserSettings] Value is null when setting user properties with key client.desktop.lastfiltertag
2020-12-04 15:27:37,705 ERROR [com.jdimension.jlawyer.client.settings.UserSettings] Value is null when setting user properties with key client.desktop.lastfiltertag
2020-12-04 15:27:37,705 ERROR [com.jdimension.jlawyer.client.settings.UserSettings] Value is null when setting user properties with key client.desktop.lastfilterdocumenttag
2020-12-04 15:27:37,705 ERROR [com.jdimension.jlawyer.client.settings.UserSettings] Value is null when setting user properties with key client.desktop.lastfilterdocumenttag
2020-12-04 15:27:37,729 ERROR [com.jdimension.jlawyer.client.settings.UserSettings] Value is null when setting user properties with key client.desktop.onlymytagged
2020-12-04 15:27:46,743 ERROR [com.jdimension.jlawyer.client.settings.UserSettings] Value is null when setting user properties with key client.desktop.onlymycases
2020-12-04 15:27:58,751 ERROR [com.jdimension.jlawyer.client.settings.UserSettings] Value is null when setting user properties with key client.desktop.onlymyreviews
2020-12-04 15:28:10,706 ERROR [com.jdimension.jlawyer.client.settings.UserSettings] Value is null when setting user properties with key client.desktop.lastfiltertag
2020-12-04 15:28:10,706 ERROR [com.jdimension.jlawyer.client.settings.UserSettings] Value is null when setting user properties with key client.desktop.lastfiltertag
2020-12-04 15:28:10,706 ERROR [com.jdimension.jlawyer.client.settings.UserSettings] Value is null when setting user properties with key client.desktop.lastfilterdocumenttag
2020-12-04 15:28:10,706 ERROR [com.jdimension.jlawyer.client.settings.UserSettings] Value is null when setting user properties with key client.desktop.lastfilterdocumenttag
2020-12-04 15:28:10,733 ERROR [com.jdimension.jlawyer.client.settings.UserSettings] Value is null when setting user properties with key client.desktop.onlymytagged
2020-12-04 15:28:15,742 ERROR [com.jdimension.jlawyer.client.settings.UserSettings] Value is null when setting user properties with key client.desktop.onlymycases
2020-12-04 15:28:29,759 ERROR [com.jdimension.jlawyer.client.settings.UserSettings] Value is null when setting user properties with key client.desktop.onlymyreviews
2020-12-04 15:28:44,743 ERROR [com.jdimension.jlawyer.client.settings.UserSettings] Value is null when setting user properties with key client.desktop.onlymycases
2020-12-04 15:29:00,787 ERROR [com.jdimension.jlawyer.client.settings.UserSettings] Value is null when setting user properties with key client.desktop.onlymyreviews
2020-12-04 15:29:13,742 ERROR [com.jdimension.jlawyer.client.settings.UserSettings] Value is null when setting user properties with key client.desktop.onlymycases
2020-12-04 15:29:31,787 ERROR [com.jdimension.jlawyer.client.settings.UserSettings] Value is null when setting user properties with key client.desktop.onlymyreviews
2020-12-04 15:29:42,748 ERROR [com.jdimension.jlawyer.client.settings.UserSettings] Value is null when setting user properties with key client.desktop.onlymycases
2020-12-04 15:30:02,793 ERROR [com.jdimension.jlawyer.client.settings.UserSettings] Value is null when setting user properties with key client.desktop.onlymyreviews
2020-12-04 15:30:11,748 ERROR [com.jdimension.jlawyer.client.settings.UserSettings] Value is null when setting user properties with key client.desktop.onlymycases
2020-12-04 15:30:33,795 ERROR [com.jdimension.jlawyer.client.settings.UserSettings] Value is null when setting user properties with key client.desktop.onlymyreviews
2020-12-04 15:30:40,747 ERROR [com.jdimension.jlawyer.client.settings.UserSettings] Value is null when setting user properties with key client.desktop.onlymycases
2020-12-04 15:31:04,792 ERROR [com.jdimension.jlawyer.client.settings.UserSettings] Value is null when setting user properties with key client.desktop.onlymyreviews
2020-12-04 15:31:09,744 ERROR [com.jdimension.jlawyer.client.settings.UserSettings] Value is null when setting user properties with key client.desktop.onlymycases
2020-12-04 15:31:35,796 ERROR [com.jdimension.jlawyer.client.settings.UserSettings] Value is null when setting user properties with key client.desktop.onlymyreviews
2020-12-04 15:31:38,741 ERROR [com.jdimension.jlawyer.client.settings.UserSettings] Value is null when setting user properties with key client.desktop.onlymycases
2020-12-04 15:32:06,804 ERROR [com.jdimension.jlawyer.client.settings.UserSettings] Value is null when setting user properties with key client.desktop.onlymyreviews
2020-12-04 15:32:07,758 ERROR [com.jdimension.jlawyer.client.settings.UserSettings] Value is null when setting user properties with key client.desktop.onlymycases
2020-12-04 15:32:36,758 ERROR [com.jdimension.jlawyer.client.settings.UserSettings] Value is null when setting user properties with key client.desktop.onlymycases
2020-12-04 15:32:37,790 ERROR [com.jdimension.jlawyer.client.settings.UserSettings] Value is null when setting user properties with key client.desktop.onlymyreviews
2020-12-04 15:33:05,828 ERROR [com.jdimension.jlawyer.client.settings.UserSettings] Value is null when setting user properties with key client.desktop.onlymycases
2020-12-04 15:33:08,838 ERROR [com.jdimension.jlawyer.client.settings.UserSettings] Value is null when setting user properties with key client.desktop.onlymyreviews
2020-12-04 15:33:38,954 ERROR [com.jdimension.jlawyer.client.settings.UserSettings] Value is null when setting user properties with key client.desktop.onlymycases
2020-12-04 15:33:39,931 ERROR [com.jdimension.jlawyer.client.settings.UserSettings] Value is null when setting user properties with key client.desktop.onlymyreviews

**Comment by j-dimension** [comment]
Es gibt heute Antwortzeiten der BRAK-Systeme teilweise jenseits der 50s. 

Ist das ein grundsätzliches Problem seit 1.13.0.5? Das würde mich wundern, wäre mir sicher eher schon aufs Butterbrot geschmiert worden. 

Bei beA bitte erstmal keine Einzelschicksale als Bug einstellen, ich komme sonst nicht hinterher.

**Comment by Mucki526** [comment]
Mir geht´s genauso und nicht nur heute. BEA könnte (konjunktiv irrealis) so eine schöne Sache sein. ...

**Comment by stm9x9** [comment]
> Es gibt heute Antwortzeiten der BRAK-Systeme teilweise jenseits der 50s.

Wenn es daran lag: ich habe nach ca 10 min oder so abgebrochen.

> Ist das ein grundsätzliches Problem seit 1.13.0.5? Das würde mich wundern, wäre mir sicher eher schon aufs Butterbrot geschmiert worden.

hatte ich so in der Art noch nicht. Mal ne halbe Minute.
 
> Bei beA bitte erstmal keine Einzelschicksale als Bug einstellen, ich komme sonst nicht hinterher.

Letztlich - wenn es an beA liegt - dann liegt mein Augenmerk auch weniger auf meinem persönlichen Pech :-)

Aber wer nicht wie ich mit dem Taskmanager umgehen kann, der sitzt vor seinem Desktop und weiß nicht weiter. Daher geht das mehr so in Richtung: zu lange beA-Reaktionszeiten erkennen und dann mal ein popup geben:

"Problem: Die beA-Server scheinen in den letzten 60 Sekunden keine Daten geliefert zu haben. Wollen Sie weiter auf eine Reaktion warten oder die Aktion abbrechen? -> Abbrechen -> weitere 60 Sekunden warten -> weitere 5 Minuten warten"

**Comment by stm9x9** [comment]
aktuell ist es wieder besonders schlimm. Ich habe heute zweimal jl komplett abschießen müssen nach so 10min. Dann auf einmal wurden dieselben Nachrichten in kürzester Zeit geladen.

**Comment by j-dimension** [comment]
Gib dem Client doch testweise mal mehr RAM. Wenn es viele und / oder umfangreiche Postfächer gibt, kann das helfen. Im Clientverzeichnis gibt es eine .vmoptions - Datei, dort mal reinschauen.

**Comment by j-dimension** [comment]
"**aktuell** ist es wieder besonders schlimm" hört sich aber wie ein Verfügbarkeits- / Performanceproblem der beA-Infrastruktur an.
