### ISSUE TITLE
HTMLExport mit RegEx-Fehler

### ISSUE THREAD

**Issue by j-dimension** [jlawyerorg/j-lawyer-org#11]
Code:
sContent = sContent.replaceAll("\\{\\{history\\}\\}", sb.toString());

Stacktrace:
2018-09-16 21:36:02,140 ERROR
[com.jdimension.jlawyer.timer.IterativeBackupTask] (Timer-3) Error
exporting 00191/12: java.lang.IllegalArgumentException: Illegal group
reference
        at java.util.regex.Matcher.appendReplacement(Matcher.java:857)
        at java.util.regex.Matcher.replaceAll(Matcher.java:955)
        at java.lang.String.replaceAll(String.java:2223)
        at
com.jdimension.jlawyer.export.HTMLExport.export(HTMLExport.java:859)
        at
com.jdimension.jlawyer.timer.IterativeBackupTask.run(IterativeBackupTask.java:914)
        at java.util.TimerThread.mainLoop(Timer.java:555)
        at java.util.TimerThread.run(Timer.java:505)

**Comment by j-dimension** [comment]
unable to fix without knowing the actual replacement string. probably has some content that needs to be escaped. 

handled by catching the exception and not make the entire export fail. will have to be reviewed @ KH after rollout
