### ISSUE TITLE
[BUG] Fehlermeldung bei Öffnen PDF-Anhänge im Mail-Posteingang

### ISSUE THREAD

**Issue by Linkki2021** [jlawyerorg/j-lawyer-org#1264]
Bei Öffnen von Anhängen im E-Mail-Posteingang erhalten ich des Öfteren den nachfolgenden Fehler. Dieser bleibt nicht dauerhaft, meist kann man direkt danach per Doppelklick öffnen, beim nächsten Versuch aber auch mal wieder nicht. Was immer geht ist, die Mail extern zu öffnen und sich den Anhang dann extern anzuschauen.

Leider erkenne ich kein Muster, wann der Fehler auftritt, betrifft verschiedenste Absender, bei den Anhängen handelt es sich um PDF.

Eingebunden ist ein Outlook365-Postfach via imap. Welches Problem beschreibt denn der Fehler?

<img width="197" alt="Fehler Mail jl 1" src="https://user-images.githubusercontent.com/77149788/120764041-1b218280-c518-11eb-9e27-94084afd6448.PNG">

**Comment by iradraconis** [comment]
Ich schließe mich dem Bug-Report an. Ich habe den Fehler auch häufig.

**Comment by j-dimension** [comment]
Welche Clientversion? Kann ich ein client.log von unmittelbar nach dem Auftreten des Fehlers haben (per E-Mail)?
https://www.j-lawyer.org/?topic=wo-findet-man-die-fehlerprotokolle-des-j-lawyer-org-servers-und-clients

**Comment by Linkki2021** [comment]
1.14.1.0 Das Problem gab es aber auch schon vor den letzten Updates in gleicher Form. Log anbei.
[client.log](https://github.com/jlawyerorg/j-lawyer-org/files/6596728/client.log)

**Comment by j-dimension** [comment]
Vielen Dank, das Log war sehr hilfreich. Augenscheinlich bricht der IMAP (Mail-)Server die Verbindung nach Zeit x ab. Ich kann diesen Fehler abfangen und die Verbindung automatisch neu aufbauen. Mache ich im Rahmen der 1.15.

```
2021-06-04 09:59:13,220 ERROR [com.jdimension.jlawyer.client.mail.MailContentUI] Error opening attachment
javax.mail.FolderClosedException
	at javax.mail.internet.MimeBodyPart.getContent(MimeBodyPart.java:685)
	at com.jdimension.jlawyer.client.mail.EmailUtils.getAttachmentPart(EmailUtils.java:805)
	at com.jdimension.jlawyer.client.mail.EmailUtils.getAttachmentPart(EmailUtils.java:791)
	at com.jdimension.jlawyer.client.mail.EmailUtils.getAttachmentPart(EmailUtils.java:806)
	at com.jdimension.jlawyer.client.mail.EmailUtils.getAttachmentPart(EmailUtils.java:791)
	at com.jdimension.jlawyer.client.mail.EmailUtils.getAttachmentPart(EmailUtils.java:806)
	at com.jdimension.jlawyer.client.mail.EmailUtils.getAttachmentPart(EmailUtils.java:791)
	at com.jdimension.jlawyer.client.mail.EmailUtils.getAttachmentBytes(EmailUtils.java:835)
	at com.jdimension.jlawyer.client.mail.MailContentUI.lstAttachmentsMouseClicked(MailContentUI.java:1510)
	at com.jdimension.jlawyer.client.mail.MailContentUI.access$400(MailContentUI.java:711)
	at com.jdimension.jlawyer.client.mail.MailContentUI$6.mouseClicked(MailContentUI.java:1445)
```

**Comment by Linkki2021** [comment]
Prima, vielen Dank. Es gibt auch noch 1-2 andere Fehler, die in dem Zusammenhang immer mal wieder (aber seltener) auftreten. Sobald mir erneut einer über den Weg läuft liefere ich den nach.
