### ISSUE TITLE
[BUG] temporäre Datei kann nicht erstellt / geöffnet werden, wenn (Back)Slashes enthalten sind

### ISSUE THREAD

**Issue by j-dimension** [jlawyerorg/j-lawyer-org#1278]
Sonderzeichen rausfiltern o.ä.

```
2021-06-16 21:36:19,796 ERROR [com.jdimension.jlawyer.client.mail.MailContentUI] Error opening attachment
java.io.FileNotFoundException: C:\Users\metty.DESKTOP-TEL12E4\.j-lawyer-client\tmp-documents\1624476979787_16530e4bc0a8b2196a76660dfe7799f8\Anfordern\Anfragen\Informationen bei Rechtsanwalt.pdf (Das System kann den angegebenen Pfad nicht finden)
	at java.io.FileOutputStream.open0(Native Method)
	at java.io.FileOutputStream.open(FileOutputStream.java:270)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
	at com.jdimension.jlawyer.client.utils.FileUtils.createTempFile(FileUtils.java:1029)
	at com.jdimension.jlawyer.client.launcher.LauncherFactory.createTempFile(LauncherFactory.java:824)
	at com.jdimension.jlawyer.client.launcher.LauncherFactory.getLauncher(LauncherFactory.java:742)
	at com.jdimension.jlawyer.client.mail.MailContentUI.lstAttachmentsMouseClicked(MailContentUI.java:1513)
	at com.jdimension.jlawyer.client.mail.MailContentUI.access$400(MailContentUI.java:711)
	at com.jdimension.jlawyer.client.mail.MailContentUI$6.mouseClicked(MailContentUI.java:1445)
	at java.awt.AWTEventMulticaster.mouseClicked(AWTEventMulticaster.java:270)
	at java.awt.Component.processMouseEvent(Component.java:6542)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6304)
	at java.awt.Container.processEvent(Container.java:2239)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2297)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4904)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4544)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4476)
	at java.awt.Container.dispatchEventImpl(Container.java:2283)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:760)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:84)
	at java.awt.EventQueue$4.run(EventQueue.java:733)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:730)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

```

**Comment by j-dimension** [comment]
@Linkki

**Comment by j-dimension** [comment]
@Linkki2021

**Comment by j-dimension** [comment]
@Linkki2021 mit weiterem Fall wo Tabulatoren im Dateinamen sind.

**Comment by j-dimension** [comment]
@Linkki2021 berichtet dass Outlook unzulässige Zeichen durch Unterstriche ersetzt.
