### ISSUE TITLE
[BUG] Nextcloud - Fehler beim Freigeben des Dokuments

### ISSUE THREAD

**Issue by socram70** [jlawyerorg/j-lawyer-org#1302]
Folgende Meldung erhält man neuerdings bei der Freigabe per Nextcloud. Ein Unterpfad ist nicht gewählt und um Probleme auf meiner Seite auszuschließen habe ich zwei verschiedene Server probiert, bei denen ich die gleiche Fehlermeldung erhalte.

Die Meldung erscheint nach einem Klick auf "Freigabe senden" unabhängig vom Dateityp. Die Nextcloud-Version ist 21.0.2 und 22.
![grafik](https://user-images.githubusercontent.com/60073801/127732595-2abcb950-9a6f-42dd-b76c-c114880eac17.png)

Der Client ist Windows 10, 18362_19h1 mit der jlawyer-Version 1.14.1.0 und dem aktuellsten Server.

**Comment by j-dimension** [comment]
Bitte mal die komplette Fehlermeldung aus Client.log hier posten.

Und mal die Logs der Nextcloud sichten.

**Comment by socram70** [comment]
Client log:
`2021-07-31 09:34:45,202 ERROR [com.jdimension.jlawyer.client.editors.files.ArchiveFilePanel] Error removing document
org.aarboard.nextcloud.api.exception.NextcloudApiException: java.util.concurrent.ExecutionException: org.aarboard.nextcloud.api.exception.NextcloudApiException: javax.xml.bind.UnmarshalException: unerwartetes Element (URI:"", lokal:"html"). Erwartete Elemente sind <{}ocs>
	at org.aarboard.nextcloud.api.utils.NextcloudResponseHelper.getAndWrapException(NextcloudResponseHelper.java:40)
	at org.aarboard.nextcloud.api.utils.NextcloudResponseHelper.getAndCheckStatus(NextcloudResponseHelper.java:17)
	at org.aarboard.nextcloud.api.filesharing.FilesharingConnector.getShares(FilesharingConnector.java:86)
	at org.aarboard.nextcloud.api.filesharing.FilesharingConnector.getShares(FilesharingConnector.java:63)
	at org.aarboard.nextcloud.api.NextcloudConnector.getShares(NextcloudConnector.java:778)
	at com.jdimension.jlawyer.client.cloud.CloudInstance.getShares(CloudInstance.java:748)
	at com.jdimension.jlawyer.client.cloud.SendCloudShare.<init>(SendCloudShare.java:712)
	at com.jdimension.jlawyer.client.editors.files.ArchiveFilePanel.mnuShareNextcloudActionPerformed(ArchiveFilePanel.java:5574)
	at com.jdimension.jlawyer.client.editors.files.ArchiveFilePanel.access$3300(ArchiveFilePanel.java:775)
	at com.jdimension.jlawyer.client.editors.files.ArchiveFilePanel$34.actionPerformed(ArchiveFilePanel.java:2045)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.AbstractButton.doClick(AbstractButton.java:376)
	at javax.swing.plaf.basic.BasicMenuItemUI.doClick(BasicMenuItemUI.java:842)
	at javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(BasicMenuItemUI.java:886)
	at java.awt.Component.processMouseEvent(Component.java:6539)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6304)
	at java.awt.Container.processEvent(Container.java:2239)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2297)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4904)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4535)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4476)
	at java.awt.Container.dispatchEventImpl(Container.java:2283)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:760)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:84)
	at java.awt.EventQueue$4.run(EventQueue.java:733)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:730)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: java.util.concurrent.ExecutionException: org.aarboard.nextcloud.api.exception.NextcloudApiException: javax.xml.bind.UnmarshalException: unerwartetes Element (URI:"", lokal:"html"). Erwartete Elemente sind <{}ocs>
	at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:357)
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1908)
	at org.aarboard.nextcloud.api.utils.NextcloudResponseHelper.getAndWrapException(NextcloudResponseHelper.java:38)
	... 47 more
Caused by: org.aarboard.nextcloud.api.exception.NextcloudApiException: javax.xml.bind.UnmarshalException: unerwartetes Element (URI:"", lokal:"html"). Erwartete Elemente sind <{}ocs>
	at org.aarboard.nextcloud.api.utils.XMLAnswerParser.parseResponse(XMLAnswerParser.java:52)
	at org.aarboard.nextcloud.api.utils.XMLAnswerParser.parseResponse(XMLAnswerParser.java:13)
	at org.aarboard.nextcloud.api.utils.ConnectorCommon$ResponseCallback.handleResponse(ConnectorCommon.java:193)
	at org.aarboard.nextcloud.api.utils.ConnectorCommon$ResponseCallback.completed(ConnectorCommon.java:176)
	at org.aarboard.nextcloud.api.utils.ConnectorCommon$ResponseCallback.completed(ConnectorCommon.java:161)
	at shaded.org.apache.http.concurrent.BasicFuture.completed(BasicFuture.java:122)
	at shaded.org.apache.http.impl.nio.client.DefaultClientExchangeHandlerImpl.responseCompleted(DefaultClientExchangeHandlerImpl.java:181)
	at shaded.org.apache.http.nio.protocol.HttpAsyncRequestExecutor.processResponse(HttpAsyncRequestExecutor.java:442)
	at shaded.org.apache.http.nio.protocol.HttpAsyncRequestExecutor.inputReady(HttpAsyncRequestExecutor.java:332)
	at shaded.org.apache.http.impl.nio.DefaultNHttpClientConnection.consumeInput(DefaultNHttpClientConnection.java:265)
	at shaded.org.apache.http.impl.nio.client.InternalIODispatch.onInputReady(InternalIODispatch.java:81)
	at shaded.org.apache.http.impl.nio.client.InternalIODispatch.onInputReady(InternalIODispatch.java:39)
	at shaded.org.apache.http.impl.nio.reactor.AbstractIODispatch.inputReady(AbstractIODispatch.java:121)
	at shaded.org.apache.http.impl.nio.reactor.BaseIOReactor.readable(BaseIOReactor.java:162)
	at shaded.org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvent(AbstractIOReactor.java:337)
	at shaded.org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvents(AbstractIOReactor.java:315)
	at shaded.org.apache.http.impl.nio.reactor.AbstractIOReactor.execute(AbstractIOReactor.java:276)
	at shaded.org.apache.http.impl.nio.reactor.BaseIOReactor.execute(BaseIOReactor.java:104)
	at shaded.org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor$Worker.run(AbstractMultiworkerIOReactor.java:588)
	at java.lang.Thread.run(Thread.java:748)
Caused by: javax.xml.bind.UnmarshalException: unerwartetes Element (URI:"", lokal:"html"). Erwartete Elemente sind <{}ocs>
	at com.sun.xml.bind.v2.runtime.unmarshaller.UnmarshallingContext.handleEvent(UnmarshallingContext.java:712)
	at com.sun.xml.bind.v2.runtime.unmarshaller.Loader.reportError(Loader.java:232)
	at com.sun.xml.bind.v2.runtime.unmarshaller.Loader.reportError(Loader.java:227)
	at com.sun.xml.bind.v2.runtime.unmarshaller.Loader.reportUnexpectedChildElement(Loader.java:94)
	at com.sun.xml.bind.v2.runtime.unmarshaller.UnmarshallingContext$DefaultRootLoader.childElement(UnmarshallingContext.java:1117)
	at com.sun.xml.bind.v2.runtime.unmarshaller.UnmarshallingContext._startElement(UnmarshallingContext.java:542)
	at com.sun.xml.bind.v2.runtime.unmarshaller.UnmarshallingContext.startElement(UnmarshallingContext.java:524)
	at com.sun.xml.bind.v2.runtime.unmarshaller.SAXConnector.startElement(SAXConnector.java:137)
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.startElement(AbstractSAXParser.java:509)
	at com.sun.org.apache.xerces.internal.impl.dtd.XMLDTDValidator.startElement(XMLDTDValidator.java:745)
	at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.scanStartElement(XMLNSDocumentScannerImpl.java:374)
	at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl$NSContentDriver.scanRootElementHook(XMLNSDocumentScannerImpl.java:613)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:3132)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl$PrologDriver.next(XMLDocumentScannerImpl.java:852)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:602)
	at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(XMLNSDocumentScannerImpl.java:112)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:505)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:842)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:771)
	at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1213)
	at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:643)
	at com.sun.xml.bind.v2.runtime.unmarshaller.UnmarshallerImpl.unmarshal0(UnmarshallerImpl.java:228)
	at com.sun.xml.bind.v2.runtime.unmarshaller.UnmarshallerImpl.unmarshal(UnmarshallerImpl.java:199)
	at javax.xml.bind.helpers.AbstractUnmarshallerImpl.unmarshal(AbstractUnmarshallerImpl.java:157)
	at javax.xml.bind.helpers.AbstractUnmarshallerImpl.unmarshal(AbstractUnmarshallerImpl.java:214)
	at org.aarboard.nextcloud.api.utils.XMLAnswerParser.tryParseAnswer(XMLAnswerParser.java:66)
	at org.aarboard.nextcloud.api.utils.XMLAnswerParser.parseResponse(XMLAnswerParser.java:50)
	... 19 more`

Nextcloud log:

Hier ist keine Spur von einer Anfrage zu sehen.

Auch im access.log des Webservers findet sich nichts.

**Comment by j-dimension** [comment]
Beim Versuch die bestehenden Freigaben zu ermitteln antwortet die Nextcloud mit einem Fehler und übermittelt statt eines XMLs mit den Freigaben ein HTML-Dokument mit einer Fehlermeldung.

Die Analyse muss auf Seite Nextcloud weitergeführt werden. Ggf. Loglevel erhöhen, es muss einen Log geben.
