### ISSUE TITLE
Fehlerhafte Dokumentenerstellung bei Fehlerhaftem Script

### ISSUE THREAD

**Issue by socram70** [jlawyerorg/j-lawyer-org#1535]
**Describe the bug / Fehlerbeschreibung**
(todo: a description of the bug / eine Beschreibung des Fehlers)
Fehlerhafte Dokumentenerstellung bei Fehler im Script-"Code"

**To Reproduce / Schritte zum Nachvollziehen**

Erstellt man ein Vorlagedokument mit einem fehlerhaften Script (in meinem Fall habe ich vergessen, die Klammer zu schließen und das Apostroph zu setzen), gibt die Software einen hilfreichen Fehler hierzu aus, der hierauf hinweist. Außerdem wird das Dokument erstellt, allerdings taucht es nicht in der Liste der Dokumente in der Akte auf, sondern nur in der Dateistruktur des Servers. Versucht man nun ein Dokument mit gleichem Namen anzulegen, wird man darauf hingewiesen, dass das Dokument bereits existiert. Ein Löschen ist nur durch Zugriff auf den Ordner des j-lawyer-Servers möglich, da es nicht in der Dokumentenliste auftaucht.

**Expected behavior / Erwartetes Verhalten**
Außer der Fehlermeldung sollte nichts weiter passieren.

**Environment / verwendete Umgebung:**
 - OS / Betriebssystem: Windows
 - j-lawyer.org Version: Client 2.0.1.0, Server 2.0.1.0

**Additional context / Sonstiges**

**Comment by j-dimension** [comment]
Die Scriptfunktionalität ist in 2.0.1 noch gar nicht finalisiert enthalten, daher nennt die Doku "ab 2.1".

**Comment by j-dimension** [comment]
Bitte mal das server.log vom relevanten Zeitraum bereitstellen, damit ich das Szenario mit dem aktuellen Stand der 2.1 prüfen kann.

**Comment by socram70** [comment]
Das mit 2.1 hatte ich auch zwischenzeitlich gesehen, sorry. Ich hatte mich dann erst gewundert, warum statt meinem Script-Code "das ist ein Skript" im Text stand, was wohl der aktuelle Platzhalter ist.

Hier der relevante Teil vom Log. Außerdem problematisch zu sein scheint, direkt zwei [[SCRIPT:]]-Blöcke hintereinanderzuhängen. 

2022-01-16 15:46:40,513 ERROR [org.jboss.as.ejb3.invocation] (default task-63) WFLYEJB0034: EJB Invocation failed on component ArchiveFileService for method public abstract com.jdimension.jlawyer.persistence.ArchiveFileDocumentsBean com.jdimension.jlawyer.services.ArchiveFileServiceRemote.addDocumentFromTemplate(java.lang.String,java.lang.String,org.jlawyer.data.tree.GenericNode,java.lang.String,java.util.Hashtable,java.lang.String) throws java.lang.Exception: javax.ejb.EJBException: java.util.regex.PatternSyntaxException: Unclosed character class near index 118
\{\{SCRIPT:WENNENTHAELT(AKTE_EIGENE2, „Vergleich“, „den“);]][[SCRIPT:WENNENTHAELT(AKTE_EIGENE2, „Urteil“, „das“);\}\}\.
                                                                                                                      ^
        at org.jboss.as.ejb3.tx.CMTTxInterceptor.invokeInOurTx(CMTTxInterceptor.java:246)
        at org.jboss.as.ejb3.tx.CMTTxInterceptor.required(CMTTxInterceptor.java:362)
        at org.jboss.as.ejb3.tx.CMTTxInterceptor.processInvocation(CMTTxInterceptor.java:144)
        at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:422)
        at org.jboss.invocation.InterceptorContext$Invocation.proceed(InterceptorContext.java:509)
        at org.jboss.weld.module.ejb.AbstractEJBRequestScopeActivationInterceptor.aroundInvoke(AbstractEJBRequestScopeActivationInterceptor.java:81)
        at org.jboss.as.weld.ejb.EjbRequestScopeActivationInterceptor.processInvocation(EjbRequestScopeActivationInterceptor.java:89)
        at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:422)
        at org.jboss.as.ejb3.component.interceptors.CurrentInvocationContextInterceptor.processInvocation(CurrentInvocationContextInterceptor.java:41)
        at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:422)
        at org.jboss.as.ejb3.component.invocationmetrics.WaitTimeInterceptor.processInvocation(WaitTimeInterceptor.java:47)
        at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:422)
        at org.jboss.as.ejb3.security.AuthorizationInterceptor.processInvocation(AuthorizationInterceptor.java:138)
        at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:422)
        at org.jboss.as.ejb3.security.SecurityContextInterceptor.processInvocation(SecurityContextInterceptor.java:100)
        at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:422)
        at org.jboss.as.ejb3.deployment.processors.StartupAwaitInterceptor.processInvocation(StartupAwaitInterceptor.java:22)
        at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:422)
        at org.jboss.as.ejb3.component.interceptors.ShutDownInterceptorFactory$1.processInvocation(ShutDownInterceptorFactory.java:64)
        at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:422)
        at org.jboss.as.ejb3.deployment.processors.EjbSuspendInterceptor.processInvocation(EjbSuspendInterceptor.java:57)
        at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:422)
        at org.jboss.as.ejb3.component.interceptors.LoggingInterceptor.processInvocation(LoggingInterceptor.java:67)
        at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:422)
        at org.jboss.as.ee.component.NamespaceContextInterceptor.processInvocation(NamespaceContextInterceptor.java:50)
        at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:422)
        at org.jboss.invocation.ContextClassLoaderInterceptor.processInvocation(ContextClassLoaderInterceptor.java:60)
        at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:422)
        at org.jboss.invocation.InterceptorContext.run(InterceptorContext.java:438)
        at org.wildfly.security.manager.WildFlySecurityManager.doChecked(WildFlySecurityManager.java:618)
        at org.jboss.invocation.AccessCheckingInterceptor.processInvocation(AccessCheckingInterceptor.java:57)
        at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:422)
        at org.jboss.invocation.ChainedInterceptor.processInvocation(ChainedInterceptor.java:53)
        at org.jboss.as.ee.component.ViewService$View.invoke(ViewService.java:198)
        at org.wildfly.security.auth.server.SecurityIdentity.runAsFunctionEx(SecurityIdentity.java:406)
        at org.jboss.as.ejb3.remote.AssociationImpl.invokeWithIdentity(AssociationImpl.java:565)
        at org.jboss.as.ejb3.remote.AssociationImpl.invokeMethod(AssociationImpl.java:546)
        at org.jboss.as.ejb3.remote.AssociationImpl.lambda$receiveInvocationRequest$0(AssociationImpl.java:197)
        at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
        at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:1982)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1486)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1377)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.util.regex.PatternSyntaxException: Unclosed character class near index 118
\{\{SCRIPT:WENNENTHAELT(AKTE_EIGENE2, „Vergleich“, „den“);]][[SCRIPT:WENNENTHAELT(AKTE_EIGENE2, „Urteil“, „das“);\}\}\.
                                                                                                                      ^
        at java.util.regex.Pattern.error(Pattern.java:1969)
        at java.util.regex.Pattern.clazz(Pattern.java:2562)
        at java.util.regex.Pattern.clazz(Pattern.java:2518)
        at java.util.regex.Pattern.sequence(Pattern.java:2077)
        at java.util.regex.Pattern.expr(Pattern.java:2010)
        at java.util.regex.Pattern.compile(Pattern.java:1702)
        at java.util.regex.Pattern.<init>(Pattern.java:1352)
        at java.util.regex.Pattern.compile(Pattern.java:1028)
        at org.odftoolkit.simple.common.navigation.TextNavigation.<init>(TextNavigation.java:70)
        at com.jdimension.jlawyer.documents.LibreOfficeAccess.setPlaceHolders(LibreOfficeAccess.java:733)
        at com.jdimension.jlawyer.services.ArchiveFileService.addDocumentFromTemplate(ArchiveFileService.java:3185)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.jboss.as.ee.component.ManagedReferenceMethodInterceptor.processInvocation(ManagedReferenceMethodInterceptor.java:52)
        at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:422)
        at org.jboss.invocation.InterceptorContext$Invocation.proceed(InterceptorContext.java:509)
        at org.jboss.as.weld.interceptors.Jsr299BindingsInterceptor.delegateInterception(Jsr299BindingsInterceptor.java:79)
        at org.jboss.as.weld.interceptors.Jsr299BindingsInterceptor.doMethodInterception(Jsr299BindingsInterceptor.java:89)
        at org.jboss.as.weld.interceptors.Jsr299BindingsInterceptor.processInvocation(Jsr299BindingsInterceptor.java:102)
        at org.jboss.as.ee.component.interceptors.UserInterceptorFactory$1.processInvocation(UserInterceptorFactory.java:63)
        at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:422)
        at org.jboss.as.ejb3.component.invocationmetrics.ExecutionTimeInterceptor.processInvocation(ExecutionTimeInterceptor.java:43)
        at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:422)
        at org.jboss.as.jpa.interceptor.SBInvocationInterceptor.processInvocation(SBInvocationInterceptor.java:47)
        at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:422)
        at org.jboss.as.ee.concurrent.ConcurrentContextInterceptor.processInvocation(ConcurrentContextInterceptor.java:45)
        at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:422)
        at org.jboss.invocation.InitialInterceptor.processInvocation(InitialInterceptor.java:40)
        at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:422)
        at org.jboss.invocation.ChainedInterceptor.processInvocation(ChainedInterceptor.java:53)
        at org.jboss.as.ee.component.interceptors.ComponentDispatcherInterceptor.processInvocation(ComponentDispatcherInterceptor.java:52)
        at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:422)
        at org.jboss.as.ejb3.component.pool.PooledInstanceInterceptor.processInvocation(PooledInstanceInterceptor.java:51)
        at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:422)
        at org.jboss.as.ejb3.component.interceptors.AdditionalSetupInterceptor.processInvocation(AdditionalSetupInterceptor.java:54)
        at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:422)
        at org.jboss.as.ejb3.tx.CMTTxInterceptor.invokeInOurTx(CMTTxInterceptor.java:237)
        ... 42 more

**Comment by j-dimension** [comment]
schaut mir so als als wäre der Scriptplatzhalter mit einführenden geschweiften Klammern, anstelle eckiger Klammern: 

`{{SCRIPT:WENNENTHAELT(AKTE_EIGENE2, „Vergleich“, „den“);]][[SCRIPT:WENNENTHAELT(AKTE_EIGENE2, „Urteil“, „das“);}}.`

Steht das wirklich so im Dokument?

**Comment by socram70** [comment]
Das hat mich auch irritiert, aber es steht auf jeden Fall mit [[ und ]] im Dokument. Außerdem im Dokument sind weitere Platzhalter, die mit {{}} eingebunden sind.

**Comment by j-dimension** [comment]
> Erstellt man ein Vorlagedokument mit einem fehlerhaften Script (in meinem Fall habe ich vergessen, die Klammer zu schließen und das Apostroph zu setzen), gibt die Software einen hilfreichen Fehler hierzu aus, der hierauf hinweist. Außerdem wird das Dokument erstellt, allerdings taucht es nicht in der Liste der Dokumente in der Akte auf, sondern nur in der Dateistruktur des Servers.

Das tritt im aktuellen Entwicklungsstand nicht (mehr) auf.

**Comment by j-dimension** [comment]
> Außerdem problematisch zu sein scheint, direkt zwei [[SCRIPT:]]-Blöcke hintereinanderzuhängen.

In der Tat ein Fehler, den ich gerade beheben konnte. Danke für's Melden!

**Comment by socram70** [comment]
Danke für's Beheben! 👍
