### ISSUE TITLE
[BUG] [beA] nach bea-Systemupdate werden Betreff und Aktenzeichen nicht mehr aufgelöst

### ISSUE THREAD

**Issue by stm9x9** [jlawyerorg/j-lawyer-org#1642]
![image](https://user-images.githubusercontent.com/29924198/167315210-e460e73f-210b-4934-9df8-17e6d6747156.png)

Es wird nach dem aktuellen bea-Systemupdate vor ein paar Tagen Betreff und Aktenzeichen nicht mehr aufgelöst. Erst wenn ich die Nachricht in beA-web geöffnet habe, geht es auch in jl.

die entscheidende Stelle im client log dürfte sein:

2022-05-08 22:40:11,964 WARN  [de.brak.bea.osci.vhn.CoCoHtmlConverter] nachricht: xml or xsl is null
2022-05-08 22:40:12,005 INFO  [org.jlawyer.bea.BeaWrapper] sender information is null - loading entire message
2022-05-08 22:40:13,540 WARN  [de.brak.bea.osci.vhn.CoCoHtmlConverter] nachricht: xml or xsl is null
2022-05-08 22:40:13,616 INFO  [de.governikus.bea.beaToolkit.converter.attachments.AttachmentDtoToFile] Starting attachment export to C:\Users\Stephan\AppData\Local\Temp\beaToolkit\143365759\12384364546378075050\10517473801171519504.P7S
2022-05-08 22:40:13,618 INFO  [de.governikus.bea.beaToolkit.converter.attachments.AttachmentDtoToFile] Attachment export finished, hashes match
2022-05-08 22:40:13,693 INFO  [de.governikus.bea.beaToolkit.converter.attachments.AttachmentDtoToFile] Starting attachment export to C:\Users\Stephan\AppData\Local\Temp\beaToolkit\143365759\4336870544005073222\12395479113409865399.xml
2022-05-08 22:40:13,695 INFO  [de.governikus.bea.beaToolkit.converter.attachments.AttachmentDtoToFile] Attachment export finished, hashes match
2022-05-08 22:40:13,697 INFO  [org.jlawyer.bea.xjustiz.XJustizUtil] Parsing XJustiz record - first 10 bytes: -61 -81 -62 -69 -62 -65 60 63 120 109 
2022-05-08 22:40:13,697 INFO  [org.jlawyer.bea.xjustiz.XJustizUtil] Stripping 6 bytes XML BOM
2022-05-08 22:40:13,782 INFO  [de.governikus.bea.beaToolkit.converter.attachments.AttachmentDtoToFile] Starting attachment export to C:\Users\Stephan\AppData\Local\Temp\beaToolkit\143365759\12400813580358995572\14122841720658666304.pdf
2022-05-08 22:40:13,786 INFO  [de.governikus.bea.beaToolkit.converter.attachments.AttachmentDtoToFile] Attachment export finished, hashes match
2022-05-08 22:40:13,878 INFO  [de.governikus.bea.beaToolkit.converter.attachments.AttachmentDtoToFile] Starting attachment export to C:\Users\Stephan\AppData\Local\Temp\beaToolkit\143365759\16662104522940052360\10623064670095800562.pdf
2022-05-08 22:40:13,894 INFO  [de.governikus.bea.beaToolkit.converter.attachments.AttachmentDtoToFile] Attachment export finished, hashes match

**Comment by j-dimension** [comment]
Toll. 
Ich mach nen Ticket bei der BRAK auf.

**Comment by j-dimension** [comment]
@stm9x9 kannst Du helfen? 

1. Was passiert wenn Du ausm j-lawyer eine Nachricht an Dich selbst sendest und im j-lawyer anzeigst?
2. Was passiert wenn Du aus beA Web eine Nachricht an Dich selbst sendest und im j-lawyer anzeigst?

**Comment by j-dimension** [comment]
> in allen Fällen (ich habe mich jeweils auch noch von einem Kollegen anschreiben lassen) wird alles sauber angezeigt

Also betrifft es nur Nachrichten, die aus den Systemen der Justiz gesendet werden?

**Comment by stm9x9** [comment]
hm .. heute kamen diverse gerichtliche Nachrichten, alle wurden sauber angezeigt, obwohl ich sie noch nicht in beA-web geöffnet hatte.

Ich vermute angesichts von

2022-05-08 22:40:12,005 INFO [org.jlawyer.bea.BeaWrapper] sender information is null - loading entire message
2022-05-08 22:40:13,540 WARN [de.brak.bea.osci.vhn.CoCoHtmlConverter] nachricht: xml or xsl is null

daß da durchaus ein Fehler vorlag, dieser sich aber wohl berappelt hat. Ich melde mich, falls da wieder was passiert. Einstweilen kann das Ticket wohl geschlossen werden.

**Comment by j-dimension** [comment]
@stm9x9 danke für die Rückmeldung.

**Comment by stm9x9** [comment]
heute habe ich wieder so einen Fall:

![image](https://user-images.githubusercontent.com/29924198/170111420-68b6871a-41d2-4690-b4ea-81f591262151.png)

das einzige, was ich im log sehe:

2022-05-24 21:07:46,820 WARN  [de.brak.bea.osci.vhn.CoCoHtmlConverter] nachricht: xml or xsl is null
2022-05-24 21:07:46,893 INFO  [org.jlawyer.bea.BeaWrapper] sender information is null - loading entire message
2022-05-24 21:07:47,013 WARN  [de.brak.bea.osci.vhn.CoCoHtmlConverter] nachricht: xml or xsl is null
2022-05-24 21:07:47,082 INFO  [org.jlawyer.bea.BeaWrapper] sender information is null - loading entire message
2022-05-24 21:07:49,246 WARN  [de.brak.bea.osci.vhn.CoCoHtmlConverter] nachricht: xml or xsl is null
2022-05-24 21:07:49,316 INFO  [org.jlawyer.bea.BeaWrapper] sender information is null - loading entire message
2022-05-24 21:07:51,381 WARN  [de.brak.bea.osci.vhn.CoCoHtmlConverter] nachricht: xml or xsl is null
2022-05-24 21:07:51,450 INFO  [org.jlawyer.bea.BeaWrapper] sender information is null - loading entire message
2022-05-24 21:07:54,496 WARN  [de.brak.bea.osci.vhn.CoCoHtmlConverter] nachricht: xml or xsl is null
2022-05-24 21:07:54,563 INFO  [org.jlawyer.bea.BeaWrapper] sender information is null - loading entire message
2022-05-24 21:07:54,690 WARN  [de.brak.bea.osci.vhn.CoCoHtmlConverter] nachricht: xml or xsl is null
2022-05-24 21:07:54,760 INFO  [org.jlawyer.bea.BeaWrapper] sender information is null - loading entire message
2022-05-24 21:07:54,862 WARN  [de.brak.bea.osci.vhn.CoCoHtmlConverter] nachricht: xml or xsl is null
2022-05-24 21:07:54,935 INFO  [org.jlawyer.bea.BeaWrapper] sender information is null - loading entire message
2022-05-24 21:07:56,976 WARN  [de.brak.bea.osci.vhn.CoCoHtmlConverter] nachricht: xml or xsl is null
2022-05-24 21:07:57,049 INFO  [org.jlawyer.bea.BeaWrapper] sender information is null - loading entire message
2022-05-24 21:07:57,079 WARN  [org.ehcache.impl.internal.store.heap.OnHeapStore] Max Object Graph Size reached for the object : [B@77d9eeb1


allerdings ist da jetzt noch eine weitere Nachricht, die ebenfalls diese Daten nicht auflöst, aber überhaupt nicht zu öffnen ist:

![image](https://user-images.githubusercontent.com/29924198/170111863-40f53040-a232-4a93-94f2-a916bedfbe90.png)

2022-05-24 20:58:01,698 WARN  [de.brak.bea.osci.vhn.CoCoHtmlConverter] nachricht: xml or xsl is null
2022-05-24 20:58:01,773 INFO  [org.jlawyer.bea.BeaWrapper] sender information is null - loading entire message
2022-05-24 20:58:01,907 WARN  [de.brak.bea.osci.vhn.CoCoHtmlConverter] nachricht: xml or xsl is null
2022-05-24 20:58:01,971 INFO  [org.jlawyer.bea.BeaWrapper] sender information is null - loading entire message
2022-05-24 20:58:10,227 WARN  [de.brak.bea.osci.vhn.CoCoHtmlConverter] nachricht: xml or xsl is null
2022-05-24 20:58:10,291 INFO  [org.jlawyer.bea.BeaWrapper] sender information is null - loading entire message
2022-05-24 20:58:13,122 WARN  [de.brak.bea.osci.vhn.CoCoHtmlConverter] nachricht: xml or xsl is null
2022-05-24 20:58:13,198 INFO  [org.jlawyer.bea.BeaWrapper] sender information is null - loading entire message
2022-05-24 20:58:17,666 WARN  [de.brak.bea.osci.vhn.CoCoHtmlConverter] nachricht: xml or xsl is null
2022-05-24 20:58:17,750 INFO  [org.jlawyer.bea.BeaWrapper] sender information is null - loading entire message
2022-05-24 20:58:17,859 WARN  [de.brak.bea.osci.vhn.CoCoHtmlConverter] nachricht: xml or xsl is null
2022-05-24 20:58:17,925 INFO  [org.jlawyer.bea.BeaWrapper] sender information is null - loading entire message
2022-05-24 20:58:18,030 WARN  [de.brak.bea.osci.vhn.CoCoHtmlConverter] nachricht: xml or xsl is null
2022-05-24 20:58:18,096 INFO  [org.jlawyer.bea.BeaWrapper] sender information is null - loading entire message
2022-05-24 20:58:21,209 WARN  [de.brak.bea.osci.vhn.CoCoHtmlConverter] nachricht: xml or xsl is null
2022-05-24 20:58:21,272 INFO  [org.jlawyer.bea.BeaWrapper] sender information is null - loading entire message
2022-05-24 20:58:21,303 WARN  [org.ehcache.impl.internal.store.heap.OnHeapStore] Max Object Graph Size reached for the object : [B@46a8eeb7
2022-05-24 20:59:14,472 WARN  [de.brak.bea.osci.vhn.CoCoHtmlConverter] nachricht: xml or xsl is null
2022-05-24 20:59:14,791 INFO  [de.governikus.bea.beaToolkit.converter.attachments.AttachmentDtoToFile] Starting attachment export to C:\Users\xxx\AppData\Local\Temp\beaToolkit\148104189\10018765278002624418\6024850468311497417.xml
2022-05-24 20:59:14,793 INFO  [de.governikus.bea.beaToolkit.converter.attachments.AttachmentDtoToFile] Attachment export finished, hashes match
2022-05-24 20:59:14,804 INFO  [org.jlawyer.bea.xjustiz.XJustizUtil] Parsing XJustiz record - first 10 bytes: -61 -81 -62 -69 -62 -65 60 63 120 109 
2022-05-24 20:59:14,804 INFO  [org.jlawyer.bea.xjustiz.XJustizUtil] Stripping 6 bytes XML BOM
2022-05-24 20:59:14,806 ERROR [org.jlawyer.bea.BeaWrapper] Unable to get message
org.xml.sax.SAXParseException: Content ist nicht zulässig in Prolog.
	at com.sun.org.apache.xerces.internal.parsers.DOMParser.parse(DOMParser.java:261) ~[?:?]
	at com.sun.org.apache.xerces.internal.jaxp.DocumentBuilderImpl.parse(DocumentBuilderImpl.java:339) ~[?:?]
	at org.jlawyer.bea.xjustiz.XJustizUtil321.getEebId(XJustizUtil321.java:234) ~[j-lawyer-bea-wrapper.jar:?]
	at org.jlawyer.bea.BeaWrapper.getMessage(BeaWrapper.java:3871) [j-lawyer-bea-wrapper.jar:?]
	at org.jlawyer.bea.BeaWrapper.getMessage(BeaWrapper.java:3724) [j-lawyer-bea-wrapper.jar:?]
	at com.jdimension.jlawyer.client.bea.BeaAccess.getMessage(BeaAccess.java:1090) [j-lawyer-client.jar:?]
	at com.jdimension.jlawyer.client.bea.BeaInboxPanel.displayMessage(BeaInboxPanel.java:2102) [j-lawyer-client.jar:?]
	at com.jdimension.jlawyer.client.bea.BeaInboxPanel.tblMailsMouseClicked(BeaInboxPanel.java:1563) [j-lawyer-client.jar:?]
	at com.jdimension.jlawyer.client.bea.BeaInboxPanel$16.mouseClicked(BeaInboxPanel.java:1292) [j-lawyer-client.jar:?]
	at java.awt.AWTEventMulticaster.mouseClicked(AWTEventMulticaster.java:278) [?:?]
	at java.awt.AWTEventMulticaster.mouseClicked(AWTEventMulticaster.java:277) [?:?]
	at java.awt.Component.processMouseEvent(Component.java:6638) [?:?]
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3342) [?:?]
	at java.awt.Component.processEvent(Component.java:6400) [?:?]
	at java.awt.Container.processEvent(Container.java:2263) [?:?]
	at java.awt.Component.dispatchEventImpl(Component.java:5011) [?:?]
	at java.awt.Container.dispatchEventImpl(Container.java:2321) [?:?]
	at java.awt.Component.dispatchEvent(Component.java:4843) [?:?]
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4918) [?:?]
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4556) [?:?]
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4488) [?:?]
	at java.awt.Container.dispatchEventImpl(Container.java:2307) [?:?]
	at java.awt.Window.dispatchEventImpl(Window.java:2772) [?:?]
	at java.awt.Component.dispatchEvent(Component.java:4843) [?:?]
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:772) [?:?]
	at java.awt.EventQueue$4.run(EventQueue.java:721) [?:?]
	at java.awt.EventQueue$4.run(EventQueue.java:715) [?:?]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:?]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85) [?:?]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95) [?:?]
	at java.awt.EventQueue$5.run(EventQueue.java:745) [?:?]
	at java.awt.EventQueue$5.run(EventQueue.java:743) [?:?]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:?]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85) [?:?]
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:742) [?:?]
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203) [?:?]
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124) [?:?]
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113) [?:?]
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109) [?:?]
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101) [?:?]
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:90) [?:?]
2022-05-24 20:59:14,806 ERROR [com.jdimension.jlawyer.client.bea.BeaInboxPanel] Cannot load message 148104189
org.jlawyer.bea.BeaWrapperException: org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 1; Content ist nicht zulässig in Prolog.
	at org.jlawyer.bea.BeaWrapper.getMessage(BeaWrapper.java:3909) ~[j-lawyer-bea-wrapper.jar:?]
	at org.jlawyer.bea.BeaWrapper.getMessage(BeaWrapper.java:3724) ~[j-lawyer-bea-wrapper.jar:?]
	at com.jdimension.jlawyer.client.bea.BeaAccess.getMessage(BeaAccess.java:1090) ~[j-lawyer-client.jar:?]
	at com.jdimension.jlawyer.client.bea.BeaInboxPanel.displayMessage(BeaInboxPanel.java:2102) [j-lawyer-client.jar:?]
	at com.jdimension.jlawyer.client.bea.BeaInboxPanel.tblMailsMouseClicked(BeaInboxPanel.java:1563) [j-lawyer-client.jar:?]
	at com.jdimension.jlawyer.client.bea.BeaInboxPanel$16.mouseClicked(BeaInboxPanel.java:1292) [j-lawyer-client.jar:?]
	at java.awt.AWTEventMulticaster.mouseClicked(AWTEventMulticaster.java:278) [?:?]
	at java.awt.AWTEventMulticaster.mouseClicked(AWTEventMulticaster.java:277) [?:?]
	at java.awt.Component.processMouseEvent(Component.java:6638) [?:?]
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3342) [?:?]
	at java.awt.Component.processEvent(Component.java:6400) [?:?]
	at java.awt.Container.processEvent(Container.java:2263) [?:?]
	at java.awt.Component.dispatchEventImpl(Component.java:5011) [?:?]
	at java.awt.Container.dispatchEventImpl(Container.java:2321) [?:?]
	at java.awt.Component.dispatchEvent(Component.java:4843) [?:?]
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4918) [?:?]
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4556) [?:?]
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4488) [?:?]
	at java.awt.Container.dispatchEventImpl(Container.java:2307) [?:?]
	at java.awt.Window.dispatchEventImpl(Window.java:2772) [?:?]
	at java.awt.Component.dispatchEvent(Component.java:4843) [?:?]
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:772) [?:?]
	at java.awt.EventQueue$4.run(EventQueue.java:721) [?:?]
	at java.awt.EventQueue$4.run(EventQueue.java:715) [?:?]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:?]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85) [?:?]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95) [?:?]
	at java.awt.EventQueue$5.run(EventQueue.java:745) [?:?]
	at java.awt.EventQueue$5.run(EventQueue.java:743) [?:?]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:?]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85) [?:?]
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:742) [?:?]
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203) [?:?]
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124) [?:?]
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113) [?:?]
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109) [?:?]
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101) [?:?]
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:90) [?:?]
Caused by: org.xml.sax.SAXParseException: Content ist nicht zulässig in Prolog.
	at com.sun.org.apache.xerces.internal.parsers.DOMParser.parse(DOMParser.java:261) ~[?:?]
	at com.sun.org.apache.xerces.internal.jaxp.DocumentBuilderImpl.parse(DocumentBuilderImpl.java:339) ~[?:?]
	at org.jlawyer.bea.xjustiz.XJustizUtil321.getEebId(XJustizUtil321.java:234) ~[j-lawyer-bea-wrapper.jar:?]
	at org.jlawyer.bea.BeaWrapper.getMessage(BeaWrapper.java:3871) ~[j-lawyer-bea-wrapper.jar:?]
	... 37 more
