### ISSUE TITLE
[BUG] [beA] Content nicht zulässig ...

### ISSUE THREAD

**Issue by stm9x9** [jlawyerorg/j-lawyer-org#1745]
![image](https://user-images.githubusercontent.com/29924198/187221425-6ed3c075-e3b7-4db0-afd2-8cfa592ee25f.png)

Mal wieder ein Problem mit dem verflixten beA. Ich kann eine neue Nachricht nicht laden. Alle anderen gehen.

Ich werde nachher noch nachtragen, wie es in beA-web aussieht. 

Der Ordner C:\Users\USER\AppData\Local\Temp\beaToolkit\171467063\15049780724861447461 ist leer. Alle Unterordner in C:\Users\USER\AppData\Local\Temp\beaToolkit\171467063\ sind leer.

2022-08-29 16:08:00,910 INFO  [de.governikus.bea.beaToolkit.converter.attachments.AttachmentDtoToFile] Starting attachment export to C:\Users\USER\AppData\Local\Temp\beaToolkit\171467063\15049780724861447461\9813939952798184313.xml
2022-08-29 16:08:00,912 INFO  [de.governikus.bea.beaToolkit.converter.attachments.AttachmentDtoToFile] Attachment export finished, hashes match
2022-08-29 16:08:00,914 INFO  [org.jlawyer.bea.xjustiz.XJustizUtil] Parsing XJustiz record - first 10 bytes: -61 -81 -62 -69 -62 -65 60 63 120 109 
2022-08-29 16:08:00,915 INFO  [org.jlawyer.bea.xjustiz.XJustizUtil] Stripping 6 bytes XML BOM
2022-08-29 16:08:00,920 ERROR [org.jlawyer.bea.BeaWrapper] Unable to get message
org.xml.sax.SAXParseException: Content ist nicht zul崳ig in Prolog.
	at com.sun.org.apache.xerces.internal.parsers.DOMParser.parse(DOMParser.java:261) ~[?:?]
	at com.sun.org.apache.xerces.internal.jaxp.DocumentBuilderImpl.parse(DocumentBuilderImpl.java:339) ~[?:?]
	at org.jlawyer.bea.xjustiz.XJustizUtil321.getEebId(XJustizUtil321.java:234) ~[j-lawyer-bea-wrapper.jar:?]
	at org.jlawyer.bea.BeaWrapper.getMessage(BeaWrapper.java:3871) [j-lawyer-bea-wrapper.jar:?]
	at org.jlawyer.bea.BeaWrapper.getMessage(BeaWrapper.java:3724) [j-lawyer-bea-wrapper.jar:?]
	at com.jdimension.jlawyer.client.bea.BeaAccess.getMessage(BeaAccess.java:1090) [j-lawyer-client.jar:?]
	at com.jdimension.jlawyer.client.bea.BeaInboxPanel.displayMessage(BeaInboxPanel.java:2102) [j-lawyer-client.jar:?]
	at com.jdimension.jlawyer.client.bea.BeaInboxPanel.tblMailsMouseClicked(BeaInboxPanel.java:1563) [j-lawyer-client.jar:?]
	at com.jdimension.jlawyer.client.bea.BeaInboxPanel$16.mouseClicked(BeaInboxPanel.java:1292) [j-lawyer-client.jar:?]
	at java.awt.AWTEventMulticaster.mouseClicked(AWTEventMulticaster.java:278) [?:?]
	at java.awt.AWTEventMulticaster.mouseClicked(AWTEventMulticaster.java:277) [?:?]
	at java.awt.Component.processMouseEvent(Component.java:6638) [?:?]
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3342) [?:?]
	at java.awt.Component.processEvent(Component.java:6400) [?:?]
	at java.awt.Container.processEvent(Container.java:2263) [?:?]
	at java.awt.Component.dispatchEventImpl(Component.java:5011) [?:?]
	at java.awt.Container.dispatchEventImpl(Container.java:2321) [?:?]
	at java.awt.Component.dispatchEvent(Component.java:4843) [?:?]
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4918) [?:?]
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4556) [?:?]
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4488) [?:?]
	at java.awt.Container.dispatchEventImpl(Container.java:2307) [?:?]
	at java.awt.Window.dispatchEventImpl(Window.java:2772) [?:?]
	at java.awt.Component.dispatchEvent(Component.java:4843) [?:?]
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:772) [?:?]
	at java.awt.EventQueue$4.run(EventQueue.java:721) [?:?]
	at java.awt.EventQueue$4.run(EventQueue.java:715) [?:?]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:?]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85) [?:?]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95) [?:?]
	at java.awt.EventQueue$5.run(EventQueue.java:745) [?:?]
	at java.awt.EventQueue$5.run(EventQueue.java:743) [?:?]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:?]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85) [?:?]
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:742) [?:?]
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203) [?:?]
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124) [?:?]
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113) [?:?]
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109) [?:?]
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101) [?:?]
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:90) [?:?]
2022-08-29 16:08:00,921 ERROR [com.jdimension.jlawyer.client.bea.BeaInboxPanel] Cannot load message 171467063
org.jlawyer.bea.BeaWrapperException: org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 1; Content ist nicht zul崳ig in Prolog.
	at org.jlawyer.bea.BeaWrapper.getMessage(BeaWrapper.java:3909) ~[j-lawyer-bea-wrapper.jar:?]
	at org.jlawyer.bea.BeaWrapper.getMessage(BeaWrapper.java:3724) ~[j-lawyer-bea-wrapper.jar:?]
	at com.jdimension.jlawyer.client.bea.BeaAccess.getMessage(BeaAccess.java:1090) ~[j-lawyer-client.jar:?]
	at com.jdimension.jlawyer.client.bea.BeaInboxPanel.displayMessage(BeaInboxPanel.java:2102) [j-lawyer-client.jar:?]
	at com.jdimension.jlawyer.client.bea.BeaInboxPanel.tblMailsMouseClicked(BeaInboxPanel.java:1563) [j-lawyer-client.jar:?]
	at com.jdimension.jlawyer.client.bea.BeaInboxPanel$16.mouseClicked(BeaInboxPanel.java:1292) [j-lawyer-client.jar:?]
	at java.awt.AWTEventMulticaster.mouseClicked(AWTEventMulticaster.java:278) [?:?]
	at java.awt.AWTEventMulticaster.mouseClicked(AWTEventMulticaster.java:277) [?:?]
	at java.awt.Component.processMouseEvent(Component.java:6638) [?:?]
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3342) [?:?]
	at java.awt.Component.processEvent(Component.java:6400) [?:?]
	at java.awt.Container.processEvent(Container.java:2263) [?:?]
	at java.awt.Component.dispatchEventImpl(Component.java:5011) [?:?]
	at java.awt.Container.dispatchEventImpl(Container.java:2321) [?:?]
	at java.awt.Component.dispatchEvent(Component.java:4843) [?:?]
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4918) [?:?]
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4556) [?:?]
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4488) [?:?]
	at java.awt.Container.dispatchEventImpl(Container.java:2307) [?:?]
	at java.awt.Window.dispatchEventImpl(Window.java:2772) [?:?]
	at java.awt.Component.dispatchEvent(Component.java:4843) [?:?]
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:772) [?:?]
	at java.awt.EventQueue$4.run(EventQueue.java:721) [?:?]
	at java.awt.EventQueue$4.run(EventQueue.java:715) [?:?]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:?]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85) [?:?]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95) [?:?]
	at java.awt.EventQueue$5.run(EventQueue.java:745) [?:?]
	at java.awt.EventQueue$5.run(EventQueue.java:743) [?:?]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:?]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85) [?:?]
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:742) [?:?]
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203) [?:?]
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124) [?:?]
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113) [?:?]
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109) [?:?]
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101) [?:?]
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:90) [?:?]
Caused by: org.xml.sax.SAXParseException: Content ist nicht zul崳ig in Prolog.
	at com.sun.org.apache.xerces.internal.parsers.DOMParser.parse(DOMParser.java:261) ~[?:?]
	at com.sun.org.apache.xerces.internal.jaxp.DocumentBuilderImpl.parse(DocumentBuilderImpl.java:339) ~[?:?]
	at org.jlawyer.bea.xjustiz.XJustizUtil321.getEebId(XJustizUtil321.java:234) ~[j-lawyer-bea-wrapper.jar:?]
	at org.jlawyer.bea.BeaWrapper.getMessage(BeaWrapper.java:3871) ~[j-lawyer-bea-wrapper.jar:?]
	... 37 more
2022-08-29 16:08:02,502 WARN  [de.brak.bea.osci.vhn.CoCoHtmlConverter] nachricht: xml or xsl is null
2022-08-29 16:08:02,922 INFO  [de.governikus.bea.beaToolkit.converter.attachments.AttachmentDtoToFile] Starting attachment export to C:\Users\USER\AppData\Local\Temp\beaToolkit\164065739\13068731887025659159\16731828141422350906.pdf
2022-08-29 16:08:02,924 INFO  [de.governikus.bea.beaToolkit.converter.attachments.AttachmentDtoToFile] Attachment export finished, hashes match

**Comment by stm9x9** [comment]
ok, nach dem Öffnen in beA-web konnte ich die Nachricht auch in j-l öffnen. Vielleicht noch von Interesse: Die Nachricht verlangt ein eEB.
