### ISSUE TITLE
Search returns error message

### ISSUE THREAD

**Issue by mschwarzer** [jlawyerorg/j-lawyer-org#176]
When searching for cases or contacts I receive the following error (client log):

```
2018-11-21 16:14:14,836 ERROR [com.jdimension.jlawyer.client.LoginDialog] Error connecting to server
java.lang.IllegalStateException: EJBCLIENT000025: No EJB receiver available for handling [appName:j-lawyer-server, moduleName:j-lawyer-server-ejb, distinctName:] combination for invocation context org.jboss.ejb.client.EJBClientInvocationContext@1ea51b75
	at org.jboss.ejb.client.EJBClientContext.requireEJBReceiver(EJBClientContext.java:774)
	at org.jboss.ejb.client.ReceiverInterceptor.handleInvocation(ReceiverInterceptor.java:116)
	at org.jboss.ejb.client.EJBClientInvocationContext.sendRequest(EJBClientInvocationContext.java:186)
	at org.jboss.ejb.client.EJBInvocationHandler.sendRequestWithPossibleRetries(EJBInvocationHandler.java:255)
	at org.jboss.ejb.client.EJBInvocationHandler.doInvoke(EJBInvocationHandler.java:200)
	at org.jboss.ejb.client.EJBInvocationHandler.doInvoke(EJBInvocationHandler.java:183)
	at org.jboss.ejb.client.EJBInvocationHandler.invoke(EJBInvocationHandler.java:146)
	at com.sun.proxy.$Proxy2.login(Unknown Source)
	at com.jdimension.jlawyer.client.LoginDialog.cmdLoginActionPerformed(LoginDialog.java:473)
	at com.jdimension.jlawyer.client.LoginDialog.pwPasswordKeyPressed(LoginDialog.java:400)
	at com.jdimension.jlawyer.client.LoginDialog.access$400(LoginDialog.java:38)
	at com.jdimension.jlawyer.client.LoginDialog$4.keyPressed(LoginDialog.java:171)
	at java.awt.Component.processKeyEvent(Unknown Source)
	at javax.swing.JComponent.processKeyEvent(Unknown Source)
	at java.awt.Component.processEvent(Unknown Source)
	at java.awt.Container.processEvent(Unknown Source)
	at java.awt.Component.dispatchEventImpl(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.KeyboardFocusManager.redispatchEvent(Unknown Source)
	at java.awt.DefaultKeyboardFocusManager.dispatchKeyEvent(Unknown Source)
	at java.awt.DefaultKeyboardFocusManager.preDispatchKeyEvent(Unknown Source)
	at java.awt.DefaultKeyboardFocusManager.typeAheadAssertions(Unknown Source)
	at java.awt.DefaultKeyboardFocusManager.dispatchEvent(Unknown Source)
	at java.awt.Component.dispatchEventImpl(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Window.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)
2018-11-21 16:17:49,493 INFO  [com.jdimension.jlawyer.client.Main] Java: 1.8.0_162
2018-11-21 16:17:53,135 INFO  [org.xnio] XNIO version 3.3.1.Final
2018-11-21 16:17:53,222 INFO  [org.xnio.nio] XNIO NIO Implementation Version 3.3.1.Final
2018-11-21 16:17:53,500 INFO  [org.jboss.remoting] JBoss Remoting version 4.0.9.Final
2018-11-21 16:17:53,552 INFO  [org.jboss.ejb.client] JBoss EJB Client version 2.1.1.Final
2018-11-21 16:17:55,390 INFO  [org.jboss.ejb.client.remoting] EJBCLIENT000017: Received server version 2 and marshalling strategies [river]
2018-11-21 16:17:55,423 INFO  [org.jboss.ejb.client.remoting] EJBCLIENT000013: Successful version handshake completed for receiver context EJBReceiverContext{clientContext=org.jboss.ejb.client.EJBClientContext@66785ca5, receiver=Remoting connection EJB receiver [connection=org.jboss.ejb.client.remoting.ConnectionPool$PooledConnection@7c6f9652,channel=jboss.ejb,nodename=sas-pc]} on channel Channel ID 8f00290d (outbound) of Remoting connection 651e05f5 to localhost/127.0.0.1:8080
2018-11-21 16:18:12,612 INFO  [org.jboss.ejb.client.remoting] EJBCLIENT000017: Received server version 2 and marshalling strategies [river]
2018-11-21 16:18:12,613 INFO  [org.jboss.ejb.client.remoting] EJBCLIENT000013: Successful version handshake completed for receiver context EJBReceiverContext{clientContext=org.jboss.ejb.client.EJBClientContext@31cd0534, receiver=Remoting connection EJB receiver [connection=Remoting connection <4779cf43>,channel=jboss.ejb,nodename=sas-pc]} on channel Channel ID 8a29b7ec (outbound) of Remoting connection 720c013b to localhost/127.0.0.1:8080
2018-11-21 16:18:12,835 ERROR [com.jdimension.jlawyer.client.voip.FaxStatusPanel] java.lang.RuntimeException: javax.naming.NameNotFoundException: topic/faxQueueTopic -- service jboss.naming.context.java.jboss.exported.topic.faxQueueTopic
2018-11-21 16:18:13,095 ERROR [com.jdimension.jlawyer.client.templates.TemplatesPanel] javax.ejb.EJBException: No such method getAllTemplateNames() on EJB[appname=j-lawyer-server,modulename=j-lawyer-server-ejb,distinctname=,beanname=SystemManagement,viewclassname=com.jdimension.jlawyer.services.SystemManagementRemote]
2018-11-21 16:18:13,449 ERROR [com.jdimension.jlawyer.client.editors.documents.ScannerPanel] java.lang.RuntimeException: javax.naming.NameNotFoundException: topic/dirObserverTopic -- service jboss.naming.context.java.jboss.exported.topic.dirObserverTopic
2018-11-21 16:18:16,205 ERROR [com.jdimension.jlawyer.client.JKanzleiGUI] java.lang.RuntimeException: javax.naming.NameNotFoundException: topic/systemMonitoringTopic -- service jboss.naming.context.java.jboss.exported.topic.systemMonitoringTopic
2018-11-21 16:19:18,586 ERROR [com.jdimension.jlawyer.client.editors.files.QuickArchiveFileSearchThread] Error connecting to server
javax.ejb.EJBException: No such method searchEnhanced(java.lang.String,boolean,java.lang.String) on EJB[appname=j-lawyer-server,modulename=j-lawyer-server-ejb,distinctname=,beanname=ArchiveFileService,viewclassname=com.jdimension.jlawyer.services.ArchiveFileServiceRemote]
	at org.jboss.ejb.client.remoting.GeneralInvocationFailureResponseHandler.processMessage(GeneralInvocationFailureResponseHandler.java:59)
	at org.jboss.ejb.client.remoting.ChannelAssociation.processResponse(ChannelAssociation.java:386)
	at org.jboss.ejb.client.remoting.ChannelAssociation$ResponseReceiver.handleMessage(ChannelAssociation.java:498)
	at org.jboss.remoting3.remote.RemoteConnectionChannel$5.run(RemoteConnectionChannel.java:463)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
	at ...asynchronous invocation...(Unknown Source)
	at org.jboss.ejb.client.remoting.GeneralInvocationFailureResponseHandler$InvocationFailureResultProducer.getResult(GeneralInvocationFailureResponseHandler.java:84)
	at org.jboss.ejb.client.EJBClientInvocationContext.getResult(EJBClientInvocationContext.java:276)
	at org.jboss.ejb.client.EJBObjectInterceptor.handleInvocationResult(EJBObjectInterceptor.java:64)
	at org.jboss.ejb.client.EJBClientInvocationContext.getResult(EJBClientInvocationContext.java:290)
	at org.jboss.ejb.client.EJBHomeInterceptor.handleInvocationResult(EJBHomeInterceptor.java:88)
	at org.jboss.ejb.client.EJBClientInvocationContext.getResult(EJBClientInvocationContext.java:290)
	at org.jboss.ejb.client.TransactionInterceptor.handleInvocationResult(TransactionInterceptor.java:46)
	at org.jboss.ejb.client.EJBClientInvocationContext.getResult(EJBClientInvocationContext.java:290)
	at org.jboss.ejb.client.ReceiverInterceptor.handleInvocationResult(ReceiverInterceptor.java:129)
	at org.jboss.ejb.client.EJBClientInvocationContext.getResult(EJBClientInvocationContext.java:265)
	at org.jboss.ejb.client.EJBClientInvocationContext.awaitResponse(EJBClientInvocationContext.java:453)
	at org.jboss.ejb.client.EJBInvocationHandler.doInvoke(EJBInvocationHandler.java:204)
	at org.jboss.ejb.client.EJBInvocationHandler.doInvoke(EJBInvocationHandler.java:183)
	at org.jboss.ejb.client.EJBInvocationHandler.invoke(EJBInvocationHandler.java:146)
	at com.sun.proxy.$Proxy4.searchEnhanced(Unknown Source)
	at com.jdimension.jlawyer.client.editors.files.QuickArchiveFileSearchThread.run(QuickArchiveFileSearchThread.java:61)
	at java.lang.Thread.run(Unknown Source)
```

The server log does not show any error messages. Only info messages:

```
2018-11-21 16:28:47,911 INFO  [com.jdimension.jlawyer.timer.DirectoryObserverTask] (Timer-4) directory observation is switched off
2018-11-21 16:28:59,908 INFO  [com.jdimension.jlawyer.timer.DirectoryObserverTask] (Timer-4) directory observation is switched off
2018-11-21 16:29:11,910 INFO  [com.jdimension.jlawyer.timer.DirectoryObserverTask] (Timer-4) directory observation is switched off
2018-11-21 16:29:23,908 INFO  [com.jdimension.jlawyer.timer.DirectoryObserverTask] (Timer-4) directory observation is switched off
2018-11-21 16:29:35,910 INFO  [com.jdimension.jlawyer.timer.DirectoryObserverTask] (Timer-4) directory observation is switched off
2018-11-21 16:29:47,910 INFO  [com.jdimension.jlawyer.timer.DirectoryObserverTask] (Timer-4) directory observation is switched off
2018-11-21 16:29:59,910 INFO  [com.jdimension.jlawyer.timer.DirectoryObserverTask] (Timer-4) directory observation is switched off
2018-11-21 16:30:11,910 INFO  [com.jdimension.jlawyer.timer.DirectoryObserverTask] (Timer-4) directory observation is switched off
2018-11-21 16:30:23,910 INFO  [com.jdimension.jlawyer.timer.DirectoryObserverTask] (Timer-4) directory observation is switched off
2018-11-21 16:30:35,908 INFO  [com.jdimension.jlawyer.timer.DirectoryObserverTask] (Timer-4) directory observation is switched off

```

Using:
- Windows 7
- j-lawyer 1.9.0

**Comment by j-dimension** [comment]
You seem to be running a client in version 1.9.0 against a server in version 1.9.1 and there is an API that has changed in between these two versions. Can you confirm?

**Comment by mschwarzer** [comment]
Thanks! That was the issues. For future releases it would be useful to verify on login if client and server version are compatible.
