### ISSUE TITLE
Bea Timeout: automatisch neu verbinden in BeaCheckTimerTask

### ISSUE THREAD

**Issue by Mucki526** [jlawyerorg/j-lawyer-org#1803]
Gibt es eine Möglichkeit das automatische Ausloggen beim BEA zu verhindern? Wenn nicht, könnte man es nicht so einprogrammieren, dass für den Fall, dass Bea ausgeloggt wird, es automatisch im Hintergrund, spätestens beim nächsten Zugriffversuch auf den Posteingang wieder eingeloggt wird? 

**NOTE: Please search existing tickets to avoid duplicates **
**HINWEIS: Bitte vorab die Ticketsuche verwenden, um Doppeleinträge zu vermeiden **

**Is your feature request related to a problem? Please describe. / Welches Problem soll durch die Erweiterung / Verbesserung gelöst werden?**
Description / Beschreibung

**Describe the solution you'd like / Beschreibe die gewünschte Lösung**
Description / Beschreibung

**Additional context / Sonstiges **
Sonstige Informationen / Screenshots / ...

**Comment by j-dimension** [comment]
Das gibt es bereits - der Client macht zyklisch Abfragen, um einen Timeout zu verhindern. Evtl. hat die BRAK Anpassungen gemacht und der Timeout ist jetzt geringer? Nach welcher Zeit bist Du denn "offline"?

**Comment by Mucki526** [comment]
Eigentlich laufend, mehrmals am Tag. Das Szenario ist auch oft so, ich sehe, es kommt eine mail - Sie haben eine neue BEA Nachricht. Ich warte dann schon immer ein  paar Minuten, bis das theoretisch verfügbar sein sollte. Dann gehe ich auf BEA, da ist nix da, wenn ich dann das angezeigte (alte Verzeichnis anklicke bekomme ich irgend einen B0 "Null" Fehler (wohl leeres Verzeichnis), wenn ich dann auf aktualisieren drücke kommt: 
![grafik](https://user-images.githubusercontent.com/37142896/200502730-8ef13d42-d685-4d33-8140-9793b5d0fcee.png)
Dann zeigt es bereit unten, aber kein Verzeichnis, aktualisieren hilft nicht, aufklappen geht nicht, Mir bleibt nur neu einloggen. Dann lädt es alles wieder.

**Comment by j-dimension** [comment]
@stm9x9 als beA-Intensivtäter, hast Du das schonmal beobachtet?

**Comment by Mucki526** [comment]
Jeden Tag. Es ist lästig. Meiner Frau geht es auch so. Meine Frau arbeitet inzwischen garnicht mehr mit dem J-Lawyer BEA, sondern geht über die Web-Oberfläche, speichert die Nachricht im Scan-Ordner und von dort in die Akte, Geht schneller sagt sie. Ich versuche die Funktionalität in J-lawyer zu nutzen, aber da gibt es einige "Haken- und Ösen" wie dargestellt. Oft habe ich auch die Einträge im Dateiverzeichnis der vorhandenen BEA_Nachrichten doppelt angezeigt, bzw. die BEAS sind zweimal vorhanden, Das passiert m.E. wenn man zweimal beim Aktualisieren auf aktualisieren drückt. Ganz genau verstanden habe ich die BUGS noch nicht. Sie kosten aber Zeit.

**Comment by Mucki526** [comment]
Den Fehler habe ich mehrfach am Tag. Immer muss ich mich neu einloggen. 
![grafik](https://user-images.githubusercontent.com/37142896/200533724-533d2547-1f50-4108-8858-b720989485cb.png)

**Comment by j-dimension** [comment]
9999 ist der Sammelfehler der BRAK. Hier wäre die BRAK zu kontaktieren.

**Comment by j-dimension** [comment]
> Jeden Tag. Es ist lästig. Meiner Frau geht es auch so. Meine Frau arbeitet inzwischen garnicht mehr mit dem J-Lawyer BEA, sondern geht über die Web-Oberfläche, speichert die Nachricht im Scan-Ordner und von dort in die Akte, Geht schneller sagt sie. Ich versuche die Funktionalität in J-lawyer zu nutzen, aber da gibt es einige "Haken- und Ösen" wie dargestellt. Oft habe ich auch die Einträge im Dateiverzeichnis der vorhandenen BEA_Nachrichten doppelt angezeigt, bzw. die BEAS sind zweimal vorhanden, Das passiert m.E. wenn man zweimal beim Aktualisieren auf aktualisieren drückt. Ganz genau verstanden habe ich die BUGS noch nicht. Sie kosten aber Zeit.

@Mucki526  Hilft mir leider alles nicht weiter. Was hilft, sind Logs, Screenshots / Videos und genaue Beschreibungen, um einen Fehler auf meiner Seite nachvollziehbar zu machen.

**Comment by stm9x9** [comment]
Der Aktualisierungs-Button (ohne vorher auszulogen) hat bei mir noch nie funktioniert IIRC. Ich habe eher das Problem, daß ich meinen Rechner ab und an in suspend gehen lasse und danach geht beA oft nicht weiter ohne ausloggen/einloggen. Hab ich aber nicht weiter beobachtet. Wäre natürlich toll, wenn j-l sich nach einer Rechner-Pause wieder von selber einloggen würde.

**Comment by Mucki526** [comment]
Morgens, wenn der Rechner durchgelaufen ist (ja, unökologisch...) zeigt j-lawyer beim BEA links unten (grün) bereit, aber der Inhalt eines Verzeichnisses kann nicht angezeigt werden 
![grafik](https://user-images.githubusercontent.com/37142896/201030876-6d283d96-f522-4887-93e0-22d21696bfd4.png)
also ausloggen und neu einloggen.... lästig und ein Zeitfresser, wenn noch beas im Ordner sind, die alle neu geladen werden....

**Comment by Mucki526** [comment]
Und hoffentlich das richtige Serverlog... :-)
[server.log.txt](https://github.com/jlawyerorg/j-lawyer-org/files/10005213/server.log.txt)

**Comment by j-dimension** [comment]
```
2022-11-12 06:35:55,447 ERROR [org.jlawyer.bea.BeaWrapper] Unable to get folder overview
de.brak.bea.application.dto.soap.types6.BeaFault: 0001 - The entered session was invalid!
	at jdk.internal.reflect.GeneratedConstructorAccessor668.newInstance(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:490) ~[?:?]
	at com.sun.xml.ws.fault.SOAPFaultBuilder.createException(SOAPFaultBuilder.java:117) ~[rt-2.3.3.jar:2.3.3]
	at com.sun.xml.ws.client.sei.StubHandler.readResponse(StubHandler.java:223) ~[rt-2.3.3.jar:2.3.3]
	at com.sun.xml.ws.db.DatabindingImpl.deserializeResponse(DatabindingImpl.java:176) ~[rt-2.3.3.jar:2.3.3]
	at com.sun.xml.ws.db.DatabindingImpl.deserializeResponse(DatabindingImpl.java:263) ~[rt-2.3.3.jar:2.3.3]
	at com.sun.xml.ws.client.sei.SyncMethodHandler.invoke(SyncMethodHandler.java:89) ~[rt-2.3.3.jar:2.3.3]
	at com.sun.xml.ws.client.sei.SyncMethodHandler.invoke(SyncMethodHandler.java:62) ~[rt-2.3.3.jar:2.3.3]
	at com.sun.xml.ws.client.sei.SEIStub.invoke(SEIStub.java:131) ~[rt-2.3.3.jar:2.3.3]
	at com.sun.proxy.$Proxy69.getFolderOverview(Unknown Source) ~[?:?]
	at org.jlawyer.bea.BeaWrapper.getFolderOverview(BeaWrapper.java:2054) [j-lawyer-bea-wrapper.jar:?]
	at org.jlawyer.bea.BeaWrapper.getFolderOverview(BeaWrapper.java:2016) [j-lawyer-bea-wrapper.jar:?]
	at com.jdimension.jlawyer.client.bea.BeaAccess.getFolderOverview(BeaAccess.java:1057) [j-lawyer-client.jar:?]
	at com.jdimension.jlawyer.client.bea.BeaCheckTimerTask.run(BeaCheckTimerTask.java:710) [j-lawyer-client.jar:?]
	at java.util.TimerThread.mainLoop(Timer.java:556) [?:?]
	at java.util.TimerThread.run(Timer.java:506) [?:?]
```

```
2022-11-12 06:35:57,001 ERROR [org.jlawyer.bea.BeaWrapper] Unable to get beA folder overview for folder Posteingang
org.jlawyer.bea.BeaWrapperException: Unable to get beA folder overview for folder Posteingang
	at org.jlawyer.bea.BeaWrapper.getFolderOverview(BeaWrapper.java:2061) [j-lawyer-bea-wrapper.jar:?]
	at org.jlawyer.bea.BeaWrapper.getFolderOverview(BeaWrapper.java:2016) [j-lawyer-bea-wrapper.jar:?]
	at com.jdimension.jlawyer.client.bea.BeaAccess.getFolderOverview(BeaAccess.java:1057) [j-lawyer-client.jar:?]
	at com.jdimension.jlawyer.client.bea.BeaCheckTimerTask.run(BeaCheckTimerTask.java:710) [j-lawyer-client.jar:?]
	at java.util.TimerThread.mainLoop(Timer.java:556) [?:?]
	at java.util.TimerThread.run(Timer.java:506) [?:?]
```
