### ISSUE TITLE
[BUG] /v6/templates/documents/{folder}/{template}/{caseId}/{fileName} gibt Exception, wenn Sachbearbeiter oder Anwalt der Akte leer / nicht existent

### ISSUE THREAD

**Issue by timo0** [jlawyerorg/j-lawyer-org#1832]
Ich versuche ein Dokument aus einer Vorlage per API zu erstellen

Aufruf:
```
curl -u "admin:pwd" \
"https://jlawyer/j-lawyer-io/rest/v6/templates/documents/Vollmacht/Vollmacht.docx/e76ea796ac16000d5d4c226b49b16ad0" \
-H "accept: application/json" \
-H "Content-Type: application/json"
```

Antwort:
```
[
	"{{AKTE_KURZRUBRUM}}",
	"{{AKTE_WEGEN}}"
]
```

Aufruf:
```
curl -v \
-u "admin:pwd" \
-X PUT \
"https://jlawyer/j-lawyer-io/rest/v6/templates/documents/Vollmacht/Vollmacht.docx/e76ea796ac16000d5d4c226b49b16ad0/2022-12-07_Vollmacht" \
-H "accept: application/json" \
-H "Content-Type: application/json" \
-d "[{\"placeHolderKey\": \"{{AKTE_KURZRUBRUM}}\", \"placeHolderValue\": \"Test 1\"}, {\"placeHolderKey\": \"{{AKTE_WEGEN}}\", \"placeHolderValue\": \"Test 2\"}]"
```

Antwort:
```
*   Trying 10.89.1.3:443...
* Connected to jlawyer (10.89.1.3) port 443 (#0)
* ALPN: offers h2
* ALPN: offers http/1.1
*  CAfile: /etc/ssl/cert.pem
*  CApath: none
* (304) (OUT), TLS handshake, Client hello (1):
* (304) (IN), TLS handshake, Server hello (2):
* (304) (IN), TLS handshake, Unknown (8):
* (304) (IN), TLS handshake, Certificate (11):
* (304) (IN), TLS handshake, CERT verify (15):
* (304) (IN), TLS handshake, Finished (20):
* (304) (OUT), TLS handshake, Finished (20):
* SSL connection using TLSv1.3 / AEAD-AES256-GCM-SHA384
* ALPN: server accepted h2
* Server certificate:
*  subject: CN=jlawyer
*  start date: Oct  9 14:55:20 2022 GMT
*  expire date: Jan  7 14:55:19 2023 GMT
*  subjectAltName: host "jlawyer" matched cert's "jlawyer"
*  issuer: C=US; O=Let's Encrypt; CN=R3
*  SSL certificate verify ok.
* Using HTTP2, server supports multiplexing
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* Server auth using Basic with user 'admin'
* h2h3 [:method: PUT]
* h2h3 [:path: /j-lawyer-io/rest/v6/templates/documents/Vollmacht/Vollmacht.docx/e76ea796ac16000d5d4c226b49b16ad0/2022-12-07_Vollmacht]
* h2h3 [:scheme: https]
* h2h3 [:authority: jlawyer]
* h2h3 [authorization: Basic *]
* h2h3 [user-agent: curl/7.84.0]
* h2h3 [accept: application/json]
* h2h3 [content-type: application/json]
* h2h3 [content-length: 228]
* Using Stream ID: 1 (easy handle 0x7fe8c780a800)
> PUT /j-lawyer-io/rest/v6/templates/documents/Vollmacht/Vollmacht.docx/e76ea796ac16000d5d4c226b49b16ad0/2022-12-07_Vollmacht HTTP/2
> Host: jlawyer
> authorization: Basic *
> user-agent: curl/7.84.0
> accept: application/json
> content-type: application/json
> content-length: 228
>
* We are completely uploaded and fine
* Connection state changed (MAX_CONCURRENT_STREAMS == 128)!
< HTTP/2 500
< server: openresty
< date: Thu, 08 Dec 2022 07:41:35 GMT
< content-length: 0
< expires: 0
< cache-control: no-cache, no-store, must-revalidate
< pragma: no-cache
<
* Connection #0 to host jlawyer left intact
```

Server Log (gekürzt. gesamtes kann gern zur Verfügung gestellt werden)
```
14:01:34,380 ERROR [org.jboss.as.ejb3.invocation] (default task-20) WFLYEJB0034: EJB Invocation failed on component AppUserBeanFacade for method public abstract com.jdimension.jlawyer.persistence.AppUserBean com.jdimension.jlawyer.persistence.AppUserBeanFacadeLocal.findByPrincipalId(java.lang.String): javax.ejb.EJBTransactionRolledbackException: No entity found for query
	[...]
	at com.jdimension.jlawyer.persistence.AppUserBeanFacadeLocal$$$view79.findByPrincipalId(Unknown Source)
	at com.jdimension.jlawyer.services.SystemManagement.getUser(SystemManagement.java:1212)
	[...]
	at com.jdimension.jlawyer.services.SystemManagementLocal$$$view9.getUser(Unknown Source)
	at org.jlawyer.io.rest.v6.TemplatesEndpointV6.addDocumentFromTemplate(TemplatesEndpointV6.java:847)
	[...]
Caused by: javax.persistence.NoResultException: No entity found for query
	at org.hibernate.query.internal.AbstractProducedQuery.getSingleResult(AbstractProducedQuery.java:1555)
	at com.jdimension.jlawyer.persistence.AppUserBeanFacade.findByPrincipalId(AppUserBeanFacade.java:694)
	[...]
	... 169 more

14:01:34,381 ERROR [org.jboss.as.ejb3.invocation] (default task-20) WFLYEJB0034: EJB Invocation failed on component SystemManagement for method public abstract com.jdimension.jlawyer.persistence.AppUserBean com.jdimension.jlawyer.services.SystemManagementLocal.getUser(java.lang.String): javax.ejb.EJBTransactionRolledbackException: No entity found for query
	at org.jboss.as.ejb3.tx.CMTTxInterceptor.invokeInCallerTx(CMTTxInterceptor.java:203)
	[...]
	at com.jdimension.jlawyer.persistence.AppUserBeanFacadeLocal$$$view79.findByPrincipalId(Unknown Source)
	at com.jdimension.jlawyer.services.SystemManagement.getUser(SystemManagement.java:1212)
	[...]
	at com.jdimension.jlawyer.services.SystemManagementLocal$$$view9.getUser(Unknown Source)
	at org.jlawyer.io.rest.v6.TemplatesEndpointV6.addDocumentFromTemplate(TemplatesEndpointV6.java:847)
	[...]
Caused by: javax.persistence.NoResultException: No entity found for query
	at org.hibernate.query.internal.AbstractProducedQuery.getSingleResult(AbstractProducedQuery.java:1555)
	at com.jdimension.jlawyer.persistence.AppUserBeanFacade.findByPrincipalId(AppUserBeanFacade.java:694)
	[...]
	... 169 more

14:01:34,382 ERROR [org.jlawyer.io.rest.v6.TemplatesEndpointV6] (default task-20) can not create document with template Vollmacht.docx in folder Vollmacht for case e76ea796ac16000d5d4c226b49b16ad0: javax.ejb.EJBTransactionRolledbackException: No entity found for query
	at org.jboss.as.ejb3.tx.CMTTxInterceptor.invokeInCallerTx(CMTTxInterceptor.java:203)
	at org.jboss.as.ejb3.tx.CMTTxInterceptor.required(CMTTxInterceptor.java:364)
	[...]
	at com.jdimension.jlawyer.persistence.AppUserBeanFacadeLocal$$$view79.findByPrincipalId(Unknown Source)
	at com.jdimension.jlawyer.services.SystemManagement.getUser(SystemManagement.java:1212)
	[...]
	at com.jdimension.jlawyer.services.SystemManagementLocal$$$view9.getUser(Unknown Source)
	at org.jlawyer.io.rest.v6.TemplatesEndpointV6.addDocumentFromTemplate(TemplatesEndpointV6.java:847)
	[...]
Caused by: javax.persistence.NoResultException: No entity found for query
	at org.hibernate.query.internal.AbstractProducedQuery.getSingleResult(AbstractProducedQuery.java:1555)
	at com.jdimension.jlawyer.persistence.AppUserBeanFacade.findByPrincipalId(AppUserBeanFacade.java:694)
	[...]
	... 169 more

```

Zusätzlich hätte ich noch eine Frage:
Im Client werden `AKTE_KURZRUBRUM` und `AKTE_WEGEN` automatisch gefüllt, geht das auch per API?

**Comment by j-dimension** [comment]
@timo0 scheinbar existiert entweder "Anwalt" oder "Sachbearbeiter" der Akte nicht als Nutzer im System.



> Im Client werden `AKTE_KURZRUBRUM` und `AKTE_WEGEN` automatisch gefüllt, geht das auch per API?

Das ist bereits umgesetzt, wird aber erst mit 2.3 veröffentlicht: https://github.com/jlawyerorg/j-lawyer-org/issues/1811

**Comment by timo0** [comment]
Es war kein Sachbearbeiter gesetzt. Danke für den Hinweis! Wie hätte ich das erkennen können? 

Leider geht es jetzt noch nicht durch:
```
14:01:33,547 ERROR [org.jlawyer.io.rest.v6.TemplatesEndpointV6] (default task-1372) can not create document with template Vollmacht.docx in folder Vollmacht for case e76ea796ac16000d5d4c226b49b16ad0: java.io.FileNotFoundException: /opt/jboss/j-lawyer-data/templatesVollmacht/Vollmacht.docx (No such file or directory)
	[...]	
	at com.jdimension.jlawyer.services.SystemManagement.copyFile(SystemManagement.java:992)
	at com.jdimension.jlawyer.services.ArchiveFileService.addDocumentFromTemplate(ArchiveFileService.java:3361)
	[...]
	at com.jdimension.jlawyer.services.ArchiveFileServiceLocal$$$view38.addDocumentFromTemplate(Unknown Source)
	[...]
```

Ich wüsste nicht, wo ich den fehlenden `/` einfügen sollte?

> Das ist bereits umgesetzt, wird aber erst mit 2.3 veröffentlicht: https://github.com/jlawyerorg/j-lawyer-org/issues/1811

Ich habe die aktuelle Vorschau-Version vom Server installiert. Dann könnte ich wahrscheinlich die Platzhalter weglassen?

**Comment by j-dimension** [comment]
> Es war kein Sachbearbeiter gesetzt. Danke für den Hinweis! Wie hätte ich das erkennen können?

Nee, das soll so nicht sein. Ich fixe das (und werde dazu das Ticket diesbezüglich schärfen). 



> Ich wüsste nicht, wo ich den fehlenden `/` einfügen sollte?

Den musst Du als Folder mit reinreichen - die Vorlagenordner können ja auch beliebig tief geschachtelt sein. Müsstest also 

`%2FVollmacht`

reinreichen.



> Ich habe die aktuelle Vorschau-Version vom Server installiert. Dann könnte ich wahrscheinlich die Platzhalter weglassen?

Nee, da war das noch nicht drin. Ich erstelle gerade einen Satz neue Installer für Dich. Müsstest Du in 20min runterladen können. Server 2.3.0.4 hat die Änderungen für diesen Endpunkt, aber noch nicht den Fix bzgl. der Sachbearbeiter / Anwalt-Werte.

**Comment by timo0** [comment]
> Den musst Du als Folder mit reinreichen 

Das wars, danke! Dachte, der erste `/` wäre implizit. Aber auch hier wäre ne Fehlermeldung über die API nett. :) 

Ich benutz die Docker Container als Basis für meine, aber die werden ja auch immer neu gebaut, oder?

**Comment by j-dimension** [comment]
> Ich benutz die Docker Container als Basis für meine, aber die werden ja auch immer neu gebaut, oder?

Ja, wenn dieses Build hier durch ist (https://github.com/jlawyerorg/j-lawyer-org/actions/runs/3648821126), kannst Du den Server in Version 2.3.0.4 nehmen. Der hat

- ein automatisches Hinzufügen des führendes / für den Folder
- eine Behandlung für leere / ungültige Anwalt / Sachbearbeiter

**Comment by timo0** [comment]
Ein Traum! Vielen Dank funktioniert perfekt :)
