### ISSUE TITLE
[BUG] Nullpointer beim Öffnen einer Akte, die via API erstellt wurde

### ISSUE THREAD

**Issue by Linkki2021** [jlawyerorg/j-lawyer-org#1840]
Wenn wir Fälle via API anlegen und diesen dann in j-lawyer öffnen möchten erhalten wir häufig den Fehler "Fehler beim Laden des Editors: null".

Die Daten werden korrekt übertragen, der Fall ist bereits angelegt. Aber wir können ihn nicht öffnen. Wenn man j-lawyer als User schließt und wieder öffnet taucht der Fehler nicht wieder auf.

Uns ist unklar, was den Fehler verursacht (passiert nicht immer), was der Fehler beschreibt,  wie wir ihn vermeiden können - die Anlage  via API an sich funktioniert reibungslos und ohne Fehlerausgabe.
![image](https://user-images.githubusercontent.com/77149788/208120271-24963c08-bc91-480a-9dbd-1453daaeeb87.png)

**Comment by j-dimension** [comment]
Bitte das client.log des Arbeitsplatzes per E-Mail bereitstellen.

> https://www.j-lawyer.org/?topic=wo-findet-man-die-fehlerprotokolle-des-j-lawyer-org-servers-und-clients

**Comment by j-dimension** [comment]
```
2022-12-19 12:00:43,310 ERROR [com.jdimension.jlawyer.client.editors.files.QuickArchiveFileSearchPanel] Error creating editor from class com.jdimension.jlawyer.client.editors.files.EditArchiveFileDetailsPanel
java.lang.NullPointerException: null
	at com.jdimension.jlawyer.client.utils.DocumentSizeFilter.replace(DocumentSizeFilter.java:714) ~[j-lawyer-client.jar:?]
	at javax.swing.text.AbstractDocument.replace(AbstractDocument.java:667) ~[?:?]
	at javax.swing.text.JTextComponent.setText(JTextComponent.java:1729) ~[?:?]
	at com.jdimension.jlawyer.client.editors.files.ArchiveFilePanel.setArchiveFileDTO(ArchiveFilePanel.java:1196) ~[j-lawyer-client.jar:?]
	at com.jdimension.jlawyer.client.editors.files.ArchiveFilePanel.setArchiveFileDTO(ArchiveFilePanel.java:1168) ~[j-lawyer-client.jar:?]
	at com.jdimension.jlawyer.client.editors.files.QuickArchiveFileSearchPanel.useSelection(QuickArchiveFileSearchPanel.java:1084) [j-lawyer-client.jar:?]
	at com.jdimension.jlawyer.client.editors.files.QuickArchiveFileSearchPanel.tblResultsMouseClicked(QuickArchiveFileSearchPanel.java:1096) [j-lawyer-client.jar:?]
	at com.jdimension.jlawyer.client.editors.files.QuickArchiveFileSearchPanel$9.mouseClicked(QuickArchiveFileSearchPanel.java:900) [j-lawyer-client.jar:?]
```

**Comment by j-dimension** [comment]
Gebt Ihr einen Wert für die "Notiz" der Akte mit, beim Erstellen via API?

Wenn nicht, könnt Ihr testweise mal einen leeren String mitgeben?

**Comment by Linkki2021** [comment]
Haben bislang keinen Wert mitgegeben. Das scheint das Problem zu beheben.

Konnten keinen Null-Pointer mehr produzieren. Falls das trotz Stringmitgabe nochmal vorkommt melden wir uns.

Danke DIr

**Comment by j-dimension** [comment]
@Linkki2021 danke. Muss meinerseits trotzdem gefixt werden, aber so müsst Ihr nicht auf das nächste Release warten.
