### ISSUE TITLE
[beA]-Schnittstellenfehler "0703 - Subject couldn't be transcoded!" beim Laden der Ordnerübersicht (Papierkorb)

### ISSUE THREAD

**Issue by stm9x9** [jlawyerorg/j-lawyer-org#1866]
Ich bekomme heute auf einmal folgenden Fehler, wenn ich den beA-Papierkorb öffnen will:

![image](https://user-images.githubusercontent.com/29924198/214576448-8d053a98-81dc-421d-8062-df7a65ad2e09.png)

client.log:

```
2023-01-25 14:29:12,333 WARN  [org.jlawyer.bea.BeaWrapper] Retrying to get folder overview...
2023-01-25 14:29:14,787 ERROR [org.jlawyer.bea.BeaWrapper] Unable to get folder overview
de.brak.bea.application.dto.soap.types6.BeaFault: 0703 - Subject couldn't be transcoded!
	at jdk.internal.reflect.GeneratedConstructorAccessor281.newInstance(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:490) ~[?:?]
	at com.sun.xml.ws.fault.SOAPFaultBuilder.createException(SOAPFaultBuilder.java:117) ~[rt-2.3.3.jar:2.3.3]
	at com.sun.xml.ws.client.sei.StubHandler.readResponse(StubHandler.java:223) ~[rt-2.3.3.jar:2.3.3]
	at com.sun.xml.ws.db.DatabindingImpl.deserializeResponse(DatabindingImpl.java:176) ~[rt-2.3.3.jar:2.3.3]
	at com.sun.xml.ws.db.DatabindingImpl.deserializeResponse(DatabindingImpl.java:263) ~[rt-2.3.3.jar:2.3.3]
	at com.sun.xml.ws.client.sei.SyncMethodHandler.invoke(SyncMethodHandler.java:89) ~[rt-2.3.3.jar:2.3.3]
	at com.sun.xml.ws.client.sei.SyncMethodHandler.invoke(SyncMethodHandler.java:62) ~[rt-2.3.3.jar:2.3.3]
	at com.sun.xml.ws.client.sei.SEIStub.invoke(SEIStub.java:131) ~[rt-2.3.3.jar:2.3.3]
	at com.sun.proxy.$Proxy70.getFolderOverview(Unknown Source) ~[?:?]
	at org.jlawyer.bea.BeaWrapper.getFolderOverview(BeaWrapper.java:2054) [j-lawyer-bea-wrapper.jar:?]
	at org.jlawyer.bea.BeaWrapper.getFolderOverview(BeaWrapper.java:2016) [j-lawyer-bea-wrapper.jar:?]
	at com.jdimension.jlawyer.client.bea.BeaAccess.getFolderOverview(BeaAccess.java:1057) [j-lawyer-client.jar:?]
	at com.jdimension.jlawyer.client.bea.LoadBeaFolderAction.<init>(LoadBeaFolderAction.java:716) [j-lawyer-client.jar:?]
	at com.jdimension.jlawyer.client.bea.BeaInboxPanel.treeFoldersValueChangedImpl(BeaInboxPanel.java:1525) [j-lawyer-client.jar:?]
	at com.jdimension.jlawyer.client.bea.BeaInboxPanel.treeFoldersValueChanged(BeaInboxPanel.java:1469) [j-lawyer-client.jar:?]
	at com.jdimension.jlawyer.client.bea.BeaInboxPanel$15.valueChanged(BeaInboxPanel.java:1259) [j-lawyer-client.jar:?]
	at javax.swing.JTree.fireValueChanged(JTree.java:2967) [?:?]
	at javax.swing.JTree$TreeSelectionRedirector.valueChanged(JTree.java:3456) [?:?]
	at javax.swing.tree.DefaultTreeSelectionModel.fireValueChanged(DefaultTreeSelectionModel.java:641) [?:?]
	at javax.swing.tree.DefaultTreeSelectionModel.notifyPathChange(DefaultTreeSelectionModel.java:1111) [?:?]
	at javax.swing.tree.DefaultTreeSelectionModel.setSelectionPaths(DefaultTreeSelectionModel.java:297) [?:?]
	at javax.swing.tree.DefaultTreeSelectionModel.setSelectionPath(DefaultTreeSelectionModel.java:191) [?:?]
	at javax.swing.JTree.setSelectionPath(JTree.java:1656) [?:?]
	at javax.swing.plaf.basic.BasicTreeUI.selectPathForEvent(BasicTreeUI.java:2736) [?:?]
	at javax.swing.plaf.basic.BasicTreeUI$Handler.handleSelection(BasicTreeUI.java:4016) [?:?]
	at javax.swing.plaf.basic.BasicTreeUI$Handler.mousePressed(BasicTreeUI.java:3955) [?:?]
	at javax.swing.plaf.basic.BasicTreeUI$MouseHandler.mousePressed(BasicTreeUI.java:3208) [?:?]
	at com.formdev.flatlaf.ui.FlatTreeUI$1.mousePressed(FlatTreeUI.java:218) [flatlaf-2.6.jar:2.6]
	at java.awt.AWTEventMulticaster.mousePressed(AWTEventMulticaster.java:287) [?:?]
	at java.awt.Component.processMouseEvent(Component.java:6632) [?:?]
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3342) [?:?]
	at java.awt.Component.processEvent(Component.java:6400) [?:?]
	at java.awt.Container.processEvent(Container.java:2263) [?:?]
	at java.awt.Component.dispatchEventImpl(Component.java:5011) [?:?]
	at java.awt.Container.dispatchEventImpl(Container.java:2321) [?:?]
	at java.awt.Component.dispatchEvent(Component.java:4843) [?:?]
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4918) [?:?]
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4544) [?:?]
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4488) [?:?]
	at java.awt.Container.dispatchEventImpl(Container.java:2307) [?:?]
	at java.awt.Window.dispatchEventImpl(Window.java:2772) [?:?]
	at java.awt.Component.dispatchEvent(Component.java:4843) [?:?]
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:772) [?:?]
	at java.awt.EventQueue$4.run(EventQueue.java:721) [?:?]
	at java.awt.EventQueue$4.run(EventQueue.java:715) [?:?]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:?]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85) [?:?]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95) [?:?]
	at java.awt.EventQueue$5.run(EventQueue.java:745) [?:?]
	at java.awt.EventQueue$5.run(EventQueue.java:743) [?:?]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:?]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85) [?:?]
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:742) [?:?]
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203) [?:?]
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124) [?:?]
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113) [?:?]
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109) [?:?]
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101) [?:?]
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:90) [?:?]
2023-01-25 14:29:14,788 ERROR [org.jlawyer.bea.BeaWrapper] Unable to get beA folder overview for folder Papierkorb
org.jlawyer.bea.BeaWrapperException: Unable to get beA folder overview for folder Papierkorb
	at org.jlawyer.bea.BeaWrapper.getFolderOverview(BeaWrapper.java:2061) [j-lawyer-bea-wrapper.jar:?]
	at org.jlawyer.bea.BeaWrapper.getFolderOverview(BeaWrapper.java:2016) [j-lawyer-bea-wrapper.jar:?]
	at com.jdimension.jlawyer.client.bea.BeaAccess.getFolderOverview(BeaAccess.java:1057) [j-lawyer-client.jar:?]
	at com.jdimension.jlawyer.client.bea.LoadBeaFolderAction.<init>(LoadBeaFolderAction.java:716) [j-lawyer-client.jar:?]
	at com.jdimension.jlawyer.client.bea.BeaInboxPanel.treeFoldersValueChangedImpl(BeaInboxPanel.java:1525) [j-lawyer-client.jar:?]
	at com.jdimension.jlawyer.client.bea.BeaInboxPanel.treeFoldersValueChanged(BeaInboxPanel.java:1469) [j-lawyer-client.jar:?]
	at com.jdimension.jlawyer.client.bea.BeaInboxPanel$15.valueChanged(BeaInboxPanel.java:1259) [j-lawyer-client.jar:?]
	at javax.swing.JTree.fireValueChanged(JTree.java:2967) [?:?]
	at javax.swing.JTree$TreeSelectionRedirector.valueChanged(JTree.java:3456) [?:?]
	at javax.swing.tree.DefaultTreeSelectionModel.fireValueChanged(DefaultTreeSelectionModel.java:641) [?:?]
	at javax.swing.tree.DefaultTreeSelectionModel.notifyPathChange(DefaultTreeSelectionModel.java:1111) [?:?]
	at javax.swing.tree.DefaultTreeSelectionModel.setSelectionPaths(DefaultTreeSelectionModel.java:297) [?:?]
	at javax.swing.tree.DefaultTreeSelectionModel.setSelectionPath(DefaultTreeSelectionModel.java:191) [?:?]
	at javax.swing.JTree.setSelectionPath(JTree.java:1656) [?:?]
	at javax.swing.plaf.basic.BasicTreeUI.selectPathForEvent(BasicTreeUI.java:2736) [?:?]
	at javax.swing.plaf.basic.BasicTreeUI$Handler.handleSelection(BasicTreeUI.java:4016) [?:?]
	at javax.swing.plaf.basic.BasicTreeUI$Handler.mousePressed(BasicTreeUI.java:3955) [?:?]
	at javax.swing.plaf.basic.BasicTreeUI$MouseHandler.mousePressed(BasicTreeUI.java:3208) [?:?]
	at com.formdev.flatlaf.ui.FlatTreeUI$1.mousePressed(FlatTreeUI.java:218) [flatlaf-2.6.jar:2.6]
	at java.awt.AWTEventMulticaster.mousePressed(AWTEventMulticaster.java:287) [?:?]
	at java.awt.Component.processMouseEvent(Component.java:6632) [?:?]
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3342) [?:?]
	at java.awt.Component.processEvent(Component.java:6400) [?:?]
	at java.awt.Container.processEvent(Container.java:2263) [?:?]
	at java.awt.Component.dispatchEventImpl(Component.java:5011) [?:?]
	at java.awt.Container.dispatchEventImpl(Container.java:2321) [?:?]
	at java.awt.Component.dispatchEvent(Component.java:4843) [?:?]
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4918) [?:?]
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4544) [?:?]
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4488) [?:?]
	at java.awt.Container.dispatchEventImpl(Container.java:2307) [?:?]
	at java.awt.Window.dispatchEventImpl(Window.java:2772) [?:?]
	at java.awt.Component.dispatchEvent(Component.java:4843) [?:?]
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:772) [?:?]
	at java.awt.EventQueue$4.run(EventQueue.java:721) [?:?]
	at java.awt.EventQueue$4.run(EventQueue.java:715) [?:?]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:?]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85) [?:?]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95) [?:?]
	at java.awt.EventQueue$5.run(EventQueue.java:745) [?:?]
	at java.awt.EventQueue$5.run(EventQueue.java:743) [?:?]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:?]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85) [?:?]
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:742) [?:?]
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203) [?:?]
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124) [?:?]
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113) [?:?]
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109) [?:?]
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101) [?:?]
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:90) [?:?]
2023-01-25 14:29:14,789 ERROR [com.jdimension.jlawyer.client.bea.BeaInboxPanel] Error getting contents of folder
org.jlawyer.bea.BeaWrapperException: org.jlawyer.bea.BeaWrapperException: Unable to get beA folder overview for folder Papierkorb
	at org.jlawyer.bea.BeaWrapper.getFolderOverview(BeaWrapper.java:2278) ~[j-lawyer-bea-wrapper.jar:?]
	at org.jlawyer.bea.BeaWrapper.getFolderOverview(BeaWrapper.java:2016) ~[j-lawyer-bea-wrapper.jar:?]
	at com.jdimension.jlawyer.client.bea.BeaAccess.getFolderOverview(BeaAccess.java:1057) ~[j-lawyer-client.jar:?]
	at com.jdimension.jlawyer.client.bea.LoadBeaFolderAction.<init>(LoadBeaFolderAction.java:716) ~[j-lawyer-client.jar:?]
	at com.jdimension.jlawyer.client.bea.BeaInboxPanel.treeFoldersValueChangedImpl(BeaInboxPanel.java:1525) [j-lawyer-client.jar:?]
	at com.jdimension.jlawyer.client.bea.BeaInboxPanel.treeFoldersValueChanged(BeaInboxPanel.java:1469) [j-lawyer-client.jar:?]
	at com.jdimension.jlawyer.client.bea.BeaInboxPanel$15.valueChanged(BeaInboxPanel.java:1259) [j-lawyer-client.jar:?]
	at javax.swing.JTree.fireValueChanged(JTree.java:2967) [?:?]
	at javax.swing.JTree$TreeSelectionRedirector.valueChanged(JTree.java:3456) [?:?]
	at javax.swing.tree.DefaultTreeSelectionModel.fireValueChanged(DefaultTreeSelectionModel.java:641) [?:?]
	at javax.swing.tree.DefaultTreeSelectionModel.notifyPathChange(DefaultTreeSelectionModel.java:1111) [?:?]
	at javax.swing.tree.DefaultTreeSelectionModel.setSelectionPaths(DefaultTreeSelectionModel.java:297) [?:?]
	at javax.swing.tree.DefaultTreeSelectionModel.setSelectionPath(DefaultTreeSelectionModel.java:191) [?:?]
	at javax.swing.JTree.setSelectionPath(JTree.java:1656) [?:?]
	at javax.swing.plaf.basic.BasicTreeUI.selectPathForEvent(BasicTreeUI.java:2736) [?:?]
	at javax.swing.plaf.basic.BasicTreeUI$Handler.handleSelection(BasicTreeUI.java:4016) [?:?]
	at javax.swing.plaf.basic.BasicTreeUI$Handler.mousePressed(BasicTreeUI.java:3955) [?:?]
	at javax.swing.plaf.basic.BasicTreeUI$MouseHandler.mousePressed(BasicTreeUI.java:3208) [?:?]
	at com.formdev.flatlaf.ui.FlatTreeUI$1.mousePressed(FlatTreeUI.java:218) [flatlaf-2.6.jar:2.6]
	at java.awt.AWTEventMulticaster.mousePressed(AWTEventMulticaster.java:287) [?:?]
	at java.awt.Component.processMouseEvent(Component.java:6632) [?:?]
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3342) [?:?]
	at java.awt.Component.processEvent(Component.java:6400) [?:?]
	at java.awt.Container.processEvent(Container.java:2263) [?:?]
	at java.awt.Component.dispatchEventImpl(Component.java:5011) [?:?]
	at java.awt.Container.dispatchEventImpl(Container.java:2321) [?:?]
	at java.awt.Component.dispatchEvent(Component.java:4843) [?:?]
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4918) [?:?]
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4544) [?:?]
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4488) [?:?]
	at java.awt.Container.dispatchEventImpl(Container.java:2307) [?:?]
	at java.awt.Window.dispatchEventImpl(Window.java:2772) [?:?]
	at java.awt.Component.dispatchEvent(Component.java:4843) [?:?]
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:772) [?:?]
	at java.awt.EventQueue$4.run(EventQueue.java:721) [?:?]
	at java.awt.EventQueue$4.run(EventQueue.java:715) [?:?]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:?]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85) [?:?]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95) [?:?]
	at java.awt.EventQueue$5.run(EventQueue.java:745) [?:?]
	at java.awt.EventQueue$5.run(EventQueue.java:743) [?:?]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:?]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85) [?:?]
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:742) [?:?]
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203) [?:?]
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124) [?:?]
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113) [?:?]
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109) [?:?]
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101) [?:?]
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:90) [?:?]
Caused by: org.jlawyer.bea.BeaWrapperException: Unable to get beA folder overview for folder Papierkorb
	at org.jlawyer.bea.BeaWrapper.getFolderOverview(BeaWrapper.java:2061) ~[j-lawyer-bea-wrapper.jar:?]
	... 49 more
2023-01-25 14:30:05,134 WARN  [org.ehcache.impl.internal.store.heap.OnHeapStore] Max Object Graph Size reached for the object : [B@d50bddb

```

**Comment by j-dimension** [comment]
Hier hilft nur auf Selbstheilung warten oder den beA-Support kontaktieren. 

0703 - Subject couldn't be transcoded!

kommt direkt aus der Schnittstelle, und ich habe keine Möglichkeit und auch keine Doku, was der Fehlercode bedeutet.
