### ISSUE TITLE
[beA] Client re-connect zu beA nach power suspend

### ISSUE THREAD

**Issue by LazyGuy21No** [jlawyerorg/j-lawyer-org#1888]
Das Thema "Abbrüche zum beA" ist im Alltagsbetrieb mE weitgehend gelöst. Ich bemerke (MacOS 13.2.1.) aber noch Folgendes:

Wenn ich abends den Rechner zuklappe und morgens weiterarbeiten will, ohne mit beim JL abgemeldet zu haben, ist die Verbindung zum beA-Server leider weg und kommt auch wirklich erst wieder, wenn ich den Client neu starte.

Idee: Prüfung z.B. alle 15 Minuten, ob die Verbindung noch steht und falls nicht die Verbindung neu starten. 

Alternativ: "bemerken", dass der Rechner aus dem Power Suspend kommt

Alternativ: könnte die Verbindung zum beA-System nicht ohnehin auf den Server wandern?

**Comment by j-dimension** [comment]
Hmm... genau so ein Reconnect ist implementiert. Hat aber natürlich ein gewisses Intervall, d.h. nach einem Suspend kann es etwas dauern, bis die Verbindung neu aufgebaut wird. 

Ein Suspend-Signal vom Betriebssystem an die Anwendung ist m.W. nicht plattformunabhängig verfügbar.

Ein Verschieben der Integration auf den Server wäre auch mein Wunsch, so ist das bspw. auch mit Sipgate, Nextcloud etc. umgesetzt. Nur bei der BRAK geht das nicht, da die Bibliotheken keine zwei unterschiedlichen Verbindungen innerhalb eines Prozesses ermöglichen. Zwei unterschiedliche Nutzer mit zwei unterschiedlichen Tokens können also nicht innerhalb eines Prozesses zum beA verbinden.

**Comment by j-dimension** [comment]
Du kannst mir gern mal ein client.log senden, in dieser Vorgehensweise:

- Suspend
- 20min warten
- client.log senden

**Comment by stm9x9** [comment]
> Ein Verschieben der Integration auf den Server wäre auch mein Wunsch, so ist das bspw. auch mit Sipgate, Nextcloud etc. umgesetzt. Nur bei der BRAK geht das nicht, da die Bibliotheken keine zwei unterschiedlichen Verbindungen innerhalb eines Prozesses ermöglichen. Zwei unterschiedliche Nutzer mit zwei unterschiedlichen Tokens können also nicht innerhalb eines Prozesses zum beA verbinden.

Soweit ich das bei anderen KSW verstanden habe, wo beA im Hintergrund läuft, wird da auch nur mit einem Account, vorzugsweise einem Mitarbeiter-Account (und nur beim Einzelkämpfer dann mit seinem persönlichen Anwalts-Account) verbunden. Der Nachteil wäre dann, verstehe ich das richtig?, daß dann kein Anwalt ohne qeS einfach mit nur einfacher Signatur und eigenem Account aka über einen sicheren Übermittlungsweg senden kann? Das scheinen die anderen ja dann in Kauf zu nehmen. Bzw. viele lassen schon aus Haftungsgründen lieber die "sorgsam angeleitete, bislang immer fehlerfrei arbeitende Refa" versenden statt den Anwalt.

Wäre das eine Option für jl? Also wirklich als Option: a) mache es dir einfach und laß alles den Server machen, dafür müssen aber alle bei Euch qe-signieren oder b) mache es wie gehabt mit deinem privaten Anwaltsaccount, dann aber lokal auf deinem jl-Client?

Wobei jl ja leider noch (zb für eEBs) das Problem hat, daß wir nicht innerhalb von jl signieren können. Wird das signieren (also nur die normale Kartensignatur, nicht Fernsignatur) eigentlich über die beA-Library als Funktion angeboten oder müßte ds für jl komplett neu geschrieben werden?

**Comment by j-dimension** [comment]
> Der Nachteil wäre dann, verstehe ich das richtig?, daß dann kein Anwalt ohne qeS einfach mit nur einfacher Signatur und eigenem Account aka über einen sicheren Übermittlungsweg senden kann?

Exakt.



> Wäre das eine Option für jl? Also wirklich als Option: a) mache es dir einfach und laß alles den Server machen, dafür müssen aber alle bei Euch qe-signieren oder b) mache es wie gehabt mit deinem privaten Anwaltsaccount, dann aber lokal auf deinem jl-Client?

Technisch machbar.



> Wird das signieren (also nur die normale Kartensignatur, nicht Fernsignatur) eigentlich über die beA-Library als Funktion angeboten oder müßte ds für jl komplett neu geschrieben werden?

Das ist nicht Bestandteil der Library / API.

**Comment by j-dimension** [comment]
```
2024-10-10 14:13:49,583 ERROR [com.jdimension.jlawyer.client.bea.BeaInboxPanel] beA logout failed
org.jlawyer.bea.BeaWrapperException: de.brak.bea.application.dto.soap.types.BeaFault: 9999 - General error processing request.
	at org.jlawyer.bea.BeaWrapper.logout(BeaWrapper.java:1440) ~[j-lawyer-bea-wrapper.jar:?]
	at com.jdimension.jlawyer.client.bea.BeaAccess.logout(BeaAccess.java:921) ~[j-lawyer-client.jar:?]
	at com.jdimension.jlawyer.client.bea.BeaInboxPanel.logout(BeaInboxPanel.java:1951) ~[j-lawyer-client.jar:?]
	at com.jdimension.jlawyer.client.bea.BeaInboxPanel.cmdLogoutActionPerformed(BeaInboxPanel.java:1960) ~[j-lawyer-client.jar:?]
	at com.jdimension.jlawyer.client.bea.BeaInboxPanel$20.actionPerformed(BeaInboxPanel.java:1353) ~[j-lawyer-client.jar:?]
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1972) ~[?:?]
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2313) ~[?:?]
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405) ~[?:?]
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262) ~[?:?]
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:279) ~[?:?]
	at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:297) ~[?:?]
	at java.awt.Component.processMouseEvent(Component.java:6626) ~[?:?]
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3389) ~[?:?]
	at java.awt.Component.processEvent(Component.java:6391) ~[?:?]
	at java.awt.Container.processEvent(Container.java:2266) ~[?:?]
	at java.awt.Component.dispatchEventImpl(Component.java:5001) ~[?:?]
	at java.awt.Container.dispatchEventImpl(Container.java:2324) ~[?:?]
	at java.awt.Component.dispatchEvent(Component.java:4833) ~[?:?]
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4948) ~[?:?]
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4575) ~[?:?]
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4516) ~[?:?]
	at java.awt.Container.dispatchEventImpl(Container.java:2310) ~[?:?]
	at java.awt.Window.dispatchEventImpl(Window.java:2780) ~[?:?]
	at java.awt.Component.dispatchEvent(Component.java:4833) ~[?:?]
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:775) ~[?:?]
	at java.awt.EventQueue$4.run(EventQueue.java:720) ~[?:?]
	at java.awt.EventQueue$4.run(EventQueue.java:714) ~[?:?]
	at java.security.AccessController.doPrivileged(AccessController.java:399) ~[?:?]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86) ~[?:?]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:97) ~[?:?]
	at java.awt.EventQueue$5.run(EventQueue.java:747) ~[?:?]
	at java.awt.EventQueue$5.run(EventQueue.java:745) ~[?:?]
	at java.security.AccessController.doPrivileged(AccessController.java:399) ~[?:?]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86) ~[?:?]
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:744) ~[?:?]
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203) ~[?:?]
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124) ~[?:?]
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113) ~[?:?]
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109) ~[?:?]
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101) ~[?:?]
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:90) ~[?:?]
Caused by: de.brak.bea.application.dto.soap.types.BeaFault: 9999 - General error processing request.
	at jdk.internal.reflect.GeneratedConstructorAccessor133.newInstance(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?]
	at com.sun.xml.ws.fault.SOAPFaultBuilder.createException(SOAPFaultBuilder.java:117) ~[rt-2.3.3.jar:2.3.3]
	at com.sun.xml.ws.client.sei.StubHandler.readResponse(StubHandler.java:223) ~[rt-2.3.3.jar:2.3.3]
	at com.sun.xml.ws.db.DatabindingImpl.deserializeResponse(DatabindingImpl.java:176) ~[rt-2.3.3.jar:2.3.3]
	at com.sun.xml.ws.db.DatabindingImpl.deserializeResponse(DatabindingImpl.java:263) ~[rt-2.3.3.jar:2.3.3]
	at com.sun.xml.ws.client.sei.SyncMethodHandler.invoke(SyncMethodHandler.java:89) ~[rt-2.3.3.jar:2.3.3]
	at com.sun.xml.ws.client.sei.SyncMethodHandler.invoke(SyncMethodHandler.java:62) ~[rt-2.3.3.jar:2.3.3]
	at com.sun.xml.ws.client.sei.SEIStub.invoke(SEIStub.java:131) ~[rt-2.3.3.jar:2.3.3]
	at jdk.proxy2.$Proxy71.logoutUser(Unknown Source) ~[?:?]
	at org.jlawyer.bea.BeaWrapper.logout(BeaWrapper.java:1434) ~[j-lawyer-bea-wrapper.jar:?]
	... 40 more
```

**Comment by j-dimension** [comment]
Der beA-Server wirft einen Fehler beim Logout, wenn eine abgelaufene Session-ID mitgegeben wird.

Ich schaue mir das an und überlege mir einen Workaround.

**Comment by j-dimension** [comment]
Das Aus- und Einloggen sollte nun zuverlässig funktionieren.
