### ISSUE TITLE
[BUG] Installer muss vor Update den "lib"-Ordner löschen

### ISSUE THREAD

**Issue by j-dimension** [jlawyerorg/j-lawyer-org#1923]
Sonst kann es nach Bibliotheksupdates beim Start des Clients bspw. zu soetwas kommen:

```
java.lang.NoSuchMethodError: 'java.lang.ClassLoader org.apache.logging.log4j.util.StackLocatorUtil.getCallerClassLoader(int)'
	at org.apache.log4j.Logger.getLogger(Logger.java:40)
	at com.jdimension.jlawyer.client.settings.ClientSettings.<clinit>(ClientSettings.java:793)
	at com.jdimension.jlawyer.client.Main.main(Main.java:785)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.exe4j.runtime.LauncherEngine.launch(LauncherEngine.java:84)
	at com.install4j.runtime.launcher.MacLauncher.main(MacLauncher.java:52)
```

**Comment by j-dimension** [comment]
Client-Installer aktualisiert
