### ISSUE TITLE
[BUG] nextcloud Kalender Dialog "Service temporarily unavailable"

### ISSUE THREAD

**Issue by hackvokat** [jlawyerorg/j-lawyer-org#1929]
Hallo,

ich kann momentan keine Nextcloud Kalender mehr in j-lawyer editieren oder neu anlegen.

(Einstellungen->Kalender->Kalender und Synchronisation)

Sobald ich einen hinterlegten Kalender anklicke kommt die Fehlermeldung "Service temporarily unavailable".

Im client.log steht dazu folgendes:
`2023-03-29 15:27:03,445 INFO  [org.apache.commons.httpclient.auth.AuthChallengeProcessor] basic authentication scheme selected
2023-03-29 15:27:03,652 ERROR [com.jdimension.jlawyer.client.configuration.CalendarSetupDialog] Error connecting to server
org.apache.jackrabbit.webdav.DavException: Service Temporarily Unavailable
	at org.apache.jackrabbit.webdav.client.methods.DavMethodBase.getResponseException(DavMethodBase.java:165) ~[j-lawyer-cloud.jar:?]
	at org.apache.jackrabbit.webdav.client.methods.DavMethodBase.getResponseBodyAsMultiStatus(DavMethodBase.java:91) ~[j-lawyer-cloud.jar:?]
	at org.jlawyer.cloud.NextcloudCalendarConnector.getAllCalendars(NextcloudCalendarConnector.java:759) ~[j-lawyer-cloud.jar:?]
	at com.jdimension.jlawyer.client.configuration.CalendarSetupDialog.cmdGetCloudCalendarsActionPerformed(CalendarSetupDialog.java:1278) [j-lawyer-client.jar:?]
	at com.jdimension.jlawyer.client.configuration.CalendarSetupDialog$10.actionPerformed(CalendarSetupDialog.java:942) [j-lawyer-client.jar:?]
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1967) [?:?]
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2308) [?:?]
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405) [?:?]
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262) [?:?]
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:279) [?:?]
	at java.awt.Component.processMouseEvent(Component.java:6635) [?:?]
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3342) [?:?]
	at java.awt.Component.processEvent(Component.java:6400) [?:?]
	at java.awt.Container.processEvent(Container.java:2263) [?:?]
	at java.awt.Component.dispatchEventImpl(Component.java:5011) [?:?]
	at java.awt.Container.dispatchEventImpl(Container.java:2321) [?:?]
	at java.awt.Component.dispatchEvent(Component.java:4843) [?:?]
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4918) [?:?]
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4547) [?:?]
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4488) [?:?]
	at java.awt.Container.dispatchEventImpl(Container.java:2307) [?:?]
	at java.awt.Window.dispatchEventImpl(Window.java:2772) [?:?]
	at java.awt.Component.dispatchEvent(Component.java:4843) [?:?]
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:772) [?:?]
	at java.awt.EventQueue$4.run(EventQueue.java:721) [?:?]
	at java.awt.EventQueue$4.run(EventQueue.java:715) [?:?]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:?]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85) [?:?]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95) [?:?]
	at java.awt.EventQueue$5.run(EventQueue.java:745) [?:?]
	at java.awt.EventQueue$5.run(EventQueue.java:743) [?:?]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:?]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85) [?:?]
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:742) [?:?]
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203) [?:?]
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124) [?:?]
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:117) [?:?]
	at java.awt.WaitDispatchSupport$2.run(WaitDispatchSupport.java:190) [?:?]
	at java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:235) [?:?]
	at java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:233) [?:?]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:?]
	at java.awt.WaitDispatchSupport.enter(WaitDispatchSupport.java:233) [?:?]
	at java.awt.Dialog.show(Dialog.java:1070) [?:?]
	at java.awt.Component.show(Component.java:1716) [?:?]
	at java.awt.Component.setVisible(Component.java:1663) [?:?]
	at java.awt.Window.setVisible(Window.java:1031) [?:?]
	at java.awt.Dialog.setVisible(Dialog.java:1005) [?:?]
	at com.jdimension.jlawyer.client.JKanzleiGUI.mnuCalendarSetupActionPerformed(JKanzleiGUI.java:2486) [j-lawyer-client.jar:?]
	at com.jdimension.jlawyer.client.JKanzleiGUI$45.actionPerformed(JKanzleiGUI.java:1625) [j-lawyer-client.jar:?]
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1967) [?:?]
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2308) [?:?]
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405) [?:?]
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262) [?:?]
	at javax.swing.AbstractButton.doClick(AbstractButton.java:369) [?:?]
	at com.apple.laf.ScreenMenuItem.actionPerformed(ScreenMenuItem.java:129) [?:?]
	at java.awt.MenuItem.processActionEvent(MenuItem.java:690) [?:?]
	at java.awt.MenuItem.processEvent(MenuItem.java:649) [?:?]
	at java.awt.MenuComponent.dispatchEventImpl(MenuComponent.java:375) [?:?]
	at java.awt.MenuComponent.dispatchEvent(MenuComponent.java:363) [?:?]
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:775) [?:?]
	at java.awt.EventQueue$4.run(EventQueue.java:721) [?:?]
	at java.awt.EventQueue$4.run(EventQueue.java:715) [?:?]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:?]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85) [?:?]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95) [?:?]
	at java.awt.EventQueue$5.run(EventQueue.java:745) [?:?]
	at java.awt.EventQueue$5.run(EventQueue.java:743) [?:?]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:?]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85) [?:?]
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:742) [?:?]
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203) [?:?]
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124) [?:?]
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113) [?:?]
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109) [?:?]
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101) [?:?]
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:90) [?:?]
`
Aus der Fehlermeldung werde ich nicht schlau. Kann jemand weiterhelfen?

Die Synchronisation mit den bereits angelegten Kalendern funktioniert weiterhin.

**Comment by j-dimension** [comment]
Dann mal in die Webserver-Logs schauen, warum 503 geworfen wird.

**Comment by j-dimension** [comment]
Okay, ich sehe das hier in einer Installation auch. Muss ich anschauen.

**Comment by j-dimension** [comment]
https://stackoverflow.com/questions/1793979/registering-multiple-keystores-in-jvm

**Comment by j-dimension** [comment]
Ich sehe das mit neueren Nextcloudinstallationen. Alle 24.x funktionieren, einige 25.x nicht. 

Request für das Ermitteln der Kalender eines Users:

`curl -s -X PROPFIND -u nutzer:passwort -H "Content-Type: text/xml" -i --data-binary "propfind.txt" https://cloud.com/remote.php/dav/calendars/nutzer/`

funktioniert in der Shell mit Payload

```
<d:propfind xmlns:d="DAV:" xmlns:cs="http://calendarserver.org/ns/">
<d:prop>
<d:displayname />
<cs:getctag />
</d:prop>
</d:propfind>
```

**Comment by j-dimension** [comment]
@hackvokat bitte mal diese Datei

> https://cloud.j-dimension.com/index.php/s/wscJLx3KDCKoEWm?path=%2FVorschau%2F2023-03-30%20Nextcloud-Fix%20Kalendersetup

in den Unterordner "lib" des Clients kopieren. Alte Datei vorher sichern. Dann Rückmeldung, ob das Problem behoben ist.

**Comment by hackvokat** [comment]
Funktioniert wieder, vielen Dank für die schnelle Lösung!
