### ISSUE TITLE
Backupmanager needs to wait for mysql restore process to finish

### ISSUE THREAD

**Issue by j-dimension** [jlawyerorg/j-lawyer-org#198]

**Comment by j-dimension** [comment]
```
java.lang.IllegalThreadStateException: process hasn't exited
        at java.lang.UNIXProcess.exitValue(UNIXProcess.java:423)
        at org.jlawyer.backupmgr.impl.RestoreExecutor.restoreDatabase(RestoreExecutor.java:1219)
        at org.jlawyer.backupmgr.impl.RestoreExecutor.restore(RestoreExecutor.java:1032)
        at org.jlawyer.backupmgr.controller.BackupMgrController$1.run(BackupMgrController.java:123)
        at java.lang.Thread.run(Thread.java:748)

```

**Comment by j-dimension** [comment]
needs to be tested with large data set
