### ISSUE TITLE
[BUG] Backup Sync Fehler

### ISSUE THREAD

**Issue by hackvokat** [jlawyerorg/j-lawyer-org#2039]
Hallo,

seit gestern bekomme ich beim automatischen und manuellen Backup eine Fehlermeldung, sobald es an die Synchronisation mit dem externen Backup geht:
Synchronisation: FEHLGESCHLAGEN!

An keinem der Systeme hat sich etwas geändert. Helfen die Logs weiter? Ich werde nicht ganz schlau, wo es genau hakt. Wie könnte ich das Problem ausfindig machen?

In der server.log steht dazu:

```
2023-08-17 16:21:37,874 INFO  [com.jdimension.jlawyer.timer.IterativeBackupTask] (Timer-5) Export finished
2023-08-17 16:21:37,875 INFO  [com.jdimension.jlawyer.timer.IterativeBackupTask] (Timer-5) Starting sync to sftp://BENUTZER:***@SERVER/users/jlawyer
2023-08-17 16:21:59,297 ERROR [com.jdimension.jlawyer.timer.IterativeBackupTask] (Timer-5) failed to sync: Unknown message with code "Could not determine the type of file "sftp://BENUTZER:***@SERVER/users/jlawyer".".: org.apache.commons.vfs2.FileSystemException: Unknown message with code "Could not determine the type of file "sftp://BENUTZER:***@SERVER/users/jlawyer".".
        at org.apache.commons.vfs2.provider.sftp.SftpFileObject.refresh(SftpFileObject.java:94)
        at org.apache.commons.vfs2.provider.AbstractFileSystem.resolveFile(AbstractFileSystem.java:364)
        at org.apache.commons.vfs2.provider.AbstractFileSystem.resolveFile(AbstractFileSystem.java:317)
        at org.apache.commons.vfs2.provider.AbstractOriginatingFileProvider.findFile(AbstractOriginatingFileProvider.java:84)
        at org.apache.commons.vfs2.provider.AbstractOriginatingFileProvider.findFile(AbstractOriginatingFileProvider.java:64)
        at org.apache.commons.vfs2.impl.DefaultFileSystemManager.resolveFile(DefaultFileSystemManager.java:804)
        at org.apache.commons.vfs2.impl.DefaultFileSystemManager.resolveFile(DefaultFileSystemManager.java:726)
        at com.jdimension.jlawyer.storage.LocalSshFtpFile.<init>(LocalSshFtpFile.java:707)
        at com.jdimension.jlawyer.storage.VirtualFile.getFile(VirtualFile.java:679)
        at com.jdimension.jlawyer.timer.IterativeBackupTask.run(IterativeBackupTask.java:966)
        at java.util.TimerThread.mainLoop(Timer.java:555)
        at java.util.TimerThread.run(Timer.java:505)
Caused by: org.apache.commons.vfs2.FileSystemException: Could not determine the type of file "sftp://BENUTZER:***@SERVER/users/jlawyer".
        at org.apache.commons.vfs2.provider.AbstractFileObject.getType(AbstractFileObject.java:1526)
        at org.apache.commons.vfs2.provider.sftp.SftpFileObject.refresh(SftpFileObject.java:90)
        ... 11 more
Caused by: org.apache.commons.vfs2.FileSystemException: Could not connect to SFTP server at "sftp://BENUTZER:***@SERVER/".
        at org.apache.commons.vfs2.provider.sftp.SftpFileSystem.getChannel(SftpFileSystem.java:149)
        at org.apache.commons.vfs2.provider.sftp.SftpFileObject.statSelf(SftpFileObject.java:152)
        at org.apache.commons.vfs2.provider.sftp.SftpFileObject.doGetType(SftpFileObject.java:113)
        at org.apache.commons.vfs2.provider.AbstractFileObject.getType(AbstractFileObject.java:1517)
        ... 12 more
Caused by: com.jcraft.jsch.JSchException: channel is not opened.
        at com.jcraft.jsch.Channel.sendChannelOpen(Channel.java:765)
        at com.jcraft.jsch.Channel.connect(Channel.java:151)
        at com.jcraft.jsch.Channel.connect(Channel.java:145)
        at org.apache.commons.vfs2.provider.sftp.SftpFileSystem.getChannel(SftpFileSystem.java:113)
        ... 15 more

2023-08-17 16:21:59,297 INFO  [com.jdimension.jlawyer.timer.IterativeBackupTask] (Timer-5) Sync finished
```

**Comment by j-dimension** [comment]
Evtl. hat sich der Schlüssel des Zielservers geändert?
