### ISSUE TITLE
[BUG] Fehler beim Speichern einer Mail zur Akte: "null"

### ISSUE THREAD

**Issue by stm9x9** [jlawyerorg/j-lawyer-org#2079]
Ich bekomme seit jetzt bei jedem Speicherversuch einer Mail (mit oder ohne Anhänge) zur Akte diesen Fehler:

![image](https://github.com/jlawyerorg/j-lawyer-org/assets/29924198/f6a3fb78-ed14-412e-9756-049ce25a3fa2)

Nach einem Neustart des Clients ging es wieder. Aber das soll doch nicht vorkommen?

hier der Auszug aus client.log

`2023-09-15 18:33:32,647 ERROR [com.jdimension.jlawyer.client.mail.EmailUtils] Error determining mailbox for message 
javax.mail.MessageRemovedException: null
	at com.sun.mail.imap.IMAPMessage.checkExpunged(IMAPMessage.java:280) ~[javax.mail-1.6.2.jar:1.6.2]
	at com.sun.mail.imap.IMAPMessage.getFrom(IMAPMessage.java:322) ~[javax.mail-1.6.2.jar:1.6.2]
	at com.jdimension.jlawyer.client.mail.EmailUtils.getMailboxSetup(EmailUtils.java:798) [j-lawyer-client.jar:?]
	at com.jdimension.jlawyer.client.mail.EmailInboxPanel.messagesRemoved(EmailInboxPanel.java:2635) [j-lawyer-client.jar:?]
	at javax.mail.event.MessageCountEvent.dispatch(MessageCountEvent.java:156) [javax.mail-1.6.2.jar:1.6.2]
	at javax.mail.EventQueue.run(EventQueue.java:170) [javax.mail-1.6.2.jar:1.6.2]
	at java.lang.Thread.run(Thread.java:829) [?:?]
2023-09-15 18:33:32,647 WARN  [com.jdimension.jlawyer.client.mail.EmailInboxPanel] can not determine mailbox setup of removed message
2023-09-15 18:33:52,402 ERROR [com.jdimension.jlawyer.client.mail.EmailInboxPanel] java.lang.NullPointerException
2023-09-15 18:34:11,322 WARN  [com.jdimension.jlawyer.client.mail.EmailUtils] cannot determine message subject
javax.mail.FolderClosedException: null
	at com.sun.mail.imap.IMAPMessage.getProtocol(IMAPMessage.java:169) ~[javax.mail-1.6.2.jar:1.6.2]
	at com.sun.mail.imap.IMAPMessage.loadEnvelope(IMAPMessage.java:1488) ~[javax.mail-1.6.2.jar:1.6.2]
	at com.sun.mail.imap.IMAPMessage.getSubject(IMAPMessage.java:441) ~[javax.mail-1.6.2.jar:1.6.2]
	at com.jdimension.jlawyer.client.mail.EmailUtils.getMailboxSetup(EmailUtils.java:822) [j-lawyer-client.jar:?]
	at com.jdimension.jlawyer.client.mail.EmailInboxPanel.messageChanged(EmailInboxPanel.java:2564) [j-lawyer-client.jar:?]
	at javax.mail.event.MessageChangedEvent.dispatch(MessageChangedEvent.java:106) [javax.mail-1.6.2.jar:1.6.2]
	at javax.mail.EventQueue.run(EventQueue.java:170) [javax.mail-1.6.2.jar:1.6.2]
	at java.lang.Thread.run(Thread.java:829) [?:?]
2023-09-15 18:34:11,323 ERROR [com.jdimension.jlawyer.client.mail.EmailUtils] Error determining mailbox for message 
javax.mail.FolderClosedException: null
	at com.sun.mail.imap.IMAPMessage.getProtocol(IMAPMessage.java:169) ~[javax.mail-1.6.2.jar:1.6.2]
	at com.sun.mail.imap.IMAPMessage.loadEnvelope(IMAPMessage.java:1488) ~[javax.mail-1.6.2.jar:1.6.2]
	at com.sun.mail.imap.IMAPMessage.getFrom(IMAPMessage.java:325) ~[javax.mail-1.6.2.jar:1.6.2]
	at com.jdimension.jlawyer.client.mail.EmailUtils.getMailboxSetup(EmailUtils.java:798) [j-lawyer-client.jar:?]
	at com.jdimension.jlawyer.client.mail.EmailInboxPanel.messageChanged(EmailInboxPanel.java:2564) [j-lawyer-client.jar:?]
	at javax.mail.event.MessageChangedEvent.dispatch(MessageChangedEvent.java:106) [javax.mail-1.6.2.jar:1.6.2]
	at javax.mail.EventQueue.run(EventQueue.java:170) [javax.mail-1.6.2.jar:1.6.2]
	at java.lang.Thread.run(Thread.java:829) [?:?]
2023-09-15 18:34:27,299 ERROR [com.jdimension.jlawyer.client.mail.EmailInboxPanel] java.lang.NullPointerException
2023-09-15 18:34:46,728 ERROR [com.jdimension.jlawyer.client.mail.EmailInboxPanel] java.lang.NullPointerException
`

**Comment by j-dimension** [comment]
Geht das client.log noch weiter?

Wie kann man das nachvollziehen?

**Comment by j-dimension** [comment]
Und welche Version?

**Comment by stm9x9** [comment]
sehe gerade, die neue Version ist draußen :-)

War noch die 2.3.0.1

das client log ist da zu ende

reproduzieren wird schwierig, wie gesagt, nach einem Neustart ging es wieder. Ich hatte gehofft, daß log ist aufschlußreich genug. :-/ Einziger Anhaltspunkt: das Mailfenster war offen, dann ging der Rechner für zwei Stunden etwa in standby und dann kam der Fehler.

**Comment by j-dimension** [comment]
Tritt das noch auf? Wenn ja, dann bitte mehr Infos.

**Comment by Dickmaulruessler** [comment]
> Tritt das noch auf? Wenn ja, dann bitte mehr Infos.

Ich hatte das heute auch. Ursache war, dass ich beim Umbennen einer von Outlook stammenden E-Mail (wurde im .msg-Format gespeichert) die Dateiendung versehentlich gelöscht hatte und beim späteren Korrigieren dann von JL immer wieder "Dateiname**.msg.eml**" - also **zwei** Dateiendungen - auftraten (.eml scheint wohl standard zu sein). 

Mein Fazit wäre: 
Dateiformat .msg nicht löschen und dann funzt es super!
@stm9x9 

Falls es für das versehentliche Löschen von .msg Dateiendungen noch Vorsorge getroffen werden könnte (wie bei anderen Dateien), wäre das evtl. noch etwas, was getan werden könnte.
Siehe zu dem Thema "Dateiendungen" (dort betreffend beA) auch #1733

**Comment by stm9x9** [comment]
ich habe das nicht mehr erlebt. Aber das mit Outlook ist es bei mir nicht. Nutze ich nicht.
