### ISSUE TITLE
[TASK] Java 17 Upgrade Server + Client, Upgrade auf Wildfly 26

### ISSUE THREAD

**Issue by j-dimension** [jlawyerorg/j-lawyer-org#2099]
Benötigt für KSW Toolkit
BRAK empfiehlt Liberica Full JDK 17.0.7+7 x86 64

offene Punkte Wildfly 26:
- [x] Installer Server: Windows Install
- [x] Installer Server: Windows Update
- [x] Installer Server: Linux Install
- [x] Installer Server: Linux Update
- [x] Installer Server: Mac Install
- [x] Installer Server: Mac Update
- [x] Installer Server: j-lawyer.BOX
- [x] Installer Server: j-lawyer.BOX muss Managementkonsole updaten, wenn nicht lauffähig auf neuem Wildfly
- [x] Installer Server (Windows): prüfen, ob mitgeliefertes JRE verwendet wird
- [x] Installer Server (Linux): prüfen, ob mitgeliefertes JRE verwendet wird - FEHLER! nutzt noch System-JDK
- [x] Installer Server (Mac): prüfen, ob mitgeliefertes JRE verwendet wird
- [x] Installer Client: Windows Install
- [x] Installer Client: Windows Update
- [x] Installer Client: Linux Install
- [x] Installer Client: Linux Update
- [x] Installer Client: Mac Install
- [x] Installer Client: Mac Update
- [x] Installer Client: Mac Crash unter High Sierra (ab Monterey sollte es keine Probleme geben)
- [ ] Verschlüsselung DB-Passwort
- [x] Test Credentials-Caching und Methode flushUserCache - erledigt, flush scheint nicht mehr notwendig zu sein
- [x] Konfiguration Hashing für DB-Security
- [x] MDBs prüfen (SearchIndexProcessor)
- [x] nicht mehr unterstützt: security-domain in jboss-app.xml (j-lawyer-server, j-lawyer-io, j-lawyer-server-io)
- [x] securitydomain-annotation überall anwenden
- [x] Docker
- [x] Detailkonfigrationen Datenbank (retry, ...)
- [x] RESTEasy-Fehler debuggen - Erkenntnis: wenn nach Wildfly-Startup erst der remote EJB client den REST client triggert, dann Fehler. Wenn der TimerTask via AutostartServlet zuerst den REST client triggert, gibt es keine Probleme.

**Comment by j-dimension** [comment]
DB-Passwort verschlüsseln:

<subsystem xmlns="urn:wildfly:elytron:14.0" final-providers="combined-providers" disallowed-providers="OracleUcrypto">
    ...
    <credential-stores>
        <credential-store name="myCredentialStore" relative-to="jboss.server.data.dir" path="credential-store.jceks"/>
    </credential-stores>
    ...
</subsystem>

CLI:
/subsystem=elytron/credential-store=myCredentialStore:add-alias(alias=dbPassword, secret-value="yourEncryptedPassword")



        <datasource jta="true" jndi-name="java:/jboss/datasources/YourDS" pool-name="YourDS" enabled="true" use-ccm="true">
            ...
            <security>
                <user-name>yourUsername</user-name>
                <credential-reference clear-text="false" store="myCredentialStore" alias="dbPassword"/>
            </security>
            ...
        </datasource>

**Comment by j-dimension** [comment]
```
Caused by: java.lang.NullPointerException: Cannot invoke "java.lang.reflect.Constructor.getParameterTypes()" because "constructor" is null
	at org.jboss.resteasy.resteasy-core@4.7.7.Final//org.jboss.resteasy.core.ConstructorInjectorImpl.<init>(ConstructorInjectorImpl.java:55)
	at org.jboss.resteasy.resteasy-core@4.7.7.Final//org.jboss.resteasy.core.InjectorFactoryImpl.createConstructor(InjectorFactoryImpl.java:61)
	at org.jboss.resteasy.resteasy-core@4.7.7.Final//org.jboss.resteasy.core.providerfactory.ResteasyProviderFactoryImpl.injectedInstance(ResteasyProviderFactoryImpl.java:1398)
	at org.jboss.resteasy.resteasy-core@4.7.7.Final//org.jboss.resteasy.core.interception.jaxrs.JaxrsInterceptorRegistryImpl$AbstractInterceptorFactory.createInterceptor(JaxrsInterceptorRegistryImpl.java:150)
	at org.jboss.resteasy.resteasy-core@4.7.7.Final//org.jboss.resteasy.core.interception.jaxrs.JaxrsInterceptorRegistryImpl$OnDemandInterceptorFactory.initialize(JaxrsInterceptorRegistryImpl.java:168)
	at org.jboss.resteasy.resteasy-core@4.7.7.Final//org.jboss.resteasy.core.interception.jaxrs.JaxrsInterceptorRegistryImpl$OnDemandInterceptorFactory.checkInitialize(JaxrsInterceptorRegistryImpl.java:183)
	at org.jboss.resteasy.resteasy-core@4.7.7.Final//org.jboss.resteasy.core.interception.jaxrs.JaxrsInterceptorRegistryImpl$OnDemandInterceptorFactory.getInterceptor(JaxrsInterceptorRegistryImpl.java:193)
	at org.jboss.resteasy.resteasy-core@4.7.7.Final//org.jboss.resteasy.core.interception.jaxrs.JaxrsInterceptorRegistryImpl$AbstractInterceptorFactory.postMatch(JaxrsInterceptorRegistryImpl.java:138)
	at org.jboss.resteasy.resteasy-core@4.7.7.Final//org.jboss.resteasy.core.interception.jaxrs.JaxrsInterceptorRegistryImpl.postMatch(JaxrsInterceptorRegistryImpl.java:288)
	at org.jboss.resteasy.resteasy-client@4.7.7.Final//org.jboss.resteasy.client.jaxrs.internal.ClientConfiguration.getRequestFilters(ClientConfiguration.java:120)
	at org.jboss.resteasy.resteasy-client@4.7.7.Final//org.jboss.resteasy.client.jaxrs.internal.ClientInvocation.getRequestFilters(ClientInvocation.java:460)
	at org.jboss.resteasy.resteasy-client@4.7.7.Final//org.jboss.resteasy.client.jaxrs.internal.ClientInvocation.filterRequest(ClientInvocation.java:759)
	at org.jboss.resteasy.resteasy-client@4.7.7.Final//org.jboss.resteasy.client.jaxrs.internal.ClientInvocation.invoke(ClientInvocation.java:491)
	at org.jboss.resteasy.resteasy-client@4.7.7.Final//org.jboss.resteasy.client.jaxrs.internal.ClientInvocation.invoke(ClientInvocation.java:69)
	at org.jboss.resteasy.resteasy-client@4.7.7.Final//org.jboss.resteasy.client.jaxrs.internal.ClientInvocationBuilder.post(ClientInvocationBuilder.java:226)
	at deployment.j-lawyer-server.ear//com.jdimension.jlawyer.epost.EpostAPI.login(EpostAPI.java:782)
```

**Comment by j-dimension** [comment]
Resteasy durch Jersey ersetzt
