### ISSUE TITLE
[BUG] E-Mail speichern: Failed to read response

### ISSUE THREAD

**Issue by Maz111111** [jlawyerorg/j-lawyer-org#2222]
"Fehler beim Senden: Fehler beim Speichern: Failed to read response"
Es kommt zu obiger Fehlermeldung, wenn der Name einer Mail, der von jL für die Dokumentenbenennung erstellt wird,  zu lang wird.
Das Sendefenster bleibt dann offen un ddie gesendete Nachricht wird nicht zu dne Dokumenten genommen.

Für den Anwender ist insofern nicht bzw. nicht  zweifelsfrei ersichtlich, ob die Mail versendet wurde oder nicht.

Systemreport wirft folgendes aus:
"Caused by: com.mysql.cj.jdbc.exceptions.MysqlDataTruncation: Data truncation: Data too long for column 'name' at row 1"

jL sollte zum einen eine nachvollziehbare Fehlermeldung augeben und ggf. eigenständig eine Anpassung des Namens vorschlagen.
Die Prüfung sollte vor Einleitung des Versands erfolgen und in der Fehlermeldung sollte der klare Hinweis erfolgen, dass die Mail bis dahin noch nicht versendet wurde, damit keine Unsicherheiten beim Anwender entstehen.

**Comment by j-dimension** [comment]
Ich habe mir das angeschaut, es gibt bereits eine Längenprüfung - der vorgeschlagene Name sollte niemals länger sein als das Feld in der Datenbank. Wurde der vorgeschlagene Name danach manuell angepasst / erweitert?

**Comment by j-dimension** [comment]
Und bitte noch das Snippet im Systemreport großzügig hier aufnehmen, nicht nur die eine Zeile - ich kann so nicht die konkrete Codezeile herauslesen.

**Comment by Maz111111** [comment]
> Ich habe mir das angeschaut, es gibt bereits eine Längenprüfung - der vorgeschlagene Name sollte niemals länger sein als das Feld in der Datenbank. Wurde der vorgeschlagene Name danach manuell angepasst / erweitert?

Nein. Ich habe es insgesamt dreimal (an unterschiedlichen Tagen- jeweils zweimal pro Tag, das letzte Mal dann aber tatsächlich verändert) unverändert gesendet. Nachfrage ergab, dass die Mail insges. auch viermal bei Empfänger angekommen ist.


> Und bitte noch das Snippet im Systemreport großzügig hier aufnehmen, nicht nur die eine Zeile - ich kann so nicht die konkrete Codezeile herauslesen.

Ich schicke dir den gesamten Report.

**Comment by j-dimension** [comment]
Client 2.5:

```
javax.ejb.EJBException: Failed to read response
	at org.jboss.ejb.protocol.remote.EJBClientChannel$MethodInvocation$ExceptionResultProducer.getResult(EJBClientChannel.java:1293) ~[jboss-client.jar:16.0.0.Final]
	at org.jboss.ejb.client.EJBClientInvocationContext.getResult(EJBClientInvocationContext.java:592) ~[jboss-client.jar:16.0.0.Final]
	at org.jboss.ejb.client.EJBClientInvocationContext.getResult(EJBClientInvocationContext.java:528) ~[jboss-client.jar:16.0.0.Final]
	at org.jboss.ejb.protocol.remote.RemotingEJBClientInterceptor.handleInvocationResult(RemotingEJBClientInterceptor.java:56) ~[jboss-client.jar:16.0.0.Final]
	at org.jboss.ejb.client.EJBClientInvocationContext.getResult(EJBClientInvocationContext.java:594) ~[jboss-client.jar:16.0.0.Final]
	at org.jboss.ejb.client.EJBClientInvocationContext.getResult(EJBClientInvocationContext.java:528) ~[jboss-client.jar:16.0.0.Final]
	at org.jboss.ejb.client.TransactionPostDiscoveryInterceptor.handleInvocationResult(TransactionPostDiscoveryInterceptor.java:133) ~[jboss-client.jar:16.0.0.Final]
	at org.jboss.ejb.client.EJBClientInvocationContext.getResult(EJBClientInvocationContext.java:594) ~[jboss-client.jar:16.0.0.Final]
	at org.jboss.ejb.client.EJBClientInvocationContext.getResult(EJBClientInvocationContext.java:528) ~[jboss-client.jar:16.0.0.Final]
	at org.jboss.ejb.client.DiscoveryEJBClientInterceptor.handleInvocationResult(DiscoveryEJBClientInterceptor.java:115) ~[jboss-client.jar:16.0.0.Final]
	at org.jboss.ejb.client.EJBClientInvocationContext.getResult(EJBClientInvocationContext.java:594) ~[jboss-client.jar:16.0.0.Final]
	at org.jboss.ejb.client.EJBClientInvocationContext.getResult(EJBClientInvocationContext.java:528) ~[jboss-client.jar:16.0.0.Final]
	at org.jboss.ejb.client.NamingEJBClientInterceptor.handleInvocationResult(NamingEJBClientInterceptor.java:79) ~[jboss-client.jar:16.0.0.Final]
	at org.jboss.ejb.client.EJBClientInvocationContext.getResult(EJBClientInvocationContext.java:594) ~[jboss-client.jar:16.0.0.Final]
	at org.jboss.ejb.client.EJBClientInvocationContext.getResult(EJBClientInvocationContext.java:528) ~[jboss-client.jar:16.0.0.Final]
	at org.jboss.ejb.client.TransactionInterceptor.handleInvocationResult(TransactionInterceptor.java:172) ~[jboss-client.jar:16.0.0.Final]
	at org.jboss.ejb.client.EJBClientInvocationContext.getResult(EJBClientInvocationContext.java:594) ~[jboss-client.jar:16.0.0.Final]
	at org.jboss.ejb.client.EJBClientInvocationContext.getResult(EJBClientInvocationContext.java:528) ~[jboss-client.jar:16.0.0.Final]
	at org.jboss.ejb.client.EJBClientInvocationContext.awaitResponse(EJBClientInvocationContext.java:938) ~[jboss-client.jar:16.0.0.Final]
	at org.jboss.ejb.client.EJBInvocationHandler.invoke(EJBInvocationHandler.java:177) ~[jboss-client.jar:16.0.0.Final]
	at org.jboss.ejb.client.EJBInvocationHandler.invoke(EJBInvocationHandler.java:112) ~[jboss-client.jar:16.0.0.Final]
	at com.sun.proxy.$Proxy24.addDocument(Unknown Source) ~[?:?]
	at com.jdimension.jlawyer.client.mail.SendAction.execute(SendAction.java:915) ~[j-lawyer-client.jar:?]
	at com.jdimension.jlawyer.client.processing.ProgressableAction.lambda$start$6(ProgressableAction.java:767) ~[j-lawyer-client.jar:?]
	at java.lang.Thread.run(Thread.java:829) ~[?:?]
```

**Comment by j-dimension** [comment]
Server: 

`2023-12-03 17:42:14,957 ERROR [org.jboss.as.ejb3.invocation] (default task-6873) WFLYEJB0034: EJB Invocation failed on component ArchiveFileService for method public abstract com.jdimension.jlawyer.persistence.ArchiveFileDocumentsBean com.jdimension.jlawyer.services.ArchiveFileServiceRemote.addDocument(java.lang.String,java.lang.String,byte[],java.lang.String) throws java.lang.Exception: javax.ejb.EJBTransactionRolledbackException: javax.transaction.RollbackException: ARJUNA016053: Could not commit transaction.`

**Comment by j-dimension** [comment]
@Maz111111 kannst Du das bitte nochmal mit exakt den selben Dateien (Versand an Dich) ausführen und mir den vom System vorgeschlagenenen Dateinamen senden?
