### ISSUE TITLE
[BUG] pdf-Umwandlung ergibt Fehler

### ISSUE THREAD

**Issue by stm9x9** [jlawyerorg/j-lawyer-org#2224]
Ich habe hier drei odt-Dateien (alle aus derselben Vorlage), die ich nicht mehr in pdf umwandeln kann (ablegen als pdf oder lokal speichern als pdf).

Auf der UI gibt es den Konvertierungsfehler 1:

![image](https://github.com/jlawyerorg/j-lawyer-org/assets/29924198/1e4a97cc-c635-48cd-875d-19e1372fa22f)

das log liefert:

`2023-12-07 19:22:01,380 WARN  [com.jdimension.jlawyer.client.utils.FileConverter] PDF conversion failed with exit code 1 - retrying... (C:\Users\xxx\AppData\Local\Temp\4583c8d8c0a801c24bcb2a81a16bcb60\2023-12-07_Widerrufsbelehrung xxx.odt)
2023-12-07 19:22:10,075 ERROR [com.jdimension.jlawyer.client.utils.FileConverter] PDF conversion failed with exit code 1, command line was 'python.exe C:\Program Files\j-lawyer-client\unoconv-master\unoconv -f pdf C:\Users\xxx\AppData\Local\Temp\4583c8d8c0a801c24bcb2a81a16bcb60\2023-12-07_Widerrufsbelehrung xxx.odt
2023-12-07 19:22:10,075 ERROR [com.jdimension.jlawyer.client.editors.files.ArchiveFilePanel] Could not convert document to PDF
java.lang.Exception: Konvertierung nach PDF fehlgeschlagen: 1
	at com.jdimension.jlawyer.client.utils.FileConverter$WindowsFileConverter.convertToPDFLO(FileConverter.java:872) ~[j-lawyer-client.jar:?]
	at com.jdimension.jlawyer.client.utils.FileConverter$WindowsFileConverter.convertToPDF(FileConverter.java:803) ~[j-lawyer-client.jar:?]
	at com.jdimension.jlawyer.client.editors.files.ArchiveFilePanel.lambda$convertDocumentToPdf$9(ArchiveFilePanel.java:4960) ~[j-lawyer-client.jar:?]
	at com.jdimension.jlawyer.client.editors.files.ArchiveFilePanel.waitForOpenDocument(ArchiveFilePanel.java:1397) ~[j-lawyer-client.jar:?]
	at com.jdimension.jlawyer.client.editors.files.ArchiveFilePanel.convertDocumentToPdf(ArchiveFilePanel.java:5014) ~[j-lawyer-client.jar:?]
	at com.jdimension.jlawyer.client.editors.files.ArchiveFilePanel.mnuDuplicateDocumentAsPdfActionPerformed(ArchiveFilePanel.java:5031) ~[j-lawyer-client.jar:?]
	at com.jdimension.jlawyer.client.editors.files.ArchiveFilePanel$14.actionPerformed(ArchiveFilePanel.java:1961) ~[j-lawyer-client.jar:?]
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1967) ~[?:?]
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2308) ~[?:?]
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405) ~[?:?]
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262) ~[?:?]
	at javax.swing.AbstractButton.doClick(AbstractButton.java:369) ~[?:?]
	at javax.swing.plaf.basic.BasicMenuItemUI.doClick(BasicMenuItemUI.java:1020) ~[?:?]
	at javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(BasicMenuItemUI.java:1064) ~[?:?]
	at java.awt.Component.processMouseEvent(Component.java:6635) ~[?:?]
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3342) ~[?:?]
	at java.awt.Component.processEvent(Component.java:6400) ~[?:?]
	at java.awt.Container.processEvent(Container.java:2263) ~[?:?]
	at java.awt.Component.dispatchEventImpl(Component.java:5011) ~[?:?]
	at java.awt.Container.dispatchEventImpl(Container.java:2321) ~[?:?]
	at java.awt.Component.dispatchEvent(Component.java:4843) ~[?:?]
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4918) ~[?:?]
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4547) ~[?:?]
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4488) ~[?:?]
	at java.awt.Container.dispatchEventImpl(Container.java:2307) ~[?:?]
	at java.awt.Window.dispatchEventImpl(Window.java:2772) ~[?:?]
	at java.awt.Component.dispatchEvent(Component.java:4843) ~[?:?]
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:772) ~[?:?]
	at java.awt.EventQueue$4.run(EventQueue.java:721) ~[?:?]
	at java.awt.EventQueue$4.run(EventQueue.java:715) ~[?:?]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:?]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85) ~[?:?]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95) ~[?:?]
	at java.awt.EventQueue$5.run(EventQueue.java:745) ~[?:?]
	at java.awt.EventQueue$5.run(EventQueue.java:743) ~[?:?]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:?]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85) ~[?:?]
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:742) ~[?:?]
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203) ~[?:?]
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124) ~[?:?]
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113) ~[?:?]
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109) ~[?:?]
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101) ~[?:?]
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:90) ~[?:?]
2023-12-07 19:22:24,981 WARN  [com.jdimension.jlawyer.client.utils.FileConverter] PDF conversion failed with exit code 1 - retrying... (C:\Users\xxx\AppData\Local\Temp\458424fcc0a801c25d32c218e331b52a\2023-12-07_Widerrufsbelehrung xxx.odt)
2023-12-07 19:22:33,760 ERROR [com.jdimension.jlawyer.client.utils.FileConverter] PDF conversion failed with exit code 1, command line was 'python.exe C:\Program Files\j-lawyer-client\unoconv-master\unoconv -f pdf C:\Users\xxx\AppData\Local\Temp\458424fcc0a801c25d32c218e331b52a\2023-12-07_Widerrufsbelehrung xxx.odt
2023-12-07 19:22:33,760 ERROR [com.jdimension.jlawyer.client.editors.documents.SaveDocumentsLocallyDialog] error saving documents
java.lang.Exception: Konvertierung nach PDF fehlgeschlagen: 1
	at com.jdimension.jlawyer.client.utils.FileConverter$WindowsFileConverter.convertToPDFLO(FileConverter.java:872) ~[j-lawyer-client.jar:?]
	at com.jdimension.jlawyer.client.utils.FileConverter$WindowsFileConverter.convertToPDF(FileConverter.java:803) ~[j-lawyer-client.jar:?]
	at com.jdimension.jlawyer.client.editors.documents.SaveDocumentsLocallyDialog.cmdSaveActionPerformed(SaveDocumentsLocallyDialog.java:875) ~[j-lawyer-client.jar:?]
	at com.jdimension.jlawyer.client.editors.documents.SaveDocumentsLocallyDialog$4.actionPerformed(SaveDocumentsLocallyDialog.java:769) ~[j-lawyer-client.jar:?]
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1967) ~[?:?]
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2308) ~[?:?]
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405) ~[?:?]
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262) ~[?:?]
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:279) ~[?:?]
	at java.awt.Component.processMouseEvent(Component.java:6635) ~[?:?]
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3342) ~[?:?]
	at java.awt.Component.processEvent(Component.java:6400) ~[?:?]
	at java.awt.Container.processEvent(Container.java:2263) ~[?:?]
	at java.awt.Component.dispatchEventImpl(Component.java:5011) ~[?:?]
	at java.awt.Container.dispatchEventImpl(Container.java:2321) ~[?:?]
	at java.awt.Component.dispatchEvent(Component.java:4843) ~[?:?]
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4918) ~[?:?]
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4547) ~[?:?]
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4488) ~[?:?]
	at java.awt.Container.dispatchEventImpl(Container.java:2307) ~[?:?]
	at java.awt.Window.dispatchEventImpl(Window.java:2772) ~[?:?]
	at java.awt.Component.dispatchEvent(Component.java:4843) ~[?:?]
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:772) ~[?:?]
	at java.awt.EventQueue$4.run(EventQueue.java:721) ~[?:?]
	at java.awt.EventQueue$4.run(EventQueue.java:715) ~[?:?]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:?]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85) ~[?:?]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95) ~[?:?]
	at java.awt.EventQueue$5.run(EventQueue.java:745) ~[?:?]
	at java.awt.EventQueue$5.run(EventQueue.java:743) ~[?:?]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:?]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85) ~[?:?]
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:742) ~[?:?]
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203) ~[?:?]
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124) ~[?:?]
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:117) ~[?:?]
	at java.awt.WaitDispatchSupport$2.run(WaitDispatchSupport.java:190) ~[?:?]
	at java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:235) ~[?:?]
	at java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:233) ~[?:?]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:?]
	at java.awt.WaitDispatchSupport.enter(WaitDispatchSupport.java:233) ~[?:?]
	at java.awt.Dialog.show(Dialog.java:1070) ~[?:?]
	at java.awt.Component.show(Component.java:1716) ~[?:?]
	at java.awt.Component.setVisible(Component.java:1663) ~[?:?]
	at java.awt.Window.setVisible(Window.java:1031) ~[?:?]
	at java.awt.Dialog.setVisible(Dialog.java:1005) ~[?:?]
	at com.jdimension.jlawyer.client.editors.files.ArchiveFilePanel.saveDocumentsLocally(ArchiveFilePanel.java:5784) ~[j-lawyer-client.jar:?]
	at com.jdimension.jlawyer.client.editors.files.ArchiveFilePanel.mnuSaveDocumentsLocallyPdfActionPerformed(ArchiveFilePanel.java:5793) ~[j-lawyer-client.jar:?]
	at com.jdimension.jlawyer.client.editors.files.ArchiveFilePanel$12.actionPerformed(ArchiveFilePanel.java:1943) ~[j-lawyer-client.jar:?]
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1967) ~[?:?]
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2308) ~[?:?]
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405) ~[?:?]
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262) ~[?:?]
	at javax.swing.AbstractButton.doClick(AbstractButton.java:369) ~[?:?]
	at javax.swing.plaf.basic.BasicMenuItemUI.doClick(BasicMenuItemUI.java:1020) ~[?:?]
	at javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(BasicMenuItemUI.java:1064) ~[?:?]
	at java.awt.Component.processMouseEvent(Component.java:6635) ~[?:?]
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3342) ~[?:?]
	at java.awt.Component.processEvent(Component.java:6400) ~[?:?]
	at java.awt.Container.processEvent(Container.java:2263) ~[?:?]
	at java.awt.Component.dispatchEventImpl(Component.java:5011) ~[?:?]
	at java.awt.Container.dispatchEventImpl(Container.java:2321) ~[?:?]
	at java.awt.Component.dispatchEvent(Component.java:4843) ~[?:?]
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4918) ~[?:?]
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4547) ~[?:?]
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4488) ~[?:?]
	at java.awt.Container.dispatchEventImpl(Container.java:2307) ~[?:?]
	at java.awt.Window.dispatchEventImpl(Window.java:2772) ~[?:?]
	at java.awt.Component.dispatchEvent(Component.java:4843) ~[?:?]
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:772) ~[?:?]
	at java.awt.EventQueue$4.run(EventQueue.java:721) ~[?:?]
	at java.awt.EventQueue$4.run(EventQueue.java:715) ~[?:?]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:?]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85) ~[?:?]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95) ~[?:?]
	at java.awt.EventQueue$5.run(EventQueue.java:745) ~[?:?]
	at java.awt.EventQueue$5.run(EventQueue.java:743) ~[?:?]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:?]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85) ~[?:?]
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:742) ~[?:?]
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203) ~[?:?]
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124) ~[?:?]
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113) ~[?:?]
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109) ~[?:?]
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101) ~[?:?]
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:90) ~[?:?]
`

Beim nächsten Start von Libreoffice wird von einem Absturz berichtet:

![image](https://github.com/jlawyerorg/j-lawyer-org/assets/29924198/5410cadb-64a9-4cbf-a591-4b880f2ac0c2)

Dateien aus dieser Vorlage haben bisher keine Probleme gemacht. Jetzt kann ich aber auch vorher konvertierbare Dateien nicht mehr umwandeln. Dateien aus anderen Vorlagen gehen weiterhin.

Mein System:

Version: 7.6.2.1 (x86) / LibreOffice Community
Build ID: 56f7684011345957bbf33a7ee678afaf4d2ba333
CPU threads: 16; OS: Windows 10.0 Build 19045; UI render: Skia/Raster; VCL: win
Locale: de-DE (de_DE); UI: de-DE
Calc: threaded

**Comment by j-dimension** [comment]
Lässt sich denn ein so erstelltes Dokument in LO öffnen? Und dort als PDF speichern?

**Comment by j-dimension** [comment]
Und was passiert wenn man in einer Eingabeaufforderung im Verzeichnis des Clients

unoconv "C:\bla\irgendwas.odt" 

für diese Datei eingibt? (Pfad ersetzen)

**Comment by stm9x9** [comment]
es scheint an der LO-Version oder -Installation gelegen zu haben. Ich habe geupdatet:

Version: 7.6.4.1 (x86) / LibreOffice Community
Build ID: e19e193f88cd6c0525a17fb7a176ed8e6a3e2aa1
CPU threads: 16; OS: Windows 10.0 Build 19045; UI render: Skia/Raster; VCL: win
Locale: de-DE (de_DE); UI: de-DE
Calc: threaded

und jetzt geht es.
