### ISSUE TITLE
[BUG] Fehler beim Speichern einer Mail

### ISSUE THREAD

**Issue by stm9x9** [jlawyerorg/j-lawyer-org#2243]
Ich habe eine Mail in jl verfaßt und auch abgeschickt. Beim Speichern zur Akte kommt folgender Fehler und nach Wegklicken bleibt das Nachrichtenfenster offen. Ich habe nochmals versendet und wieder der Fehler. wie ich nachher feststellen konnte, waren beide Mails im gesendet-Ordner meines Mailaccounts.

Fehler beim Speichern: Failed to read response

hier das Logfile:

```
2023-12-20 22:40:56,158 ERROR [com.jdimension.jlawyer.client.mail.SendAction] Could not save message to archive file
javax.ejb.EJBException: Failed to read response
	at org.jboss.ejb.protocol.remote.EJBClientChannel$MethodInvocation$ExceptionResultProducer.getResult(EJBClientChannel.java:1293) ~[jboss-client.jar:16.0.0.Final]
	at org.jboss.ejb.client.EJBClientInvocationContext.getResult(EJBClientInvocationContext.java:592) ~[jboss-client.jar:16.0.0.Final]
	at org.jboss.ejb.client.EJBClientInvocationContext.getResult(EJBClientInvocationContext.java:528) ~[jboss-client.jar:16.0.0.Final]
	at org.jboss.ejb.protocol.remote.RemotingEJBClientInterceptor.handleInvocationResult(RemotingEJBClientInterceptor.java:56) ~[jboss-client.jar:16.0.0.Final]
	at org.jboss.ejb.client.EJBClientInvocationContext.getResult(EJBClientInvocationContext.java:594) ~[jboss-client.jar:16.0.0.Final]
	at org.jboss.ejb.client.EJBClientInvocationContext.getResult(EJBClientInvocationContext.java:528) ~[jboss-client.jar:16.0.0.Final]
	at org.jboss.ejb.client.TransactionPostDiscoveryInterceptor.handleInvocationResult(TransactionPostDiscoveryInterceptor.java:133) ~[jboss-client.jar:16.0.0.Final]
	at org.jboss.ejb.client.EJBClientInvocationContext.getResult(EJBClientInvocationContext.java:594) ~[jboss-client.jar:16.0.0.Final]
	at org.jboss.ejb.client.EJBClientInvocationContext.getResult(EJBClientInvocationContext.java:528) ~[jboss-client.jar:16.0.0.Final]
	at org.jboss.ejb.client.DiscoveryEJBClientInterceptor.handleInvocationResult(DiscoveryEJBClientInterceptor.java:115) ~[jboss-client.jar:16.0.0.Final]
	at org.jboss.ejb.client.EJBClientInvocationContext.getResult(EJBClientInvocationContext.java:594) ~[jboss-client.jar:16.0.0.Final]
	at org.jboss.ejb.client.EJBClientInvocationContext.getResult(EJBClientInvocationContext.java:528) ~[jboss-client.jar:16.0.0.Final]
	at org.jboss.ejb.client.NamingEJBClientInterceptor.handleInvocationResult(NamingEJBClientInterceptor.java:79) ~[jboss-client.jar:16.0.0.Final]
	at org.jboss.ejb.client.EJBClientInvocationContext.getResult(EJBClientInvocationContext.java:594) ~[jboss-client.jar:16.0.0.Final]
	at org.jboss.ejb.client.EJBClientInvocationContext.getResult(EJBClientInvocationContext.java:528) ~[jboss-client.jar:16.0.0.Final]
	at org.jboss.ejb.client.TransactionInterceptor.handleInvocationResult(TransactionInterceptor.java:172) ~[jboss-client.jar:16.0.0.Final]
	at org.jboss.ejb.client.EJBClientInvocationContext.getResult(EJBClientInvocationContext.java:594) ~[jboss-client.jar:16.0.0.Final]
	at org.jboss.ejb.client.EJBClientInvocationContext.getResult(EJBClientInvocationContext.java:528) ~[jboss-client.jar:16.0.0.Final]
	at org.jboss.ejb.client.EJBClientInvocationContext.awaitResponse(EJBClientInvocationContext.java:938) ~[jboss-client.jar:16.0.0.Final]
	at org.jboss.ejb.client.EJBInvocationHandler.invoke(EJBInvocationHandler.java:177) ~[jboss-client.jar:16.0.0.Final]
	at org.jboss.ejb.client.EJBInvocationHandler.invoke(EJBInvocationHandler.java:112) ~[jboss-client.jar:16.0.0.Final]
	at com.sun.proxy.$Proxy24.addDocument(Unknown Source) ~[?:?]
	at com.jdimension.jlawyer.client.mail.SendAction.execute(SendAction.java:915) ~[j-lawyer-client.jar:?]
	at com.jdimension.jlawyer.client.processing.ProgressableAction.lambda$start$6(ProgressableAction.java:767) ~[j-lawyer-client.jar:?]
	at java.lang.Thread.run(Thread.java:829) ~[?:?]
Caused by: java.lang.ClassNotFoundException: com.mysql.cj.jdbc.exceptions.MysqlDataTruncation
	at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581) ~[?:?]
	at jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:522) ~[?:?]
	at java.lang.Class.forName0(Native Method) ~[?:?]
	at java.lang.Class.forName(Class.java:398) ~[?:?]
	at org.jboss.marshalling.AbstractClassResolver.loadClass(AbstractClassResolver.java:123) ~[jboss-client.jar:16.0.0.Final]
	at org.jboss.marshalling.AbstractClassResolver.resolveClass(AbstractClassResolver.java:104) ~[jboss-client.jar:16.0.0.Final]
	at org.jboss.marshalling.river.RiverUnmarshaller.doReadClassDescriptor(RiverUnmarshaller.java:1022) ~[jboss-client.jar:16.0.0.Final]
	at org.jboss.marshalling.river.RiverUnmarshaller.doReadNewObject(RiverUnmarshaller.java:1355) ~[jboss-client.jar:16.0.0.Final]
	at org.jboss.marshalling.river.RiverUnmarshaller.doReadObject(RiverUnmarshaller.java:272) ~[jboss-client.jar:16.0.0.Final]
	at org.jboss.marshalling.river.RiverUnmarshaller.doReadObject(RiverUnmarshaller.java:220) ~[jboss-client.jar:16.0.0.Final]
	at org.jboss.marshalling.river.RiverUnmarshaller.readFields(RiverUnmarshaller.java:1853) ~[jboss-client.jar:16.0.0.Final]
	at org.jboss.marshalling.river.RiverObjectInputStream.defaultReadObject(RiverObjectInputStream.java:81) ~[jboss-client.jar:16.0.0.Final]
	at java.lang.Throwable.readObject(Throwable.java:896) ~[?:?]
	at org.jboss.marshalling.reflect.JDKSpecific$SerMethods.callReadObject(JDKSpecific.java:100) ~[jboss-client.jar:16.0.0.Final]
	at org.jboss.marshalling.reflect.SerializableClass.callReadObject(SerializableClass.java:212) ~[jboss-client.jar:16.0.0.Final]
	at org.jboss.marshalling.river.RiverUnmarshaller.doInitSerializable(RiverUnmarshaller.java:1746) ~[jboss-client.jar:16.0.0.Final]
	at org.jboss.marshalling.river.RiverUnmarshaller.doInitSerializable(RiverUnmarshaller.java:1715) ~[jboss-client.jar:16.0.0.Final]
	at org.jboss.marshalling.river.RiverUnmarshaller.doInitSerializable(RiverUnmarshaller.java:1715) ~[jboss-client.jar:16.0.0.Final]
	at org.jboss.marshalling.river.RiverUnmarshaller.doInitSerializable(RiverUnmarshaller.java:1715) ~[jboss-client.jar:16.0.0.Final]
	at org.jboss.marshalling.river.RiverUnmarshaller.doInitSerializable(RiverUnmarshaller.java:1715) ~[jboss-client.jar:16.0.0.Final]
	at org.jboss.marshalling.river.RiverUnmarshaller.doInitSerializable(RiverUnmarshaller.java:1715) ~[jboss-client.jar:16.0.0.Final]
	at org.jboss.marshalling.river.RiverUnmarshaller.doInitSerializable(RiverUnmarshaller.java:1715) ~[jboss-client.jar:16.0.0.Final]
	at org.jboss.marshalling.river.RiverUnmarshaller.doReadNewObject(RiverUnmarshaller.java:1395) ~[jboss-client.jar:16.0.0.Final]
	at org.jboss.marshalling.river.RiverUnmarshaller.doReadObject(RiverUnmarshaller.java:272) ~[jboss-client.jar:16.0.0.Final]
	at org.jboss.marshalling.river.RiverUnmarshaller.doReadObject(RiverUnmarshaller.java:220) ~[jboss-client.jar:16.0.0.Final]
	at org.jboss.marshalling.river.RiverUnmarshaller.readFields(RiverUnmarshaller.java:1853) ~[jboss-client.jar:16.0.0.Final]
	at org.jboss.marshalling.river.RiverObjectInputStream.defaultReadObject(RiverObjectInputStream.java:81) ~[jboss-client.jar:16.0.0.Final]
	at java.lang.Throwable.readObject(Throwable.java:896) ~[?:?]
	at org.jboss.marshalling.reflect.JDKSpecific$SerMethods.callReadObject(JDKSpecific.java:100) ~[jboss-client.jar:16.0.0.Final]
	at org.jboss.marshalling.reflect.SerializableClass.callReadObject(SerializableClass.java:212) ~[jboss-client.jar:16.0.0.Final]
	at org.jboss.marshalling.river.RiverUnmarshaller.doInitSerializable(RiverUnmarshaller.java:1746) ~[jboss-client.jar:16.0.0.Final]
	at org.jboss.marshalling.river.RiverUnmarshaller.doInitSerializable(RiverUnmarshaller.java:1715) ~[jboss-client.jar:16.0.0.Final]
	at org.jboss.marshalling.river.RiverUnmarshaller.doInitSerializable(RiverUnmarshaller.java:1715) ~[jboss-client.jar:16.0.0.Final]
	at org.jboss.marshalling.river.RiverUnmarshaller.doInitSerializable(RiverUnmarshaller.java:1715) ~[jboss-client.jar:16.0.0.Final]
	at org.jboss.marshalling.river.RiverUnmarshaller.doReadNewObject(RiverUnmarshaller.java:1395) ~[jboss-client.jar:16.0.0.Final]
	at org.jboss.marshalling.river.RiverUnmarshaller.doReadObject(RiverUnmarshaller.java:272) ~[jboss-client.jar:16.0.0.Final]
	at org.jboss.marshalling.river.RiverUnmarshaller.doReadObject(RiverUnmarshaller.java:220) ~[jboss-client.jar:16.0.0.Final]
	at org.jboss.marshalling.river.RiverUnmarshaller.readFields(RiverUnmarshaller.java:1853) ~[jboss-client.jar:16.0.0.Final]
	at org.jboss.marshalling.river.RiverObjectInputStream.defaultReadObject(RiverObjectInputStream.java:81) ~[jboss-client.jar:16.0.0.Final]
	at java.lang.Throwable.readObject(Throwable.java:896) ~[?:?]
	at org.jboss.marshalling.reflect.JDKSpecific$SerMethods.callReadObject(JDKSpecific.java:100) ~[jboss-client.jar:16.0.0.Final]
	at org.jboss.marshalling.reflect.SerializableClass.callReadObject(SerializableClass.java:212) ~[jboss-client.jar:16.0.0.Final]
	at org.jboss.marshalling.river.RiverUnmarshaller.doInitSerializable(RiverUnmarshaller.java:1746) ~[jboss-client.jar:16.0.0.Final]
	at org.jboss.marshalling.river.RiverUnmarshaller.doInitSerializable(RiverUnmarshaller.java:1715) ~[jboss-client.jar:16.0.0.Final]
	at org.jboss.marshalling.river.RiverUnmarshaller.doInitSerializable(RiverUnmarshaller.java:1715) ~[jboss-client.jar:16.0.0.Final]
	at org.jboss.marshalling.river.RiverUnmarshaller.doReadNewObject(RiverUnmarshaller.java:1395) ~[jboss-client.jar:16.0.0.Final]
	at org.jboss.marshalling.river.RiverUnmarshaller.doReadObject(RiverUnmarshaller.java:272) ~[jboss-client.jar:16.0.0.Final]
	at org.jboss.marshalling.river.RiverUnmarshaller.doReadObject(RiverUnmarshaller.java:220) ~[jboss-client.jar:16.0.0.Final]
	at org.jboss.marshalling.river.RiverUnmarshaller.readFields(RiverUnmarshaller.java:1853) ~[jboss-client.jar:16.0.0.Final]
	at org.jboss.marshalling.river.RiverObjectInputStream.defaultReadObject(RiverObjectInputStream.java:81) ~[jboss-client.jar:16.0.0.Final]
	at java.lang.Throwable.readObject(Throwable.java:896) ~[?:?]
	at org.jboss.marshalling.reflect.JDKSpecific$SerMethods.callReadObject(JDKSpecific.java:100) ~[jboss-client.jar:16.0.0.Final]
	at org.jboss.marshalling.reflect.SerializableClass.callReadObject(SerializableClass.java:212) ~[jboss-client.jar:16.0.0.Final]
	at org.jboss.marshalling.river.RiverUnmarshaller.doInitSerializable(RiverUnmarshaller.java:1746) ~[jboss-client.jar:16.0.0.Final]
	at org.jboss.marshalling.river.RiverUnmarshaller.doInitSerializable(RiverUnmarshaller.java:1715) ~[jboss-client.jar:16.0.0.Final]
	at org.jboss.marshalling.river.RiverUnmarshaller.doInitSerializable(RiverUnmarshaller.java:1715) ~[jboss-client.jar:16.0.0.Final]
	at org.jboss.marshalling.river.RiverUnmarshaller.doInitSerializable(RiverUnmarshaller.java:1715) ~[jboss-client.jar:16.0.0.Final]
	at org.jboss.marshalling.river.RiverUnmarshaller.doInitSerializable(RiverUnmarshaller.java:1715) ~[jboss-client.jar:16.0.0.Final]
	at org.jboss.marshalling.river.RiverUnmarshaller.doReadNewObject(RiverUnmarshaller.java:1395) ~[jboss-client.jar:16.0.0.Final]
	at org.jboss.marshalling.river.RiverUnmarshaller.doReadObject(RiverUnmarshaller.java:272) ~[jboss-client.jar:16.0.0.Final]
	at org.jboss.marshalling.river.RiverUnmarshaller.doReadObject(RiverUnmarshaller.java:205) ~[jboss-client.jar:16.0.0.Final]
	at org.jboss.marshalling.AbstractObjectInput.readObject(AbstractObjectInput.java:76) ~[jboss-client.jar:16.0.0.Final]
	at org.jboss.ejb.protocol.remote.EJBClientChannel$MethodInvocation$ExceptionResultProducer.getResult(EJBClientChannel.java:1281) ~[jboss-client.jar:16.0.0.Final]
	... 24 more
2023-12-20 22:40:57,674 ERROR [com.jdimension.jlawyer.client.mail.SendAction] java.lang.Exception: Fehler beim Speichern: Failed to read response
2023-12-20 22:40:57,674 ERROR [com.jdimension.jlawyer.client.processing.ProgressableAction] java.lang.Exception: Fehler beim Senden: Fehler beim Speichern: Failed to read response
2023-12-20 22:40:57,675 ERROR [com.jdimension.jlawyer.client.processing.ProgressableAction] ProgressableAction error:Fehler beim Senden: Fehler beim Speichern: Failed to read response

```

**Comment by j-dimension** [comment]
Duplikat von #2222

**Comment by stm9x9** [comment]
> Duplikat von #2222

hm ... sicher? In 2222 wurde die Mail offenbar nicht versandt. Bei mir ist sie aber im gesendet-Ordner gelandet. Ob der Empfänger sie wirklich bekommen hat, kann ich aber frühestens morgen sagen.

**Comment by j-dimension** [comment]
Ja, sicher. Versand fand im Fall von #2222 statt.
