### ISSUE TITLE
beA: Authentifizierung über Karte/Kartenlesegerät

### ISSUE THREAD

**Issue by j-dimension** [jlawyerorg/j-lawyer-org#23]
Linux: braucht libjsb.so
Windows: jsb.dll
Mac: noch unklar, mal in die Mac beA Clientsecurity schauen!

**Comment by j-dimension** [comment]
tlw. Fehler wg. JavaFX

**Comment by j-dimension** [comment]
DaKi am 14.05.2020 über die Mailingliste: 

Ich habe jetzt mal noch ein wenig "gefummelt" und dabei ein ziemlich seltsames Verhalten festgestellt. Am Ende war ich aber mit der Karte angemeldet. Deshalb als Anlage mein Log. Vielleicht kannst du daraus ja irgendwelche hilfreichen Schlüsse ziehen, Jens.

Folgendes war zu beobachten:
1. Ich habe versucht mich mit der Karte im jlawyer anzumelden. Selbes Verhalten wie vorhin geschildert. Ergebnis: Kein beA-Zugriff, Fehlermeldung "not logged in".
2. Unmittelbar im Anschluss habe ich versucht, mich mit Software-Zertifikat anzumelden. Sofort Fehlermeldung "not logged in".
3. Ich habe jlawyer neu gestartet und mich mit dem Software-Zertifikat angemeldet. Anmeldung erfolgreich.
4. Ich habe mich über den Ausloggen-Button wieder vom beA abgemeldet.
5. Ich habe erneut die Anmeldung angewählt, allerdings diesmal mit Karte. Daraufhin kam das Fenster des beA, in dem man Karte oder Zertifikat auswählen kann. Ich habe die Karte ausgewählt. Daraufhin kam der Dialog zur Eingabe des Passworts über den Kartenleser. Ich habe das Passwort 1x eingegeben. Daraufhin wurde wiederum der Auswahldialog von jlawyer (Karte oder Software-Zertifikat) angezeigt. Ich habe wiederum die Karte gewählt. Daraufhin erschien erneut das Fenster des beA, in dem man Karte oder Zertifikat auswählen kann. Ich habe erneut auch hier die Karte ausgewählt. Daraufhin kam der Dialog zur Eingabe des Passworts über den Kartenleser, diesmal aber... wie auch bei der Anmeldung über Browser... mit zweimaliger Abfrage des Passworts. Ich habe das Passwort zweimal eingegeben und war anschließend über jlawyer im beA angemeldet.

```
2020-05-14 11:08:10,774 ERROR [org.jlawyer.bea.BeaWrapper] Unable to get beA folder overview
java.lang.NullPointerException
	at de.governikus.bea.beaToolkit.crypto.HandleCrypto$ForMessageOverview.decrypt(HandleCrypto.java:59)
	at de.governikus.bea.kswtoolkit.socketactions.impl.DecryptFolderOverview.executeAction(DecryptFolderOverview.java:50)
	at de.governikus.bea.kswtoolkit.socketactions.impl.DecryptFolderOverview.executeAction(DecryptFolderOverview.java:27)
	at de.governikus.bea.kswtoolkit.KSWToolkit.decryptfolderOverview(KSWToolkit.java:164)
	at org.jlawyer.bea.BeaWrapper.getFolderOverview(BeaWrapper.java:1365)
```

**Comment by j-dimension** [comment]
Login über separaten Prozess testen - es wird nach Login eigentlich nur die SessionID benötigt.

**Comment by j-dimension** [comment]
Die Anmeldung per Karte wird in der in wenigen Tagen erscheinenden Version offiziell nicht mehr unterstützt, ich schließe dahier.
