### ISSUE TITLE
E-Mail: "failed to parse" 

### ISSUE THREAD

**Issue by Mucki526** [jlawyerorg/j-lawyer-org#2383]
Will gerade eine thunderbirdmail in den dokumentenordner schieben. Die Datei wird verschoben (Enthält zwei jpg als Anlagen), soweit nichts ungewöhnliches - bekomme Fehler beim Laden der Datei "failed to parse". In Thunderbird gibts kein Problem die Datei und Anhänge zu öffnen.  

Importieren mit dem Plugin  als Alternative scheint zu gehen "Datei gesendet"- die Datei erscheint dann aber garnicht in der Akte....

**Comment by j-dimension** [comment]
Nach dem "failed to parse" bitte einen Systemreport erstellen und per Mail senden

**Comment by j-dimension** [comment]
> Importieren mit dem Plugin als Alternative scheint zu gehen "Datei gesendet"- die Datei erscheint dann aber garnicht in der Akte....

Dazu bitte ein eigenes Ticket im Thunderbird-Repository: https://github.com/jlawyerorg/j-lawyer-tbaddon/issues

**Comment by j-dimension** [comment]
```
2024-03-28 15:41:27,870 ERROR [com.jdimension.jlawyer.client.mail.MailContentUI] Error getting contents of IMAP message
java.lang.IllegalArgumentException: failed to parse:
	at java.awt.datatransfer.DataFlavor.<init>(DataFlavor.java:437) ~[?:?]
	at javax.activation.ActivationDataFlavor.<init>(ActivationDataFlavor.java:81) ~[activation-1.1.jar:1.1]
	at com.sun.xml.ws.encoding.ImageDataContentHandler.<init>(ImageDataContentHandler.java:43) ~[rt-2.3.3.jar:2.3.3]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?]
	at java.lang.reflect.ReflectAccess.newInstance(ReflectAccess.java:128) ~[?:?]
	at jdk.internal.reflect.ReflectionFactory.newInstance(ReflectionFactory.java:347) ~[?:?]
	at java.lang.Class.newInstance(Class.java:645) ~[?:?]
	at javax.activation.MailcapCommandMap.getDataContentHandler(MailcapCommandMap.java:596) ~[activation-1.1.jar:1.1]
	at javax.activation.MailcapCommandMap.createDataContentHandler(MailcapCommandMap.java:550) ~[activation-1.1.jar:1.1]
	at javax.activation.CommandMap.createDataContentHandler(CommandMap.java:206) ~[activation-1.1.jar:1.1]
	at javax.activation.DataHandler.getDataContentHandler(DataHandler.java:608) ~[activation-1.1.jar:1.1]
	at javax.activation.DataHandler.getContent(DataHandler.java:536) ~[activation-1.1.jar:1.1]
	at javax.mail.internet.MimeBodyPart.getContent(MimeBodyPart.java:683) ~[javax.mail-1.6.2.jar:1.6.2]
	at com.jdimension.jlawyer.client.mail.MailContentUI.recursiveFindPart(MailContentUI.java:1405) ~[j-lawyer-client.jar:?]
	at com.jdimension.jlawyer.client.mail.MailContentUI.recursiveFindPart(MailContentUI.java:1395) ~[j-lawyer-client.jar:?]
	at com.jdimension.jlawyer.client.mail.MailContentUI.setMessageImpl(MailContentUI.java:1167) ~[j-lawyer-client.jar:?]
	at com.jdimension.jlawyer.client.mail.MailContentUI.setMessage(MailContentUI.java:1029) ~[j-lawyer-client.jar:?]
	at com.jdimension.jlawyer.client.editors.documents.viewer.EmailPanel.setMessage(EmailPanel.java:698) ~[j-lawyer-client.jar:?]
	at com.jdimension.jlawyer.client.editors.documents.viewer.DocumentViewerFactory.getDocumentViewer(DocumentViewerFactory.java:760) ~[j-lawyer-client.jar:?]
	at com.jdimension.jlawyer.client.editors.documents.LoadDocumentPreviewThread.run(LoadDocumentPreviewThread.java:759) ~[j-lawyer-client.jar:?]
	at java.lang.Thread.run(Thread.java:840) ~[?:?]

```

**Comment by Mucki526** [comment]
Ich habe diesen Fehler gerade in der 3.001 wieder. Kopieren der e-mail mit PDF Anhang in den Dokumentenordner geht, dann versagt das Auspacken des PDF - "Failed to Parse". Anlage in den scanordner kopieren und import in die Akte als Workaround geht.

**Comment by j-dimension** [comment]
Dann brauche ich einen Systemreport, unmittelbar nach Auftreten des Fehlers, per E-Mail.
