### ISSUE TITLE
[TASK] Migration auf beA API v9

### ISSUE THREAD

**Issue by j-dimension** [jlawyerorg/j-lawyer-org#2527]
"Die technische Abschaltung der KSW-Schnittstelle V8 ist in der Schulungs- und Partnertestumgebung für Anfang Oktober 2024 und in der Produktivumgebung für Anfang November 2024 vorgesehen."

**Comment by j-dimension** [comment]
neue beA-Bibliotheken nutzen neuste jackson-Bibliotheken.

1. Konflikt mit jboss-client.jar. Dort die jackson core-Klassen entfernt - funktioniert
2. Konflikt mit Nextcloud-Anbindung - dort die jackson core-Klassen per shading relocated, aber scheinbar gibt es eine dynamische Auflösung / Reflection --> Fehler

```
Exception in thread "I/O dispatcher 1" java.lang.AbstractMethodError: Missing implementation of resolved method 'abstract java.lang.Object deserialize(com.fasterxml.jackson.core.JsonParser, com.fasterxml.jackson.databind.DeserializationContext)' of abstract class com.fasterxml.jackson.databind.JsonDeserializer.
	at com.fasterxml.jackson.databind.deser.impl.FieldProperty.deserializeAndSet(FieldProperty.java:138)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:313)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:176)
	at com.fasterxml.jackson.databind.deser.impl.FieldProperty.deserializeAndSet(FieldProperty.java:138)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:313)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:176)
	at com.fasterxml.jackson.databind.deser.impl.FieldProperty.deserializeAndSet(FieldProperty.java:138)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:313)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:176)
	at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext._unwrapAndDeserialize(DefaultDeserializationContext.java:356)
	at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:320)
	at com.fasterxml.jackson.databind.ObjectReader._bindAndClose(ObjectReader.java:2051)
	at com.fasterxml.jackson.databind.ObjectReader.readValue(ObjectReader.java:1459)
	at org.aarboard.nextcloud.api.utils.JsonAnswerParser.parseResponse(JsonAnswerParser.java:41)
	at org.aarboard.nextcloud.api.utils.JsonAnswerParser.parseResponse(JsonAnswerParser.java:13)
	at org.aarboard.nextcloud.api.utils.ConnectorCommon$ResponseCallback.handleResponse(ConnectorCommon.java:215)
	at org.aarboard.nextcloud.api.utils.ConnectorCommon$ResponseCallback.completed(ConnectorCommon.java:201)
	at org.aarboard.nextcloud.api.utils.ConnectorCommon$ResponseCallback.completed(ConnectorCommon.java:189)
```

**Comment by j-dimension** [comment]
Shading zurückgebaut, Nextcloud-Connector auf die Version von Jackson fixiert, die beA möchte:

```
    <dependencyManagement>
        <!-- jackson conflicts with the version that is part of bea-wrapper, therefore fix its version -->
        <dependencies>
            <dependency>
                <groupId>com.fasterxml.jackson.core</groupId>
                <artifactId>jackson-databind</artifactId>
                <version>2.16.1</version>
            </dependency>
            <dependency>
                <groupId>com.fasterxml.jackson.core</groupId>
                <artifactId>jackson-core</artifactId>
                <version>2.16.1</version>
            </dependency>
        </dependencies>
    </dependencyManagement>
```

**Comment by stm9x9** [comment]
gibt es funktionale Neuerungen für uns Nutzer?

**Comment by j-dimension** [comment]
Es soll wohl möglich sein, an ein MJP zu senden.
