### ISSUE TITLE
[BUG] Große PDF Dateien lassen sich nicht öffnen

### ISSUE THREAD

**Issue by iradraconis** [jlawyerorg/j-lawyer-org#2550]
2 PDF Dateien ausprobiert, eine 311 MB und eine 411 MB. Systemreport per Mail geschickt

![Bildschirmfoto 2024-08-27 um 08 56 29](https://github.com/user-attachments/assets/a4a41a75-b2fd-4107-acf2-54b205150475)

**Comment by iradraconis** [comment]
Diese beiden Dateien bekomme ich aufgrund des selben Fehlers schon gar nicht lokal wieder gespeichert, um sie mit meinem Test Server auszuprobieren.

Ich habe gerade keine vergleichbare große Datei zur Hand. :(

**Comment by j-dimension** [comment]
Du könntest in der betroffenen Akte im Kopf oben auf die Aktenbezeichnung rechtsklicken und die ID in die Zwischenablage übernehmen. Dann im "j-lawyer-data/archivefiles"-Verzeichnis des Servers das Unterverzeichnis anhand der ID suchen. Dort dann die Dokumente nach Größe sortieren und die dicksten Dateien identifizieren. 

Mit .pdf am Ende in die 2.7 kopieren.

**Comment by iradraconis** [comment]
Ich habe das ausprobiert und kann die Dateien noch nicht mal per Drag-and-Drop oder über die  "hinzufügen"  Schaltfläche in die Akte ziehen. Ich weiß nicht genau, wie meine Mitarbeiterin das  auf dem Rechner im Sekretariat gemacht hat. Jedenfalls bekomme ich die Dateien nicht in  die Akte. Dieselbe Fehlermeldung auch in der Version 2.7.

**Comment by j-dimension** [comment]
```
2024-08-27 08:51:15,128 INFO  [com.jdimension.jlawyer.client.editors.documents.CachingDocumentLoader] Document cache statistics: 50.0% cache hits
2024-08-27 08:54:08,894 INFO  [com.jdimension.jlawyer.client.editors.documents.viewer.PdfImageScrollingPanel] Rendering large PDF CD - Bildaufnahmen-UST_0092402_2021 - ZuA_0092353_2021.pdf with 42308808 bytes.
2024-08-27 08:55:11,801 ERROR [com.jdimension.jlawyer.client.editors.documents.LoadDocumentPreviewThread] javax.ejb.EJBException: WFLYEJB0442: Unexpected Error
2024-08-27 08:55:21,154 INFO  [com.jdimension.jlawyer.client.editors.documents.viewer.PdfImageScrollingPanel] Rendering large PDF CD-ST_0055831_2021 - Urkopie.pdf with 326403993 bytes.
2024-08-27 08:55:24,492 ERROR [com.jdimension.jlawyer.client.editors.files.OpenDocumentAction] Could not open document
java.lang.OutOfMemoryError: Java heap space
	at java.util.Arrays.copyOf(Arrays.java:3537) ~[?:?]
	at java.io.ByteArrayOutputStream.ensureCapacity(ByteArrayOutputStream.java:100) ~[?:?]
	at java.io.ByteArrayOutputStream.write(ByteArrayOutputStream.java:130) ~[?:?]
	at java.io.OutputStream.write(OutputStream.java:127) ~[?:?]
	at com.jdimension.jlawyer.client.editors.documents.CachingDocumentLoader.loadFromRemote(CachingDocumentLoader.java:796) ~[j-lawyer-client.jar:?]
	at com.jdimension.jlawyer.client.editors.documents.CachingDocumentLoader.getDocument(CachingDocumentLoader.java:759) ~[j-lawyer-client.jar:?]
	at com.jdimension.jlawyer.client.utils.CaseUtils.openDocumentInCustomLauncher(CaseUtils.java:738) ~[j-lawyer-client.jar:?]
	at com.jdimension.jlawyer.client.utils.CaseUtils.openDocument(CaseUtils.java:728) ~[j-lawyer-client.jar:?]
	at com.jdimension.jlawyer.client.editors.files.OpenDocumentAction.execute(OpenDocumentAction.java:716) ~[j-lawyer-client.jar:?]
	at com.jdimension.jlawyer.client.processing.ProgressableAction.lambda$start$6(ProgressableAction.java:767) ~[j-lawyer-client.jar:?]
	at com.jdimension.jlawyer.client.processing.ProgressableAction$$Lambda$1105/0x0000000800ddd4f0.run(Unknown Source) ~[?:?]
	at java.lang.Thread.run(Thread.java:840) ~[?:?]
```

**Comment by j-dimension** [comment]
-Xmx des Clients anpassen

**Comment by j-dimension** [comment]
-Xmx4096M

**Comment by j-dimension** [comment]
@iradraconis falls Du die Dateien noch parat hast, wäre ein kurzer Test hilfreich. Danke!

**Comment by iradraconis** [comment]
habe mit einer Videodatei getestet, die 1036 mb hat und die vor etwa 1 Woche nicht zu öffnen war. Nun kann ich das Video öffnen. Die konkrete PDF Datei aus dem Ticket habe ich nicht gefunden, aber da das Video lädt, vermute ich, hat der FIX hier Abhilfe geschafft. Danke!
