### ISSUE TITLE
[TASK] geschützte PDF-Formulare als Vorlagen verwenden

### ISSUE THREAD

**Issue by j-dimension** [jlawyerorg/j-lawyer-org#2677]
Fehler: 

```
2024-11-17 21:34:33,055 ERROR [com.jdimension.jlawyer.services.ArchiveFileService] (default task-25) could not set placeholders in file /usr/local/j-lawyer-server/j-lawyer-data/archivefiles/44cdcf787f0001014f144b3cdc2066cb/3bd592d17f0001017185b5ea09f634fd: java.lang.IllegalStateException: PDF contains an encryption dictionary, please remove it with setAllSecurityToBeRemoved() or set a protection policy with protect()
        at deployment.j-lawyer-server.ear//org.apache.pdfbox.pdfwriter.COSWriter.write(COSWriter.java:1316)
        at deployment.j-lawyer-server.ear//org.apache.pdfbox.pdfwriter.COSWriter.write(COSWriter.java:1268)
        at deployment.j-lawyer-server.ear//org.apache.pdfbox.pdmodel.PDDocument.save(PDDocument.java:1334)
        at deployment.j-lawyer-server.ear//org.apache.pdfbox.pdmodel.PDDocument.save(PDDocument.java:1305)
        at deployment.j-lawyer-server.ear.j-lawyer-server-ejb.jar//com.jdimension.jlawyer.documents.PdfFormsAccess.setPlaceHolders(PdfFormsAccess.java:698)
        at deployment.j-lawyer-server.ear.j-lawyer-server-ejb.jar//com.jdimension.jlawyer.documents.LibreOfficeAccess.setPlaceHolders(LibreOfficeAccess.java:1533)
        at deployment.j-lawyer-server.ear.j-lawyer-server-ejb.jar//com.jdimension.jlawyer.services.ArchiveFileService.addDocumentFromTemplate(ArchiveFileService.java:3601)
        at deployment.j-lawyer-server.ear.j-lawyer-server-ejb.jar//com.jdimension.jlawyer.services.ArchiveFileService.addDocumentFromTemplate(ArchiveFileService.java:3665)
```

**Comment by j-dimension** [comment]
[2024-11-16_bs-25-ausfuellbar-v1.pdf](https://github.com/user-attachments/files/17792324/2024-11-16_bs-25-ausfuellbar-v1.pdf)
