### ISSUE TITLE
[BUG] Absturz mit Fehlermeldung  javax.ejb.EJBTransactionRolledbackException: No entity found for query

### ISSUE THREAD

**Issue by jankowa** [jlawyerorg/j-lawyer-org#2711]
**Fehlerbeschreibung**

Absturz des Clients bei bestimmten Operationen nach Update auf Version 3.0.0.1 (Server und Client)

**Schritte zum Nachvollziehen**

Der Fehler kann auf verschiedene Art getriggert werden. Der Client friert dann dann komplett ein und muss neu gestartet werden:

1. im Client Einstellung -> Dokumente -> Dateinamen:  beim Click auf einen Dateinamen
2. E-Mail in einer Akte: Anhang aus der E-Mail in die Akte verschoben
3. Aus der Akte heraus E-Mail geschrieben - beim Absenden abgestürzt - E-Mail ging aber raus
4. Bea-Nachricht: im Speicherdialog eingefroren

Im Server-Log findet sich folgende Fehlermeldung:

```
[31m10:38:35,112 ERROR [org.jboss.as.ejb3.invocation] (default task-4) WFLYEJB0034: Jakarta Enterprise Beans Invocation failed on component AppUserBeanFacade for method public abstract com.jdimension.jlawyer.persistence.AppUserBean com.jdimension.jlawyer.persistence.AppUserBeanFacadeLocal.findByPrincipalId
(java.lang.String): javax.ejb.EJBTransactionRolledbackException: No entity found for query
        at org.jboss.as.ejb3@26.1.3.Final//org.jboss.as.ejb3.tx.CMTTxInterceptor.invokeInCallerTx(CMTTxInterceptor.java:219)
        at org.jboss.as.ejb3@26.1.3.Final//org.jboss.as.ejb3.tx.CMTTxInterceptor.required(CMTTxInterceptor.java:392)
```
komplettes Log: [j-lawyer.log](https://github.com/user-attachments/files/17946912/j-lawyer.log)

Nach einem Neustart des Servers (der kompletten VM) stürzt der Client bei der Operation nicht mehr ab, die Fehlermeldung im Server-Log bleibt aber.

**Erwartetes Verhalten**

Operationen können ohne Absturz ausgeführt werden, keine Fehlermeldungen im Log.

**verwendete Umgebung:**
 - Betriebssystem: Debian 11 (bullseye)
 - j-lawyer.org Version: 3.0.0.1

**Comment by j-dimension** [comment]
Die Logs und Abstürze haben nichts miteinander zu tun. Die Logs in der Form

```
[31m10:38:35,112 ERROR [org.jboss.as.ejb3.invocation] (default task-4) WFLYEJB0034: Jakarta Enterprise Beans Invocation failed on component AppUserBeanFacade for method public abstract com.jdimension.jlawyer.persistence.AppUserBean com.jdimension.jlawyer.persistence.AppUserBeanFacadeLocal.findByPrincipalId
(java.lang.String): javax.ejb.EJBTransactionRolledbackException: No entity found for query
```

besagen, dass ein Nutzer anhand seines Nutzernamens geladen werden soll, den es nicht mehr gibt. Bspw. steht Account Müller als Verantwortlicher an Akte oder Kalendereintrag, der Account wurde aber gelöscht. 

Wurden eigene Dateinamensschemata definiert? Es gibt dort einen Bug, ggf. mal diese Datei ersetzen:
https://cloud.j-dimension.com/index.php/s/wscJLx3KDCKoEWm?path=%2FVorschau%2FServer%2F2024-11-15_3.0.0.1_Bugfixes_HTMLExport_Dateinamenschema

Server stoppen, Datei ersetzen, Server starten.

**Comment by j-dimension** [comment]
siehe #2667

**Comment by jankowa** [comment]
Vielen Dank für die Schnelle Antwort. Wir werden das mal entsprechend testen.
