### ISSUE TITLE
[BUG] jpg Datei lässt sich nicht in PDF konvertieren

### ISSUE THREAD

**Issue by iradraconis** [jlawyerorg/j-lawyer-org#2717]
Ich hatte das in den vergangenen Wochen schon einige Male, davor  nie. Ich hatte es für Einzelfälle gehalten. Heute ist es wieder passiert. Rechtsklick und dann in PDF konvertieren führt zu dieser Fehlermeldung. Den Systembericht habe ich per E-Mail geschickt.

![grafik](https://github.com/user-attachments/assets/df202bc0-13f0-4fdb-a182-1aca1f8a2d36)

**Comment by j-dimension** [comment]
Um das eingrenzen zu können, wäre es hilfreich zu prüfen ob die Datei sich an der angegebenen Stelle befindet. 

Wenn nicht, ist es ein Problem beim Schreiben der temporären Datei. 

Wenn sie existiert, dann bitte aus dem Systemreport den Pfad kopieren und mit `ls -l <Zwischenablage>` prüfen, ob die Datei exakt so heißt wie es die Anwendung erwartet.

**Comment by j-dimension** [comment]
```
2024-12-04 10:34:59,849 ERROR [com.jdimension.jlawyer.client.editors.files.ArchiveFilePanel] Could not convert document to PDF
java.io.FileNotFoundException: /tmp/9105d6d1c0a8b24957337dee2dcebab7/2024-12-04_WhatsApp Bild 2024-12-03 um 13.46.02_346c7356.pdf (Datei oder Verzeichnis nicht gefunden)
	at java.io.FileInputStream.open0(Native Method) ~[?:?]
	at java.io.FileInputStream.open(FileInputStream.java:216) ~[?:?]
	at java.io.FileInputStream.<init>(FileInputStream.java:157) ~[?:?]
	at com.jdimension.jlawyer.server.utils.ServerFileUtils.readFile(ServerFileUtils.java:781) ~[j-lawyer-server-common.jar:?]
	at com.jdimension.jlawyer.client.editors.files.ArchiveFilePanel.lambda$convertDocumentToPdf$9(ArchiveFilePanel.java:5654) ~[j-lawyer-client.jar:?]
	at com.jdimension.jlawyer.client.editors.files.ArchiveFilePanel.waitForOpenDocument(ArchiveFilePanel.java:1491) ~[j-lawyer-client.jar:?]
	at com.jdimension.jlawyer.client.editors.files.ArchiveFilePanel.convertDocumentToPdf(ArchiveFilePanel.java:5707) ~[j-lawyer-client.jar:?]
	at com.jdimension.jlawyer.client.editors.files.ArchiveFilePanel.mnuDuplicateDocumentAsPdfActionPerformed(ArchiveFilePanel.java:5739) ~[j-lawyer-client.jar:?]
	at com.jdimension.jlawyer.client.editors.files.ArchiveFilePanel$9.actionPerformed(ArchiveFilePanel.java:2048) ~[j-lawyer-client.jar:?]
```

**Comment by iradraconis** [comment]
![grafik](https://github.com/user-attachments/assets/7ddb00bc-2940-4640-8bf7-a78c4826943f)

**Comment by j-dimension** [comment]
Dann bitte mal prüfen, ob die Konvertierung *für diese Datei* an sich funktioniert:

`libreoffice --headless --convert-to pdf:writer_pdf_Export:{\"SelectPdfVersion\":{\"type\":\"long\",\"value\":3}\"} --outdir /home/jens/Downloads/ /home/jens/Downloads/iradraconis.png`

(Pfade ersetzen)

**Comment by iradraconis** [comment]
![Bildschirmfoto vom 2024-12-04 11-36-45](https://github.com/user-attachments/assets/1acfdada-89c4-426a-bbf3-99644e39d6a6)

**Comment by j-dimension** [comment]
Wenn /home/max/2.jpg existiert und nicht leer ist, dann liegt es an der Datei. LibreOffice meldet, dass nicht konvertiert werden kann.

Man könnte die jetzt noch testweise in LibreOffice Draw öffnen und dort das Konvertieren versuchen.

**Comment by iradraconis** [comment]
Das war der entscheidende Hinweis. Die Draw-Komponente war bei meiner Linux-Installation nicht installiert. Ich habe diese gerade installiert, den Befehl noch einmal ausgeführt und dann hat die Konvertierung im Terminal geklappt. Die Konvertierung klappt jetzt auch im JLawyer.

**Comment by j-dimension** [comment]
Ich wusste gar nicht dass man Draw nicht mitinstallieren kann :-)

**Comment by iradraconis** [comment]
> Ich wusste gar nicht dass man Draw nicht mitinstallieren kann :-)

ich bis jetzt auch nicht, habe es aber auch nie gebraucht. Der Rechner ist aber schon locker 1 1/2 Jahre in Betrieb. Komisch, dass es bisher nicht aufgetreten ist.
