### ISSUE TITLE
[BUG]  Nexcloud Freigabe Fehler

### ISSUE THREAD

**Issue by iradraconis** [jlawyerorg/j-lawyer-org#2728]
![grafik](https://github.com/user-attachments/assets/06f8f309-53e9-435d-bc25-e8fd23277ca7)

Systembericht per Mail

**Comment by j-dimension** [comment]
Welche Änderungen hat es gegeben? Wann gingen die Freigaben zuletzt? 

Das letzte Nextcloud-Update für die von Dir genutzte Installation hat es am 5.11. gegeben.

**Comment by j-dimension** [comment]
```
2024-12-06 16:32:15,404 WARN  [shaded.org.apache.http.client.protocol.ResponseProcessCookies] Invalid cookie header: "Set-Cookie: cookie_test=test; expires=Fri, 06 Dec 2024 16:32:15 GMT; Max-Age=3600". Invalid 'expires' attribute: Fri, 06 Dec 2024 16:32:15 GMT
2024-12-06 16:32:15,409 ERROR [com.jdimension.jlawyer.client.editors.files.ArchiveFilePanel] Error removing document
org.aarboard.nextcloud.api.exception.NextcloudApiException: java.util.concurrent.ExecutionException: org.aarboard.nextcloud.api.exception.NextcloudApiException: Request failed with 404 Not Found
	at org.aarboard.nextcloud.api.utils.NextcloudResponseHelper.getAndWrapException(NextcloudResponseHelper.java:40) ~[j-lawyer-cloud.jar:?]
	at org.aarboard.nextcloud.api.utils.NextcloudResponseHelper.getAndCheckStatus(NextcloudResponseHelper.java:17) ~[j-lawyer-cloud.jar:?]
	at org.aarboard.nextcloud.api.filesharing.FilesharingConnector.getShares(FilesharingConnector.java:86) ~[j-lawyer-cloud.jar:?]
	at org.aarboard.nextcloud.api.filesharing.FilesharingConnector.getShares(FilesharingConnector.java:63) ~[j-lawyer-cloud.jar:?]
	at org.aarboard.nextcloud.api.NextcloudConnector.getShares(NextcloudConnector.java:940) ~[j-lawyer-cloud.jar:?]
	at com.jdimension.jlawyer.client.cloud.CloudInstance.getShares(CloudInstance.java:757) ~[j-lawyer-client.jar:?]
	at com.jdimension.jlawyer.client.cloud.SendCloudShare.<init>(SendCloudShare.java:717) ~[j-lawyer-client.jar:?]
	at com.jdimension.jlawyer.client.editors.files.ArchiveFilePanel.mnuShareNextcloudActionPerformed(ArchiveFilePanel.java:6438) ~[j-lawyer-client.jar:?]
	at com.jdimension.jlawyer.client.editors.files.ArchiveFilePanel$41.actionPerformed(ArchiveFilePanel.java:2369) ~[j-lawyer-client.jar:?]
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1972) ~[?:?]
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2313) ~[?:?]
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405) ~[?:?]
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262) ~[?:?]
	at javax.swing.AbstractButton.doClick(AbstractButton.java:374) ~[?:?]
	at javax.swing.plaf.basic.BasicMenuItemUI.doClick(BasicMenuItemUI.java:1028) ~[?:?]
	at javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(BasicMenuItemUI.java:1072) ~[?:?]
	at java.awt.Component.processMouseEvent(Component.java:6626) ~[?:?]
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3389) ~[?:?]
	at java.awt.Component.processEvent(Component.java:6391) ~[?:?]
	at java.awt.Container.processEvent(Container.java:2266) ~[?:?]
	at java.awt.Component.dispatchEventImpl(Component.java:5001) ~[?:?]
	at java.awt.Container.dispatchEventImpl(Container.java:2324) ~[?:?]
	at java.awt.Component.dispatchEvent(Component.java:4833) ~[?:?]
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4948) ~[?:?]
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4575) ~[?:?]
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4516) ~[?:?]
	at java.awt.Container.dispatchEventImpl(Container.java:2310) ~[?:?]
	at java.awt.Window.dispatchEventImpl(Window.java:2780) ~[?:?]
	at java.awt.Component.dispatchEvent(Component.java:4833) ~[?:?]
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:775) ~[?:?]
	at java.awt.EventQueue$4.run(EventQueue.java:720) ~[?:?]
	at java.awt.EventQueue$4.run(EventQueue.java:714) ~[?:?]
	at java.security.AccessController.doPrivileged(AccessController.java:399) ~[?:?]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86) ~[?:?]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:97) ~[?:?]
	at java.awt.EventQueue$5.run(EventQueue.java:747) ~[?:?]
	at java.awt.EventQueue$5.run(EventQueue.java:745) ~[?:?]
	at java.security.AccessController.doPrivileged(AccessController.java:399) ~[?:?]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86) ~[?:?]
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:744) ~[?:?]
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203) ~[?:?]
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124) ~[?:?]
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113) ~[?:?]
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109) ~[?:?]
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101) ~[?:?]
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:90) ~[?:?]
Caused by: java.util.concurrent.ExecutionException: org.aarboard.nextcloud.api.exception.NextcloudApiException: Request failed with 404 Not Found
	at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:396) ~[?:?]
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2073) ~[?:?]
	at org.aarboard.nextcloud.api.utils.NextcloudResponseHelper.getAndWrapException(NextcloudResponseHelper.java:38) ~[j-lawyer-cloud.jar:?]
	... 45 more
Caused by: org.aarboard.nextcloud.api.exception.NextcloudApiException: Request failed with 404 Not Found
	at org.aarboard.nextcloud.api.utils.ConnectorCommon$ResponseCallback.handleResponse(ConnectorCommon.java:219) ~[j-lawyer-cloud.jar:?]
	at org.aarboard.nextcloud.api.utils.ConnectorCommon$ResponseCallback.completed(ConnectorCommon.java:201) ~[j-lawyer-cloud.jar:?]
	at org.aarboard.nextcloud.api.utils.ConnectorCommon$ResponseCallback.completed(ConnectorCommon.java:189) ~[j-lawyer-cloud.jar:?]
	at shaded.org.apache.http.concurrent.BasicFuture.completed(BasicFuture.java:122) ~[j-lawyer-cloud.jar:?]
	at shaded.org.apache.http.impl.nio.client.DefaultClientExchangeHandlerImpl.responseCompleted(DefaultClientExchangeHandlerImpl.java:182) ~[j-lawyer-cloud.jar:?]
	at shaded.org.apache.http.nio.protocol.HttpAsyncRequestExecutor.processResponse(HttpAsyncRequestExecutor.java:448) ~[j-lawyer-cloud.jar:?]
	at shaded.org.apache.http.nio.protocol.HttpAsyncRequestExecutor.inputReady(HttpAsyncRequestExecutor.java:338) ~[j-lawyer-cloud.jar:?]
	at shaded.org.apache.http.impl.nio.DefaultNHttpClientConnection.consumeInput(DefaultNHttpClientConnection.java:265) ~[j-lawyer-cloud.jar:?]
	at shaded.org.apache.http.impl.nio.client.InternalIODispatch.onInputReady(InternalIODispatch.java:87) ~[j-lawyer-cloud.jar:?]
	at shaded.org.apache.http.impl.nio.client.InternalIODispatch.onInputReady(InternalIODispatch.java:40) ~[j-lawyer-cloud.jar:?]
	at shaded.org.apache.http.impl.nio.reactor.AbstractIODispatch.inputReady(AbstractIODispatch.java:121) ~[j-lawyer-cloud.jar:?]
	at shaded.org.apache.http.impl.nio.reactor.BaseIOReactor.readable(BaseIOReactor.java:162) ~[j-lawyer-cloud.jar:?]
	at shaded.org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvent(AbstractIOReactor.java:337) ~[j-lawyer-cloud.jar:?]
	at shaded.org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvents(AbstractIOReactor.java:315) ~[j-lawyer-cloud.jar:?]
	at shaded.org.apache.http.impl.nio.reactor.AbstractIOReactor.execute(AbstractIOReactor.java:276) ~[j-lawyer-cloud.jar:?]
	at shaded.org.apache.http.impl.nio.reactor.BaseIOReactor.execute(BaseIOReactor.java:104) ~[j-lawyer-cloud.jar:?]
	at shaded.org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor$Worker.run(AbstractMultiworkerIOReactor.java:591) ~[j-lawyer-cloud.jar:?]
	at java.lang.Thread.run(Thread.java:840) ~[?:?]

```

**Comment by iradraconis** [comment]
Das aktive Freigeben habe ich schon recht lange nicht (zuletzt im Sommer) benutzt. Die Links werden von meinen Mandanten nach wie vor benutzt, um Dateien hochzuladen.

Ich habe bewusst nichts geändert.

**Comment by j-dimension** [comment]
Kannst Du das mal mit einem der anderen Nextcloud-Accounts versuchen?

**Comment by iradraconis** [comment]
Mit einem anderen Nutzer klappt es. Ist aber derselbe Nextcloud Account.

**Comment by j-dimension** [comment]
Sind die Einstellungen in der Nutzerverwaltung (bzgl. Nextcloud) bei beiden Nutzern identisch?

**Comment by iradraconis** [comment]
ja

**Comment by j-dimension** [comment]
Das ist nicht zu erklären. Müsste fernwarten, um das analysieren zu können.

**Comment by j-dimension** [comment]
Gern melden, wenn es hier noch etwas zu tun gibt.

**Comment by iradraconis** [comment]
Es funktioniert nach wie vor nicht. Kann ich etwas tun?

**Comment by j-dimension** [comment]
Das muss irgendetwas ganz seltsames sein, wenn es bei einem Nutzer geht und beim anderen nicht. 

Helfen würde eine Abfrage auf der Datenbank:

`SELECT principalId, cloudHost, cloudPort, cloudSsl, cloudUser, cloudPassword, cloudPath FROM security_users;`

Oder ein stupides Ersetzen der aktuellen Eingaben durch Neueingabe am nicht funktionierenden User. Womöglich ist durch copy & paste irgendein (nicht sichtbares) Unicode-Sonderzeichen in ein Feld geraten.

**Comment by iradraconis** [comment]
Problem gelöst.. Pfad muss leer sein. Mein Fehler.
