### ISSUE TITLE
beA: encrypt / safely store SSL certificate

### ISSUE THREAD

**Issue by j-dimension** [jlawyerorg/j-lawyer-org#29]
Java-Runtime braucht bestimmte cacerts der BRAK! und JCE.

**Comment by j-dimension** [comment]
BeaWrapper nutzt aktuell noch hartkodierten Pfad zum Keystore

**Comment by j-dimension** [comment]
verschiedene Keystores für SPT, PRD und SPT_PRD erstellt. Nur SPT funktioniert, alle andern bringen Fehler: 

`	Suppressed: org.jboss.ejb.client.RequestSendFailedException
		at org.jboss.ejb.protocol.remote.RemoteEJBReceiver$1.handleFailed(RemoteEJBReceiver.java:101)
		at org.jboss.ejb.protocol.remote.RemoteEJBReceiver$1.handleFailed(RemoteEJBReceiver.java:74)
		at org.xnio.IoFuture$HandlingNotifier.notify(IoFuture.java:215)
		at org.xnio.AbstractIoFuture$NotifierRunnable.run(AbstractIoFuture.java:720)
		at org.xnio.IoUtils$2.execute(IoUtils.java:71)
		at org.xnio.AbstractIoFuture.runNotifier(AbstractIoFuture.java:693)
		at org.xnio.AbstractIoFuture$FailedState.withNotifier(AbstractIoFuture.java:177)
		at org.xnio.AbstractIoFuture.addNotifier(AbstractIoFuture.java:570)
		at org.jboss.ejb.protocol.remote.RemoteEJBReceiver.processInvocation(RemoteEJBReceiver.java:130)
		at org.jboss.ejb.client.EJBClientInvocationContext.sendRequest(EJBClientInvocationContext.java:479)
		at org.jboss.ejb.protocol.remote.RemotingEJBClientInterceptor.handleInvocation(RemotingEJBClientInterceptor.java:51)
		at org.jboss.ejb.client.EJBClientInvocationContext.sendRequest(EJBClientInvocationContext.java:491)
		at org.jboss.ejb.client.TransactionPostDiscoveryInterceptor.handleInvocation(TransactionPostDiscoveryInterceptor.java:79)
		at org.jboss.ejb.client.EJBClientInvocationContext.sendRequest(EJBClientInvocationContext.java:491)
		at org.jboss.ejb.client.DiscoveryEJBClientInterceptor.handleInvocation(DiscoveryEJBClientInterceptor.java:92)
		at org.jboss.ejb.client.EJBClientInvocationContext.sendRequest(EJBClientInvocationContext.java:491)
		at org.jboss.ejb.client.NamingEJBClientInterceptor.handleInvocation(NamingEJBClientInterceptor.java:67)
		at org.jboss.ejb.client.EJBClientInvocationContext.sendRequest(EJBClientInvocationContext.java:491)
		at org.jboss.ejb.client.TransactionInterceptor.handleInvocation(TransactionInterceptor.java:165)
		at org.jboss.ejb.client.EJBClientInvocationContext.sendRequest(EJBClientInvocationContext.java:491)
		at org.wildfly.common.context.Contextual.runExConsumer(Contextual.java:203)
		at org.jboss.ejb.client.EJBClientInvocationContext.sendRequestInitial(EJBClientInvocationContext.java:327)
		at org.jboss.ejb.client.EJBInvocationHandler.invoke(EJBInvocationHandler.java:173)
		... 6 more
	Caused by: java.io.IOException: JBREM000212: Failed to configure SSL context
		at org.jboss.remoting3.Endpoint.getConnectedIdentity(Endpoint.java:120)
		at org.jboss.ejb.protocol.remote.RemoteEJBReceiver.lambda$getConnection$2(RemoteEJBReceiver.java:185)
		at java.security.AccessController.doPrivileged(Native Method)
		at org.jboss.ejb.protocol.remote.RemoteEJBReceiver.getConnection(RemoteEJBReceiver.java:185)
		at org.jboss.ejb.protocol.remote.RemoteEJBReceiver.processInvocation(RemoteEJBReceiver.java:128)
		... 20 more
	Caused by: java.security.NoSuchAlgorithmException: Error constructing implementation (algorithm: Default, provider: SunJSSE, class: sun.security.ssl.SSLContextImpl$DefaultSSLContext)
		at java.security.Provider$Service.newInstance(Provider.java:1617)
		at sun.security.jca.GetInstance.getInstance(GetInstance.java:236)
		at sun.security.jca.GetInstance.getInstance(GetInstance.java:164)
		at javax.net.ssl.SSLContext.getInstance(SSLContext.java:156)
		at javax.net.ssl.SSLContext.getDefault(SSLContext.java:96)
		at org.wildfly.security.auth.client.AuthenticationContextConfigurationClient.getSSLContext(AuthenticationContextConfigurationClient.java:221)
		at org.wildfly.security.auth.client.AuthenticationContextConfigurationClient.getSSLContext(AuthenticationContextConfigurationClient.java:208)
		at org.jboss.remoting3.Endpoint.getConnectedIdentity(Endpoint.java:118)
		... 24 more
	Caused by: java.security.UnrecoverableKeyException: Cannot recover key
		at sun.security.provider.KeyProtector.recover(KeyProtector.java:315)
		at sun.security.provider.JavaKeyStore.engineGetKey(JavaKeyStore.java:141)
		at sun.security.provider.JavaKeyStore$JKS.engineGetKey(JavaKeyStore.java:56)
		at sun.security.provider.KeyStoreDelegator.engineGetKey(KeyStoreDelegator.java:96)
		at sun.security.provider.JavaKeyStore$DualFormatJKS.engineGetKey(JavaKeyStore.java:70)
		at java.security.KeyStore.getKey(KeyStore.java:1023)
		at sun.security.ssl.SunX509KeyManagerImpl.<init>(SunX509KeyManagerImpl.java:133)
		at sun.security.ssl.KeyManagerFactoryImpl$SunX509.engineInit(KeyManagerFactoryImpl.java:70)
		at javax.net.ssl.KeyManagerFactory.init(KeyManagerFactory.java:256)
		at sun.security.ssl.SSLContextImpl$DefaultManagersHolder.getKeyManagers(SSLContextImpl.java:979)
		at sun.security.ssl.SSLContextImpl$DefaultManagersHolder.<clinit>(SSLContextImpl.java:864)
		at sun.security.ssl.SSLContextImpl$DefaultSSLContext.<init>(SSLContextImpl.java:1019)
		at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
		at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
		at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
		at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
		at java.security.Provider$Service.newInstance(Provider.java:1595)
		... 31 more`
