### ISSUE TITLE
beA: Fehler beim Versenden ans (Sozial)gericht

### ISSUE THREAD

**Issue by stm9x9** [jlawyerorg/j-lawyer-org#352]
Wenn ich per bea senden eine beA erstelle und dann ein als Beteiligten eingerichtetes Gericht aus der Liste rechts nehme, kommt dieser Fehler:

![image](https://user-images.githubusercontent.com/29924198/65393654-a4fcdc80-dd83-11e9-93bb-60018cc3bcc1.png)

danach ist der Haken zwar in der Liste rechts aber im Feld ist nix:

![image](https://user-images.githubusercontent.com/29924198/65393632-54857f00-dd83-11e9-9a06-0253d53e5c54.png)

Wenn ich zb einen beteiligten Anwalt da wählte, kommt kein Fehler und der Anwalt landet in der Liste.

**Comment by j-dimension** [comment]
Bitte das client.log anhängen. Danke!

**Comment by j-dimension** [comment]
Ich verfüge über ein "Testgericht" in der beA-Testumgebung und kann dort das Problem nicht nachvollziehen. Bin daher auf das Log angewiesen.

**Comment by stm9x9** [comment]
Da ist nicht viel. Ich habe mir das Log angeguckt, bis vor dem bea-Senden. Danach kam genau eine Zeile dazu: 

2019-09-22 23:22:28,438 ERROR [com.jdimension.jlawyer.client.bea.SendBeaMessageDialog] org.jlawyer.bea.BeaWrapperException: de.brak.bea.application.dto.soap.types5.BeaFault: 0207 - There is no data for given Identity, because of the IdentitySourceType!

**Comment by stm9x9** [comment]
"Identität anzeigen" nix passiert

![image](https://user-images.githubusercontent.com/29924198/65394663-fa8bb600-dd90-11e9-8f2c-7c855ba8a17f.png)

**Comment by stm9x9** [comment]
![image](https://user-images.githubusercontent.com/29924198/65394672-155e2a80-dd91-11e9-95a5-e69f57d0818e.png)
 ergibt 
![image](https://user-images.githubusercontent.com/29924198/65394677-1d1dcf00-dd91-11e9-9ee3-dee1bf7c3648.png)

**Comment by stm9x9** [comment]
govello-1260364804747-000194713 gegen Infos aus Governikus gecheckt: SAFE-ID stimmt

**Comment by stm9x9** [comment]
anderes Gericht aus der importieren Adressdatenbank probiert. Gerichtsvollzieherin versucht. 

Der Fehler passiert bei allen importierten Adressen.

Ich habe als Gegentest gemacht:

neue Adresse angelegt über bea-Suche mit einem Anwalt und danach einer Akte zugefügt. Bei dem geht alles.

**Comment by stm9x9** [comment]
ich habe jetzt mal manuell eine Gerichts-SAFE-ID  govello-1260364804747-000194713 in meine Anwaltsadresse kopiert. Sofort kommt bei mir auch der Fehler.

**Comment by j-dimension** [comment]
Okay, vermutlich liefert die Schnittstelle dann nur Informationen zu beA-Teilnehmern. Der Fehler muss in diesem Fall wohl abgefangen werden.

**Comment by j-dimension** [comment]
Auch die zuletzt von mir gelieferte bea wrapper - jar liefert keine detaillierten Logs?

**Comment by stm9x9** [comment]
ich weiß nicht ob das damit zusammenhängt:

In der bea-Nachrichtenübersicht (egal ob gesendet oder empfangen) werden Anwälte mit Namen angezeigt, Gerichte oder andere Justizeinrichtungen nur mit der SAFE-ID, als ob die nicht aufgelöst werden kann. In der einzelnen Nachrichtenansicht ist dann alles korrekt zu sehen.

![image](https://user-images.githubusercontent.com/29924198/65466496-4c9b0d00-de5f-11e9-827b-35c0fb05df83.png)

**Comment by j-dimension** [comment]
@stm9x9  kannst du nochmal mit der neuen wrapper jar testen?

**Comment by stm9x9** [comment]
![image](https://user-images.githubusercontent.com/29924198/65466713-f8dcf380-de5f-11e9-85b8-bb8595581a85.png)

**Comment by j-dimension** [comment]
Und der Versand funktioniert?

**Comment by stm9x9** [comment]
es liegt noch in Postausgang. Und die zur Akte gespeicherte bea ist kaputt:

![image](https://user-images.githubusercontent.com/29924198/65467158-1494c980-de61-11e9-847a-58c2de4f1b9d.png)

![image](https://user-images.githubusercontent.com/29924198/65467161-19597d80-de61-11e9-93fb-932426c74e5b.png)

**Comment by j-dimension** [comment]
@stm9x9  dann bitte nochmal das client.log senden

**Comment by j-dimension** [comment]
> es liegt noch in Postausgang.

Nicht gut. Laut BRAK müssen Nachrichten an ein EGVP danach noch "sonderbehandelt" werden, damit sie vom Postausgang auch gesendet werden. Ebenfalls lt. BRAK solle man auf einen Beginn der Empfänger-SafeID prüfen ("de.justiz"). Das ist bei Dir aber nicht der Fall ("govello").

Für mich ist unklar was "de.justiz" und "govello"-SafeIDs inhaltlich voneinander unterscheidet.

**Comment by stm9x9** [comment]
im beA-Web war es eben auch ganz kurz im Postausgang und ist dann in gesendet gewechselt. Aber 

a) sieht das komisch aus:

da bei erstellt von steht meine ID statt mein Name

![image](https://user-images.githubusercontent.com/29924198/65467519-e663b980-de61-11e9-86ee-f2acf0bc0ce5.png)

aber ansonsten ist alles da, einschließlich Anhang

b) in j-l dauerte es deutlich länger - trotz aktualisieren - bis es in gesendet lag.Und auch da der NULL-Fehler

![image](https://user-images.githubusercontent.com/29924198/65467658-48bcba00-de62-11e9-827c-1a1093afaf17.png)

**Comment by stm9x9** [comment]
govello sind AFAIK "ältere" Adressen von welchen die früher schon mitgemacht haben

**Comment by j-dimension** [comment]
> govello sind AFAIK "ältere" Adressen von welchen die früher schon mitgemacht haben

Stimmt. Lt. Recherche Postfächer die älter sind als Aug '17.

**Comment by stm9x9** [comment]
äh ach so, den Test eben, den hab ich nicht ans SG Berlin gemacht (mit govello) sondern an ein Test-Gericht. Das hat schon eine safe-sp1-1463554151551-01611411. 

de.justiz hab ich noch nie aktiv bemerkt

**Comment by j-dimension** [comment]
Scheint hier dokumentiert zu sein: https://egvp.justiz.de/Drittprodukte/SAFE_Abbildungsvorschrift_SAFE_ID_V2.pdf

Ich prüfe nun also noch auf safe-sp1- und safe-prod-

**Comment by j-dimension** [comment]
@stm9x9 es gibt ein Log-Statement wenn das Öffnen der Nachricht fehlschlägt - wäre fein wenn ich das bekommen könnte.  Danke!

**Comment by stm9x9** [comment]
So, nochmal um 00:40 versandt. 10 min gewartet. Nix passiert. Es bleibt im Postausgang. 

In dem Augenblick, in dem ich mich im web einlogge, sehe ich es kurz im Ausgang und dann gleich in gesendet. (in j-l dauert es gerade noch an, das anzuzeigen)

Aber!

laut Zustellnachricht:

![image](https://user-images.githubusercontent.com/29924198/65469005-27f66380-de66-11e9-8088-fc95d54b178f.png)

Da ist es angeblich sofort zugegangen.

Laut Journal ist aber nochmal was um 00:50 passiert:

![image](https://user-images.githubusercontent.com/29924198/65469022-3a709d00-de66-11e9-9ddc-bb80192ae353.png)

Das kann aber natürlich auch nur das "in versendet" geschoben bedeuten.

**Comment by j-dimension** [comment]
@stm9x9 ich habe eben eine neue wrapper.jar hochgeladen. gern mit der nochmal testen. 

Und wenn der Fehler beim Öffnen noch kommt: bitte client.log senden.

**Comment by stm9x9** [comment]
und hier das Log vom Versand plus ein paar Minuten

2019-09-24 00:40:25,821 ERROR [org.jlawyer.bea.BeaWrapper] Unable to get identity safe-sp1-1463554261783-016114116
de.brak.bea.application.dto.soap.types5.BeaFault: 0207 - There is no data for given Identity, because of the IdentitySourceType!
	at sun.reflect.GeneratedConstructorAccessor70.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.sun.xml.internal.ws.fault.SOAPFaultBuilder.createException(SOAPFaultBuilder.java:135)
	at com.sun.xml.internal.ws.client.sei.StubHandler.readResponse(StubHandler.java:238)
	at com.sun.xml.internal.ws.db.DatabindingImpl.deserializeResponse(DatabindingImpl.java:189)
	at com.sun.xml.internal.ws.db.DatabindingImpl.deserializeResponse(DatabindingImpl.java:276)
	at com.sun.xml.internal.ws.client.sei.SyncMethodHandler.invoke(SyncMethodHandler.java:104)
	at com.sun.xml.internal.ws.client.sei.SyncMethodHandler.invoke(SyncMethodHandler.java:77)
	at com.sun.xml.internal.ws.client.sei.SEIStub.invoke(SEIStub.java:147)
	at com.sun.proxy.$Proxy56.getIdentityData(Unknown Source)
	at org.jlawyer.bea.BeaWrapper.getIdentity(BeaWrapper.java:917)
	at com.jdimension.jlawyer.client.bea.BeaAccess.getIdentity(BeaAccess.java:935)
	at com.jdimension.jlawyer.client.bea.SendBeaMessageDialog$RecipientsActionListener.actionPerformed(SendBeaMessageDialog.java:1928)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.JToggleButton$ToggleButtonModel.setPressed(JToggleButton.java:308)
	at javax.swing.AbstractButton.doClick(AbstractButton.java:376)
	at javax.swing.plaf.basic.BasicMenuItemUI.doClick(BasicMenuItemUI.java:842)
	at javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(BasicMenuItemUI.java:886)
	at java.awt.Component.processMouseEvent(Component.java:6539)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6304)
	at java.awt.Container.processEvent(Container.java:2239)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2297)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4904)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4535)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4476)
	at java.awt.Container.dispatchEventImpl(Container.java:2283)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:760)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:84)
	at java.awt.EventQueue$4.run(EventQueue.java:733)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:730)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
2019-09-24 00:41:02,776 ERROR [com.jdimension.jlawyer.client.bea.BeaMessageContentUI] Error getting contents of IMAP message
java.lang.NullPointerException
	at java.util.Calendar.setTime(Calendar.java:1770)
	at java.text.SimpleDateFormat.format(SimpleDateFormat.java:943)
	at java.text.SimpleDateFormat.format(SimpleDateFormat.java:936)
	at java.text.DateFormat.format(DateFormat.java:345)
	at com.jdimension.jlawyer.client.bea.BeaMessageContentUI.setMessageImpl(BeaMessageContentUI.java:837)
	at com.jdimension.jlawyer.client.bea.BeaMessageContentUI.setMessage(BeaMessageContentUI.java:816)
	at com.jdimension.jlawyer.client.editors.documents.viewer.BeaPanel.setMessage(BeaPanel.java:692)
	at com.jdimension.jlawyer.client.editors.documents.viewer.BeaPanel.showContent(BeaPanel.java:736)
	at com.jdimension.jlawyer.client.editors.documents.viewer.DocumentViewerFactory.getDocumentViewer(DocumentViewerFactory.java:755)
	at com.jdimension.jlawyer.client.editors.documents.LoadDocumentPreviewThread.run(LoadDocumentPreviewThread.java:730)
	at java.lang.Thread.run(Thread.java:748)
2019-09-24 00:41:57,682 WARN  [org.jlawyer.bea.BeaWrapper] Message metadata is null - unable to check eEB requested flag
2019-09-24 00:41:57,682 WARN  [org.jlawyer.bea.BeaWrapper] Message metadata is null - unable to check eEB requested flag
2019-09-24 00:41:57,682 WARN  [org.jlawyer.bea.BeaWrapper] Message metadata is null - unable to check eEB requested flag
2019-09-24 00:41:57,682 WARN  [org.jlawyer.bea.BeaWrapper] Message metadata is null - unable to check eEB requested flag
2019-09-24 00:41:57,682 WARN  [org.jlawyer.bea.BeaWrapper] Message metadata is null - unable to check eEB requested flag
2019-09-24 00:41:57,682 WARN  [org.jlawyer.bea.BeaWrapper] Message metadata is null - unable to check eEB requested flag
2019-09-24 00:41:57,682 WARN  [org.jlawyer.bea.BeaWrapper] Message metadata is null - unable to check eEB requested flag
2019-09-24 00:41:57,682 WARN  [org.jlawyer.bea.BeaWrapper] Message metadata is null - unable to check eEB requested flag
2019-09-24 00:41:57,683 WARN  [org.jlawyer.bea.BeaWrapper] Message metadata is null - unable to check eEB requested flag
2019-09-24 00:41:57,683 WARN  [org.jlawyer.bea.BeaWrapper] Message metadata is null - unable to check eEB requested flag
2019-09-24 00:41:57,683 WARN  [org.jlawyer.bea.BeaWrapper] Message metadata is null - unable to check eEB requested flag
2019-09-24 00:41:57,683 WARN  [org.jlawyer.bea.BeaWrapper] Message metadata is null - unable to check eEB requested flag
2019-09-24 00:41:57,683 WARN  [org.jlawyer.bea.BeaWrapper] Message metadata is null - unable to check eEB requested flag
2019-09-24 00:41:57,683 WARN  [org.jlawyer.bea.BeaWrapper] Message metadata is null - unable to check eEB requested flag
2019-09-24 00:41:57,683 WARN  [org.jlawyer.bea.BeaWrapper] Message metadata is null - unable to check eEB requested flag
2019-09-24 00:41:57,683 WARN  [org.jlawyer.bea.BeaWrapper] Message metadata is null - unable to check eEB requested flag
2019-09-24 00:41:57,683 WARN  [org.jlawyer.bea.BeaWrapper] Message metadata is null - unable to check eEB requested flag
2019-09-24 00:41:57,683 WARN  [org.jlawyer.bea.BeaWrapper] Message metadata is null - unable to check eEB requested flag
2019-09-24 00:41:57,683 WARN  [org.jlawyer.bea.BeaWrapper] Message metadata is null - unable to check eEB requested flag
2019-09-24 00:41:57,683 WARN  [org.jlawyer.bea.BeaWrapper] Message metadata is null - unable to check eEB requested flag
2019-09-24 00:41:57,683 WARN  [org.jlawyer.bea.BeaWrapper] Message metadata is null - unable to check eEB requested flag
2019-09-24 00:41:57,683 WARN  [org.jlawyer.bea.BeaWrapper] Message metadata is null - unable to check eEB requested flag
2019-09-24 00:41:57,683 WARN  [org.jlawyer.bea.BeaWrapper] Message metadata is null - unable to check eEB requested flag
2019-09-24 00:41:57,683 WARN  [org.jlawyer.bea.BeaWrapper] Message metadata is null - unable to check eEB requested flag
2019-09-24 00:41:57,683 WARN  [org.jlawyer.bea.BeaWrapper] Message metadata is null - unable to check eEB requested flag
2019-09-24 00:41:57,684 WARN  [org.jlawyer.bea.BeaWrapper] Message metadata is null - unable to check eEB requested flag
2019-09-24 00:41:57,684 WARN  [org.jlawyer.bea.BeaWrapper] Message metadata is null - unable to check eEB requested flag
2019-09-24 00:41:57,684 WARN  [org.jlawyer.bea.BeaWrapper] Message metadata is null - unable to check eEB requested flag
2019-09-24 00:41:57,684 WARN  [org.jlawyer.bea.BeaWrapper] Message metadata is null - unable to check eEB requested flag
2019-09-24 00:41:57,684 WARN  [org.jlawyer.bea.BeaWrapper] Message metadata is null - unable to check eEB requested flag
2019-09-24 00:41:57,684 WARN  [org.jlawyer.bea.BeaWrapper] Message metadata is null - unable to check eEB requested flag
2019-09-24 00:41:57,684 WARN  [org.jlawyer.bea.BeaWrapper] Message metadata is null - unable to check eEB requested flag
2019-09-24 00:41:57,684 WARN  [org.jlawyer.bea.BeaWrapper] Message metadata is null - unable to check eEB requested flag
2019-09-24 00:41:57,684 WARN  [org.jlawyer.bea.BeaWrapper] Message metadata is null - unable to check eEB requested flag
2019-09-24 00:41:57,684 WARN  [org.jlawyer.bea.BeaWrapper] Message metadata is null - unable to check eEB requested flag
2019-09-24 00:41:57,684 WARN  [org.jlawyer.bea.BeaWrapper] Message metadata is null - unable to check eEB requested flag
2019-09-24 00:41:57,684 WARN  [org.jlawyer.bea.BeaWrapper] Message metadata is null - unable to check eEB requested flag
2019-09-24 00:41:57,685 WARN  [org.jlawyer.bea.BeaWrapper] Message metadata is null - unable to check eEB requested flag
2019-09-24 00:41:57,685 WARN  [org.jlawyer.bea.BeaWrapper] Message metadata is null - unable to check eEB requested flag
2019-09-24 00:41:57,685 WARN  [org.jlawyer.bea.BeaWrapper] Message metadata is null - unable to check eEB requested flag
2019-09-24 00:41:57,685 WARN  [org.jlawyer.bea.BeaWrapper] Message metadata is null - unable to check eEB requested flag
2019-09-24 00:41:57,685 WARN  [org.jlawyer.bea.BeaWrapper] Message metadata is null - unable to check eEB requested flag
2019-09-24 00:41:57,686 WARN  [org.jlawyer.bea.BeaWrapper] Message metadata is null - unable to check eEB requested flag
2019-09-24 00:41:57,686 WARN  [org.jlawyer.bea.BeaWrapper] Message metadata is null - unable to check eEB requested flag
2019-09-24 00:41:57,686 WARN  [org.jlawyer.bea.BeaWrapper] Message metadata is null - unable to check eEB requested flag
2019-09-24 00:41:57,686 WARN  [org.jlawyer.bea.BeaWrapper] Message metadata is null - unable to check eEB requested flag
2019-09-24 00:41:57,686 WARN  [org.jlawyer.bea.BeaWrapper] Message metadata is null - unable to check eEB requested flag
2019-09-24 00:42:06,139 WARN  [org.jlawyer.bea.BeaWrapper] Message metadata is null - unable to check eEB requested flag
2019-09-24 00:42:10,728 ERROR [com.jdimension.jlawyer.client.bea.BeaMessageContentUI] Error getting contents of IMAP message
java.lang.NullPointerException
	at java.util.Calendar.setTime(Calendar.java:1770)
	at java.text.SimpleDateFormat.format(SimpleDateFormat.java:943)
	at java.text.SimpleDateFormat.format(SimpleDateFormat.java:936)
	at java.text.DateFormat.format(DateFormat.java:345)
	at com.jdimension.jlawyer.client.bea.BeaMessageContentUI.setMessageImpl(BeaMessageContentUI.java:837)
	at com.jdimension.jlawyer.client.bea.BeaMessageContentUI.setMessage(BeaMessageContentUI.java:816)
	at com.jdimension.jlawyer.client.bea.BeaInboxPanel.displayMessage(BeaInboxPanel.java:2037)
	at com.jdimension.jlawyer.client.bea.BeaInboxPanel.tblMailsMouseClicked(BeaInboxPanel.java:1475)
	at com.jdimension.jlawyer.client.bea.BeaInboxPanel.access$1800(BeaInboxPanel.java:753)
	at com.jdimension.jlawyer.client.bea.BeaInboxPanel$16.mouseClicked(BeaInboxPanel.java:1205)
	at java.awt.AWTEventMulticaster.mouseClicked(AWTEventMulticaster.java:270)
	at java.awt.AWTEventMulticaster.mouseClicked(AWTEventMulticaster.java:269)
	at java.awt.Component.processMouseEvent(Component.java:6542)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6304)
	at java.awt.Container.processEvent(Container.java:2239)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2297)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4904)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4544)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4476)
	at java.awt.Container.dispatchEventImpl(Container.java:2283)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:760)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:84)
	at java.awt.EventQueue$4.run(EventQueue.java:733)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:730)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
2019-09-24 00:43:17,828 WARN  [org.jlawyer.bea.BeaWrapper] Message metadata is null - unable to check eEB requested flag
2019-09-24 00:43:17,828 WARN  [org.jlawyer.bea.BeaWrapper] Message metadata is null - unable to check eEB requested flag
2019-09-24 00:43:17,828 WARN  [org.jlawyer.bea.BeaWrapper] Message metadata is null - unable to check eEB requested flag
2019-09-24 00:43:17,828 WARN  [org.jlawyer.bea.BeaWrapper] Message metadata is null - unable to check eEB requested flag
2019-09-24 00:43:17,829 WARN  [org.jlawyer.bea.BeaWrapper] Message metadata is null - unable to check eEB requested flag
2019-09-24 00:43:17,829 WARN  [org.jlawyer.bea.BeaWrapper] Message metadata is null - unable to check eEB requested flag
2019-09-24 00:43:17,829 WARN  [org.jlawyer.bea.BeaWrapper] Message metadata is null - unable to check eEB requested flag
2019-09-24 00:43:17,829 WARN  [org.jlawyer.bea.BeaWrapper] Message metadata is null - unable to check eEB requested flag
2019-09-24 00:43:17,829 WARN  [org.jlawyer.bea.BeaWrapper] Message metadata is null - unable to check eEB requested flag
2019-09-24 00:43:17,829 WARN  [org.jlawyer.bea.BeaWrapper] Message metadata is null - unable to check eEB requested flag
2019-09-24 00:43:17,829 WARN  [org.jlawyer.bea.BeaWrapper] Message metadata is null - unable to check eEB requested flag
2019-09-24 00:43:17,829 WARN  [org.jlawyer.bea.BeaWrapper] Message metadata is null - unable to check eEB requested flag
2019-09-24 00:43:17,829 WARN  [org.jlawyer.bea.BeaWrapper] Message metadata is null - unable to check eEB requested flag
2019-09-24 00:43:17,829 WARN  [org.jlawyer.bea.BeaWrapper] Message metadata is null - unable to check eEB requested flag
2019-09-24 00:43:17,829 WARN  [org.jlawyer.bea.BeaWrapper] Message metadata is null - unable to check eEB requested flag
2019-09-24 00:43:17,830 WARN  [org.jlawyer.bea.BeaWrapper] Message metadata is null - unable to check eEB requested flag
2019-09-24 00:43:17,830 WARN  [org.jlawyer.bea.BeaWrapper] Message metadata is null - unable to check eEB requested flag
2019-09-24 00:43:17,830 WARN  [org.jlawyer.bea.BeaWrapper] Message metadata is null - unable to check eEB requested flag
2019-09-24 00:43:17,830 WARN  [org.jlawyer.bea.BeaWrapper] Message metadata is null - unable to check eEB requested flag
2019-09-24 00:47:52,328 WARN  [org.jlawyer.bea.BeaWrapper] Message metadata is null - unable to check eEB requested flag
2019-09-24 00:47:52,328 WARN  [org.jlawyer.bea.BeaWrapper] Message metadata is null - unable to check eEB requested flag
2019-09-24 00:47:52,328 WARN  [org.jlawyer.bea.BeaWrapper] Message metadata is null - unable to check eEB requested flag
2019-09-24 00:47:52,328 WARN  [org.jlawyer.bea.BeaWrapper] Message metadata is null - unable to check eEB requested flag
2019-09-24 00:47:52,328 WARN  [org.jlawyer.bea.BeaWrapper] Message metadata is null - unable to check eEB requested flag
2019-09-24 00:47:52,328 WARN  [org.jlawyer.bea.BeaWrapper] Message metadata is null - unable to check eEB requested flag
2019-09-24 00:47:52,328 WARN  [org.jlawyer.bea.BeaWrapper] Message metadata is null - unable to check eEB requested flag
2019-09-24 00:47:52,328 WARN  [org.jlawyer.bea.BeaWrapper] Message metadata is null - unable to check eEB requested flag

**Comment by stm9x9** [comment]
> @stm9x9 ich habe eben eine neue wrapper.jar hochgeladen. gern mit der nochmal testen.
> 
> Und wenn der Fehler beim Öffnen noch kommt: bitte client.log senden.

kann ich erst morgen machen. Oder wohl realistisch Mittwoch abend. gn8!

**Comment by j-dimension** [comment]
@stm9x9 Danke, das zuletzt gepostete Log enthielt bereits die gewünschte Information. Ich habe jetzt ebenfalls eine neue client jar hochgeladen. 

Ticket lasse ich bis zur Rückmeldung offen.

An dieser Stelle schonmal vielen Dank für Deine Hilfe!

**Comment by stm9x9** [comment]
So, Neugierde war stärker: Nachricht wurde sofort und sauber versandt und ist auch im viewer lesbar!

und das Journal sieht auch sauber aus.

nur hier steht immer noch meine ID im web statt des Namens (der da steht, wenn ich aus dem Web sende)

![image](https://user-images.githubusercontent.com/29924198/65470483-b0c3ce00-de6b-11e9-94ab-8da82a81cd26.png)

und ich kann keinen Laufzettel abrufen, aber das ist ein anderes Thema oder noch gar nicht implementiert?

Was macht die neue client? Und soll das mit dem unbekannter Teilnehmer so sein/bleiben?

**Comment by j-dimension** [comment]
> Nachricht wurde sofort und sauber versandt und ist auch im viewer lesbar!
Sehr gut, danke.

> hier steht immer noch meine ID im web statt des Namens
Das wird erstmal keine negativen Auswirkungen haben, ich schaue heute abend trotzdem nochmal.

> ich kann keinen Laufzettel abrufen
Ist ein Bug der Schnittstelle - eine KSW kann nur exakt EINMAL die ProcessCards abrufen, und dabei muss das Timing stimmen. Thema bleibt aber auf dem Schirm, sobald eine Korrektur da ist werde ich das einbauen.

> Was macht die neue client?
"Erkennt" fehlerhafte / fehlende Nachrichtenattribute im Viewer der beA-Nachrichten und behandelt sie so, dass eine Darstellung trotzdem gegeben ist. Logging-Erweiterungen.

> Und soll das mit dem unbekannter Teilnehmer so sein/bleiben?
Erstmal kann man so arbeiten - die Ursache für den fehlschlagenden Abruf der Identitäten muss ich mit der BRAK diskutieren. Kann einen "kleinen" Moment dauern.

**Comment by stm9x9** [comment]
> > ich kann keinen Laufzettel abrufen
> 
> Ist ein Bug der Schnittstelle - eine KSW kann nur exakt EINMAL die ProcessCards abrufen, und dabei muss das Timing stimmen. Thema bleibt aber auf dem Schirm, sobald eine Korrektur da ist werde ich das einbauen.

Ich konnte bislang kein einziges Mal eine ProcessCard abrufen!?

> Erstmal kann man so arbeiten - die Ursache für den fehlschlagenden Abruf der Identitäten muss ich mit der BRAK diskutieren. Kann einen "kleinen" Moment dauern.

;-)

**Comment by stm9x9** [comment]
JFTR: https://github.com/jlawyerorg/j-lawyer-org/issues/352#issuecomment-534304254 besteht auch immer noch mit dem neuen wrapper.
