### ISSUE TITLE
beA: vor Senden prüfen ob Empfänger angegeben wurden

### ISSUE THREAD

**Issue by j-dimension** [jlawyerorg/j-lawyer-org#440]
```
2019-10-29 14:52:47,472 ERROR [org.jlawyer.bea.BeaWrapper] Could not send message
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(ArrayList.java:657)
	at java.util.ArrayList.get(ArrayList.java:433)
	at org.jlawyer.bea.BeaWrapper.sendMessage(BeaWrapper.java:1485)
	at com.jdimension.jlawyer.client.bea.BeaAccess.sendMessage(BeaAccess.java:1040)
	at com.jdimension.jlawyer.client.bea.SendBeaMessageAction.execute(SendBeaMessageAction.java:789)
	at com.jdimension.jlawyer.client.processing.ProgressableAction$4.run(ProgressableAction.java:770)
```

**Comment by j-dimension** [comment]
@RasimT
