### ISSUE TITLE
[bea] Fehler beim Öffen eines Ordners

### ISSUE THREAD

**Issue by stm9x9** [jlawyerorg/j-lawyer-org#550]
![image](https://user-images.githubusercontent.com/29924198/71593132-168eb880-2b33-11ea-9450-da6060e28c73.png)

Gibt es ein Timeout für die beA-Verbindung? Ich hatte es im Hintergrund so eine halbe Stunde offen und bekomme beim Öffnen eines neuen Ordners den Fehler oben.

... wie ich gerade sehe, aber nicht bei allen Ordnern. Ein System erkenne ich leider nicht.

**Comment by j-dimension** [comment]
Der BeaFault 9999 ist in der Regel ein Problem seitens der Infrastruktur bei der BRAK. Genaueres könnte ich evtl. aus dem client.log rauslesen.

Einen Timeout gibt es immer für http(s)-Kommunikation, der ist beim beA aber sicherlich relativ hoch eingestellt. 30min könnte hinkommen.

**Comment by stm9x9** [comment]
OK ein Timeout-Problem ist es definitiv nicht. Auch nach einem Neustart kommt der Fehler. Immer bei denselben Ordern. Andere wiederum gehen. per beAweb und mit Karte kann ich auf alle Ordner zugreifen.

**Comment by stm9x9** [comment]
client.log finde ich wo? in C:\Program Files\j-lawyer-client ist nichts.

**Comment by j-dimension** [comment]
https://www.j-lawyer.org/?topic=wo-findet-man-die-fehlerprotokolle-des-j-lawyer-org-servers-und-clients

**Comment by stm9x9** [comment]
per PN

**Comment by j-dimension** [comment]
Muss ich an die BRAK weitergeben. Ich rufe einfach nur "gib mir Liste von Nachrichten-Headern für Ordner x". Die ID des Ordners ist der einzige Parameter, eine Fehlbedienung der Schnittstelle somit ausgeschlossen. Wird dann quittiert mit

```
2020-01-01 21:22:05,596 ERROR [org.jlawyer.bea.BeaWrapper] unable to determine number of unread messages for folder Burgsdorfstr
org.jlawyer.bea.BeaWrapperException: de.brak.bea.application.dto.soap.types5.BeaFault: 9999 - General error processing request.
	at org.jlawyer.bea.BeaWrapper.getFolderOverview(BeaWrapper.java:1407)
	at org.jlawyer.bea.BeaWrapper.getFolderStructure(BeaWrapper.java:1192)
	at com.jdimension.jlawyer.client.bea.BeaAccess.getFolderStructure(BeaAccess.java:933)
	at com.jdimension.jlawyer.client.bea.BeaInboxPanel.refreshFolders(BeaInboxPanel.java:919)
	at com.jdimension.jlawyer.client.bea.BeaInboxPanel$31$1.run(BeaInboxPanel.java:2433)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: de.brak.bea.application.dto.soap.types5.BeaFault: 9999 - General error processing request.
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.sun.xml.internal.ws.fault.SOAPFaultBuilder.createException(SOAPFaultBuilder.java:135)
	at com.sun.xml.internal.ws.client.sei.StubHandler.readResponse(StubHandler.java:238)
	at com.sun.xml.internal.ws.db.DatabindingImpl.deserializeResponse(DatabindingImpl.java:189)
	at com.sun.xml.internal.ws.db.DatabindingImpl.deserializeResponse(DatabindingImpl.java:276)
	at com.sun.xml.internal.ws.client.sei.SyncMethodHandler.invoke(SyncMethodHandler.java:104)
	at com.sun.xml.internal.ws.client.sei.SyncMethodHandler.invoke(SyncMethodHandler.java:77)
	at com.sun.xml.internal.ws.client.sei.SEIStub.invoke(SEIStub.java:147)
	at com.sun.proxy.$Proxy50.getFolderOverview(Unknown Source)
	at org.jlawyer.bea.BeaWrapper.getFolderOverview(BeaWrapper.java:1244)
```

und somit leider völlig ohne sinnhaftige Detailinformationen.

**Comment by j-dimension** [comment]
Könnte mit #670 zumindest dahingehend robuster laufen, dass das Laden weiterläuft, wenn ein Fehler auftritt.

Wird hier auf ein "Fremdpostfach" zugegriffen?

**Comment by stm9x9** [comment]
ja, ist ein Fremdpostfach

**Comment by j-dimension** [comment]
Ich mache demnächst ein neues Vorab-Release. Wäre damit nochmal testbar.
