### ISSUE TITLE
1.12: Vorlagen bei Versand beA - Fehler null

### ISSUE THREAD

**Issue by Maz111111** [jlawyerorg/j-lawyer-org#736]
Wenn ich unter 1.12 im beA meine Vorlagen nutzen will erhalte ich:

![image](https://user-images.githubusercontent.com/53520581/81501595-8d09a700-92d9-11ea-9ff8-30a435bc156d.png)

ich habe es jetzt mehrfach versucht und konnte keinen Fehler bei mir finden.

**Comment by j-dimension** [comment]
Bitte mal das client.log per Email schicken.

**Comment by j-dimension** [comment]
Neuen Clientinstaller bereitgestellt.

**Comment by j-dimension** [comment]
Ursache: 

```
java.lang.NullPointerException
	at com.jdimension.jlawyer.client.editors.files.PartiesPanelEntry.<init>(PartiesPanelEntry.java:687)
	at com.jdimension.jlawyer.client.editors.files.PartiesPanelEntry.clone(PartiesPanelEntry.java:713)
	at com.jdimension.jlawyer.client.editors.files.PartiesPanel.getSelectedParties(PartiesPanel.java:969)
	at com.jdimension.jlawyer.client.bea.SendBeaMessageDialog.cmbTemplatesActionPerformed(SendBeaMessageDialog.java:2006)
	at com.jdimension.jlawyer.client.bea.SendBeaMessageDialog.access$3000(SendBeaMessageDialog.java:736)
	at com.jdimension.jlawyer.client.bea.SendBeaMessageDialog$30.actionPerformed(SendBeaMessageDialog.java:1668)
```
