### ISSUE TITLE
Rechnung lässt sich nicht erstellen

### ISSUE THREAD

**Issue by iradraconis** [jlawyerorg/j-lawyer-org#897]
Folgende Fehlermeldung erhalte ich schon den ganzen Tag beim Versuch, eine Rechnung über das RVG Plugin zu erstellen. Ich klicke im Plugin auf "Dokument" erstellen, und wähle dann die Rechnungsvorlage aus. Dann kommt diese Meldung. 

Es ging vorher noch. Irgendwann habe ich an den Einstellungen für die Formatierung rumgespielt, und seit dem geht gar nix mehr. Die Tabellenlinien habe ich allerdings noch eingeblendet (dort gibt es einen Hinweis, dass es Probleme mit der Einstellung gibt).

![IMG_4356](https://user-images.githubusercontent.com/71747937/94729494-088bf380-0362-11eb-95a3-27232a835f3f.jpeg)

**Comment by j-dimension** [comment]
Bitte mal die Vorlage per E-Mail zur Verfügung stellen - danke!

**Comment by j-dimension** [comment]
Wird "RVG Wertgebühren" als Plugin genutzt? Welche Einträge werden konkret dort gemacht? Geht es in **gar keiner** Konstellation?

**Comment by iradraconis** [comment]
Der Rechner für die Pauschalgebühr und der Rechner für Strafrecht wurden benutzt. 
Ich habe im laufe des Tages mal die Farbe der Linien angepasst. Jetzt aber wieder auf schwarz stehen.  Vielleicht hilft das beim Eingrenzen.

**Comment by iradraconis** [comment]
Achja, Einträge waren dann zum Test eher zufällig. Brutto pausch 150,- inkl. 16 % umst zum Beispiel führten auch zum Absturz

**Comment by j-dimension** [comment]
Ich bekomme das hier nicht reproduziert. 

Bitte mal die Einstellungen und dann Administratorkonsole öffnen und die Ausgabe von 

`getsetting plugins.global.tableproperties.table.lines.color`

hier posten. Danke!

**Comment by iradraconis** [comment]
![IMG_0729](https://user-images.githubusercontent.com/71747937/94736276-40983400-036c-11eb-896d-ef3fb95c361e.jpg)
![IMG_0730](https://user-images.githubusercontent.com/71747937/94736296-468e1500-036c-11eb-890c-76946ab9b169.jpg)

**Comment by iradraconis** [comment]
auf dem MacBook ging es gerade. Auf meinem Büro PC war heute nix zu machen und auf meinem iMac auch nicht.

**Comment by j-dimension** [comment]
Und hat das Zurückstellen auf schwarze Linienfarbe etwas bewirkt? Auch mit den Einstellungen oben kann ich den Fehler nicht provozieren.

**Comment by iradraconis** [comment]
ich habe jetzt gerade nichts geändert, ausser den Client zu wechseln

**Comment by j-dimension** [comment]
Dann bitte morgen nochmal im Büro prüfen und Rückmeldung geben. Dann wäre die These jetzt, dass es irgendetwas mit der Linienfarbe zu tun hat(?). Anhand des Logs kann ich das aber nicht rauslesen. Dort wird beim Hinzufügen einer Spalte auf eine ungültige Zellposition zugegriffen.

**Comment by iradraconis** [comment]
Prüfe das Morgen, sobald ich dazu komme und gebe dann Rückmeldung

**Comment by j-dimension** [comment]
Ticket bleibt offen.

**Comment by j-dimension** [comment]
```
com.jdimension.jlawyer.services.ArchiveFileServiceRemote.addDocumentFromTemplate(java.lang.String,java.lang.String,org.jlawyer.data.tree.GenericNode,java.lang.String,java.util.Hashtable,java.lang.String) throws java.lang.Exception: javax.ejb.EJBException: java.lang.IllegalArgumentException: index should be nonnegative integer.
	at org.jboss.as.ejb3.tx.CMTTxInterceptor.invokeInOurTx(CMTTxInterceptor.java:246)
	at org.jboss.as.ejb3.tx.CMTTxInterceptor.required(CMTTxInterceptor.java:362)
	at org.jboss.as.ejb3.tx.CMTTxInterceptor.processInvocation(CMTTxInterceptor.java:144)
	at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:422)
	at org.jboss.invocation.InterceptorContext$Invocation.proceed(InterceptorContext.java:509)
	at org.jboss.weld.module.ejb.AbstractEJBRequestScopeActivationInterceptor.aroundInvoke(AbstractEJBRequestScopeActivationInterceptor.java:81)
	at org.jboss.as.weld.ejb.EjbRequestScopeActivationInterceptor.processInvocation(EjbRequestScopeActivationInterceptor.java:89)
	at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:422)
	at org.jboss.as.ejb3.component.interceptors.CurrentInvocationContextInterceptor.processInvocation(CurrentInvocationContextInterceptor.java:41)
	at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:422)
	at org.jboss.as.ejb3.component.invocationmetrics.WaitTimeInterceptor.processInvocation(WaitTimeInterceptor.java:47)
	at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:422)
	at org.jboss.as.ejb3.security.AuthorizationInterceptor.processInvocation(AuthorizationInterceptor.java:138)
	at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:422)
	at org.jboss.as.ejb3.security.SecurityContextInterceptor.processInvocation(SecurityContextInterceptor.java:100)
	at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:422)
	at org.jboss.as.ejb3.deployment.processors.StartupAwaitInterceptor.processInvocation(StartupAwaitInterceptor.java:22)
	at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:422)
	at org.jboss.as.ejb3.component.interceptors.ShutDownInterceptorFactory$1.processInvocation(ShutDownInterceptorFactory.java:64)
	at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:422)
	at org.jboss.as.ejb3.deployment.processors.EjbSuspendInterceptor.processInvocation(EjbSuspendInterceptor.java:57)
	at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:422)
	at org.jboss.as.ejb3.component.interceptors.LoggingInterceptor.processInvocation(LoggingInterceptor.java:67)
	at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:422)
	at org.jboss.as.ee.component.NamespaceContextInterceptor.processInvocation(NamespaceContextInterceptor.java:50)
	at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:422)
	at org.jboss.invocation.ContextClassLoaderInterceptor.processInvocation(ContextClassLoaderInterceptor.java:60)
	at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:422)
	at org.jboss.invocation.InterceptorContext.run(InterceptorContext.java:438)
	at org.wildfly.security.manager.WildFlySecurityManager.doChecked(WildFlySecurityManager.java:618)
	at org.jboss.invocation.AccessCheckingInterceptor.processInvocation(AccessCheckingInterceptor.java:57)
	at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:422)
	at org.jboss.invocation.ChainedInterceptor.processInvocation(ChainedInterceptor.java:53)
	at org.jboss.as.ee.component.ViewService$View.invoke(ViewService.java:198)
	at org.wildfly.security.auth.server.SecurityIdentity.runAsFunctionEx(SecurityIdentity.java:406)
	at org.jboss.as.ejb3.remote.AssociationImpl.invokeWithIdentity(AssociationImpl.java:565)
	at org.jboss.as.ejb3.remote.AssociationImpl.invokeMethod(AssociationImpl.java:546)
	at org.jboss.as.ejb3.remote.AssociationImpl.lambda$receiveInvocationRequest$0(AssociationImpl.java:197)
	at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
	at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:1982)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1486)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1377)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalArgumentException: index should be nonnegative integer.
	at org.odftoolkit.simple.table.Row.getCellByIndex(Row.java:370)
	at org.odftoolkit.simple.table.Table.appendColumn(Table.java:1670)
	at com.jdimension.jlawyer.documents.LibreOfficeAccess.setPlaceHolders(LibreOfficeAccess.java:870)
	at com.jdimension.jlawyer.services.ArchiveFileService.addDocumentFromTemplate(ArchiveFileService.java:3533)
```

**Comment by Linkki2021** [comment]
Wir haben gegenwärtig das gleiche Problem, auch die Fehlermeldung. Das Ganze kommt, wenn eine Vorlage mit einzelliger Tabelle inkl. Platzhalter {{TABELLE_1}} in Word als odt gespeichert wird (Plugin RVG-Wertegebühren). Welche Office-Suite in in j-lawyer ausgewählt ist spielt mE keine Rolle.

Als Zusatzinfo: wenn man den integer-Fehler mit "ok" bestätigt und das Dokument dann nochmal erstellen möchte kommt nicht nochmal der gleiche Fehler, sondern der Hinweis, dass das Dokument bereits existiert und ein anderer Name gewählt werden soll. In den Dokumenten taucht das angeblich existierende Dokument allerdings nicht auf, und auch in den tmp-documents auf dem Laufwerk finde ich es nicht.

**Comment by j-dimension** [comment]
> Wir haben gegenwärtig das gleiche Problem, auch die Fehlermeldung. Das Ganze kommt, wenn eine Vorlage mit einzelliger Tabelle inkl. Platzhalter {{TABELLE_1}} in Word als odt gespeichert wird (Plugin RVG-Wertegebühren). Welche Office-Suite in in j-lawyer ausgewählt ist spielt mE keine Rolle.

Hilft der Workaround mit dem Speichern der Vorlage via LibreOffice?



> In den Dokumenten taucht das angeblich existierende Dokument allerdings nicht auf, und auch in den tmp-documents auf dem Laufwerk finde ich es nicht.

Auch nicht nach Neuladen der Akte?

**Comment by Linkki2021** [comment]
> > Wir haben gegenwärtig das gleiche Problem, auch die Fehlermeldung. Das Ganze kommt, wenn eine Vorlage mit einzelliger Tabelle inkl. Platzhalter {{TABELLE_1}} in Word als odt gespeichert wird (Plugin RVG-Wertegebühren). Welche Office-Suite in in j-lawyer ausgewählt ist spielt mE keine Rolle.
> 
> Hilft der Workaround mit dem Speichern der Vorlage via LibreOffice?

So tief bin ich da nicht rein, da die Vorlage ein paar grafische Details aufweist, die es mir vermutlich durcheinander bringt, wenn ich alles markiere, kopiere und neueinfüge. Wenn ich aber Dokumente via LibreOffice erstelle, dann geht alles. Unabhängig davon haben wir aber für den Moment einen Workaround für die Erstellung von RVG-Rechnungen gefunden. Das Ganze diente von meiner Seite als Verifizierung der weiter oben im Thread genannten Arbeitsthese.
> 
> > In den Dokumenten taucht das angeblich existierende Dokument allerdings nicht auf, und auch in den tmp-documents auf dem Laufwerk finde ich es nicht.
> 
> Auch nicht nach Neuladen der Akte?

Nein. Ich konnte zumindest nichts finden, habe es gerade nochmal geprüft.

**Comment by j-dimension** [comment]
Problem scheint sehr sporadisch aufzutreten und liegt außerhalb des j-lawyer Codes. Ich werde in 2.2 auf die neueste Bibliothekenversion für die ODT-Bearbeitung wechseln, in der Hoffnung dass es hilft. Dieses Upgrade hat bereits ein eigenes Ticket.
