### ISSUE TITLE
[e-mail] StartTLS und/oder Portangabe auch bei imap und pop3 zulassen

### ISSUE THREAD

**Issue by Wurzelkoch** [jlawyerorg/j-lawyer-org#937]
Der Mailprovider, den ich gern nutzen würde für die mit j-lawyer verknüpfte Mailadresse, verlangt u.a. folgende Konfiguration:

Eigenschaft | Wert
-- | --
Verschlüsselung | STARTTLS
POP3-Port | 110 (STARTTLS)
IMAP-Port | 143 (STARTTLS)
SMTP-Port | 587 (STARTTLS)
SMTP-Authentifizierung | AUTH (Plain) / Passwort normal

In j-lawyer kann ich aber nur für smtp STARTTLS explizit auswählen und den Port angeben, für imap/pop3 gibt es nur das Häkchen "SSL".
Während es mit Mailadressen anderer Provider funktioniert, bekomme ich bei dem Account, den ich nutzen möchte, folgende Fehlermeldung: `Keine Verbindung zum Mailserver: Remote host closed connection during handshake` und ich vermute, dass das an dieser Einstellung liegt.

Relevante Teile des client.log:
```
2020-11-12 19:34:40,134 ERROR [com.jdimension.jlawyer.client.mail.EmailInboxPanel] Error connecting to server mail.xxxxxx.org
javax.mail.MessagingException: Remote host closed connection during handshake;
  nested exception is:
        javax.net.ssl.SSLHandshakeException: Remote host closed connection during handshake
        at com.sun.mail.imap.IMAPStore.protocolConnect(IMAPStore.java:670)
        at javax.mail.Service.connect(Service.java:295)
        at javax.mail.Service.connect(Service.java:176)
        at com.jdimension.jlawyer.client.mail.EmailInboxPanel.connect(EmailInboxPanel.java:889)
        at com.jdimension.jlawyer.client.mail.EmailInboxPanel.refreshFolders(EmailInboxPanel.java:947)
        at com.jdimension.jlawyer.client.mail.EmailInboxPanel.cmdRefreshActionPerformed(EmailInboxPanel.java:1500)
        at com.jdimension.jlawyer.client.mail.EmailInboxPanel.access$3200(EmailInboxPanel.java:749)
        at com.jdimension.jlawyer.client.mail.EmailInboxPanel$26.actionPerformed(EmailInboxPanel.java:1457)
        at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
        at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
        at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
        at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
        at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
        at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:289)
        at java.awt.Component.processMouseEvent(Component.java:6539)
        at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
        at java.awt.Component.processEvent(Component.java:6304)
        at java.awt.Container.processEvent(Container.java:2239)
        at java.awt.Component.dispatchEventImpl(Component.java:4889)
        at java.awt.Container.dispatchEventImpl(Container.java:2297)
        at java.awt.Component.dispatchEvent(Component.java:4711)
        at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4904)
        at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4535)
        at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4476)
        at java.awt.Container.dispatchEventImpl(Container.java:2283)
        at java.awt.Window.dispatchEventImpl(Window.java:2746)
        at java.awt.Component.dispatchEvent(Component.java:4711)
        at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:760)
        at java.awt.EventQueue.access$500(EventQueue.java:97)
        at java.awt.EventQueue$3.run(EventQueue.java:709)
        at java.awt.EventQueue$3.run(EventQueue.java:703)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:84)
        at java.awt.EventQueue$4.run(EventQueue.java:733)
        at java.awt.EventQueue$4.run(EventQueue.java:731)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
        at java.awt.EventQueue.dispatchEvent(EventQueue.java:730)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
        at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
        at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: javax.net.ssl.SSLHandshakeException: Remote host closed connection during handshake
        at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:994)
        at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1367)
        at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1395)
        at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1379)
        at com.sun.mail.util.SocketFetcher.configureSSLSocket(SocketFetcher.java:548)
        at com.sun.mail.util.SocketFetcher.createSocket(SocketFetcher.java:352)
        at com.sun.mail.util.SocketFetcher.getSocket(SocketFetcher.java:233)
        at com.sun.mail.iap.Protocol.<init>(Protocol.java:113)
        at com.sun.mail.imap.protocol.IMAPProtocol.<init>(IMAPProtocol.java:111)
        at com.sun.mail.imap.IMAPStore.protocolConnect(IMAPStore.java:637)
        ... 44 more
Caused by: java.io.EOFException: SSL peer shut down incorrectly
        at sun.security.ssl.InputRecord.read(InputRecord.java:505)
        at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:975)
        ... 53 more
2020-11-12 19:34:58,932 ERROR [com.jdimension.jlawyer.client.mail.EmailInboxPanel] java.lang.IllegalStateException: Not connected
```

**Comment by j-dimension** [comment]
Was ist das für ein Mailprovider?

**Comment by Wurzelkoch** [comment]
https://systemausfall.org/wikis/hilfe/Email/Hilfe

**Comment by j-dimension** [comment]
Sorry, aber das SSL-Setup dieses Anbieters ist kaputt. Abgelaufene Root-Zerts, falsche Hostnamen (mx1 statt mail), ...

![grafik](https://user-images.githubusercontent.com/3729754/98998152-fa6eec80-2535-11eb-9b08-533d34f3d4f7.png)

**Comment by j-dimension** [comment]
Die StartTLS-Konfigurationen könnte man explizit in den Einstellungen anbieten, sind hier aber m.E. nicht das Problem.

**Comment by Wurzelkoch** [comment]
> Sorry, aber das SSL-Setup dieses Anbieters ist kaputt. Abgelaufene Root-Zerts, falsche Hostnamen (mx1 statt mail), ...

Mit Thunderbird funktioniert's, kann aber auch an einem nicht so richtig hohen Sicherheitsstandard von Thunderbird liegen. Ich hab mal da um nen fix gebeten, und meld mich nochmal, ob's hilft.

**Comment by j-dimension** [comment]
Hat Thunderbird eine Zertifikatswarnung angezeigt, die bestätigt werden musste?

**Comment by Wurzelkoch** [comment]
Grad nochmal mit einem frischen Thunderbird getestet: Nein.

**Comment by Dickmaulruessler** [comment]
Hallo Wurzelkoch, vielleicht magst du ja auch über einen Wechsel deines Mailproviders nachdenken? Ich weiß nicht, ob man als Anwalt mit (§ 2 BORA) auf einen Dienst vertrauen sollte, der 10 Monate seine Sicherheitszertifikate nicht aktualisiert... Die berufsrechliche Antwort ist dazu sehr eindeutig...

**Comment by Wurzelkoch** [comment]
> Die StartTLS-Konfigurationen könnte man explizit in den Einstellungen anbieten, sind hier aber m.E. nicht das Problem.

Nach noch bisschen Probieren mit Thunderbird kann ich dir erstmal zustimmen. Thunderbird empfängt sowohl auf dem SSL/TLS-Port als auch auf dem STARTTLS-Port.
Muss wohl systemausfall mal reparieren oder ich muss doch nen anderen Anbieter nutzen.

**Comment by 1resu** [comment]
> Sorry, aber das SSL-Setup dieses Anbieters ist kaputt. Abgelaufene Root-Zerts, falsche Hostnamen (mx1 statt mail), ...

Der Screenshot ist von immuniweb.com, richtig? Das Testergebnis ist gecachet und mehr als 500 Tage alt. Das dort angezeigte Zertifikat wird schon lange nicht mehr ausgeliefert. Das Mailsetup (SMTP, POP, IMAP) inkl. STARTTLS funktioniert korrekt. Das ist auch der Grund, weshalb Thunderbird keine Zertifikatswarnung anzeigt.

Die im Screenshot angezeigte Meldung _The certificate doesn't match hostname_ bezieht sich zudem darauf, dass der Check für die Domain "systemausfall.org" ausgeführt wurde. Korrekt ist jedoch "mail.systemausfall.org", da die Maildienste unter dieser Domain zu erreichen sind.

Persönlich finde ich die Aussagekraft von openssl größer: `openssl s_client -connect mail.systemausfall.org:110 -starttls pop3 -tlsextdebug` zeigt das aktuelle Zertifikat an und validiert es.

**Comment by j-dimension** [comment]
@1resu danke für's Schauen. Ob immuniweb.com cached weiß ich nicht. Ich hatte explizit mail.systemausfall.org getestet, das sollte aus dem Screenshot auch hervorgehen.

@Wurzelkoch ich habe für die Analyse von "Einzelschicksalen" leider nicht ausreichend Zeit. Du könntest schauen ob dir das bereits bearbeitete Ticket https://github.com/jlawyerorg/j-lawyer-org/issues/872 hilft. Es ist Teil von Version 1.13, die in wenigen Tagen veröffentlicht werden wird.

**Comment by Wurzelkoch** [comment]
@j-dimension Das klingt tatsächlich nach nem Ansatz. Da warte ich doch gern auf das Update.
Übrigens bin ich ziemlich begeistert, wie engagiert du dich trotz unzureichender Zeit auch um so Einzelprobleme kümmerst.

**Comment by 1resu** [comment]
> Ob immuniweb.com cached weiß ich nicht.

Ein entsprechender Hinweis auf das Alter der verwendeten Daten wurde oben auf der Seite angezeigt.
Aus meiner Sicht sind die Ergebnisse des Checks mit Vorsicht zu genießen: Es gab bei systemausfall.org keine Situation in dem dieses Zertifkat nach Ablauf der Gültigkeit eingesetzt wurde. Ebenso wie es keinen hostname-Mismatch gab/gibt: mx.systemausfall.org und mail.systemausfall.org verwenden jeweils eigene, unterschiedliche Zertifikate. Der Test vermischt hier also unkorrekter Weise verschiedene Sachen.

**Comment by sumpfralle** [comment]
> [..], falsche Hostnamen (mx1 statt mail), ... [..]

Es ist recht gebräuchlich, dass die MX-Konfiguration (Kommunikation mit anderen Servern; hier: `mx1`) andere Server verwendet, als die zur Kommunikation mit Mail-Clients (hier: `mail`). Mit den Hostnamen dieses Providers gibt es also kein Problem.

Bezüglich des Tests bei immuweb: abgesehen von dem obigen Cache-Problem, würde ich auch ein usability-Problem vermuten. Um ein für ein Mail-Setup relevantes Ergebnis zu erhalten, muss man `Host:Port` auswählen - also in diesem Fall: `mail.systemausfall.org:110` (für POP3).

... und damit sieht es dann plötzlich sehr gut aus:

![immuweb-pop-tls](https://user-images.githubusercontent.com/1474141/99120887-eee5f900-25fb-11eb-87ca-758fe1133c61.png)


Unabhängig davon würde ich jedoch die Qualität eines solchen Test-Diensts (wie immuweb) in Frage stellen, solange sie keinen öffentlichen Issue-Tracker oder zumindest ein Forum betreiben, auf dass Nutzer sich über fragwürdige Test-Methoden oder Usability-Probleme austauschen können. Nunja - der web-basierte Test ist ja auch nur ein Marketing-Vehikel für die Beratungsdienstleistungen der Firma: es schadet also aus ihrer Sicht bestimmt nicht, wenn durch unklare Nutzereingaben ein paar orange Balken Handlungsdruck suggerieren ...

Zurück zum eigentlichen Thema (j-lawyer und STARTTLS): angesichts von [RFC8314](https://tools.ietf.org/html/rfc8314) sollten Mailanbieter sicherlich ihre Vorgabekonfiguration in der Zukunft langsam auf *implicit TLS* (also: 995 für pop3s, 993 für imaps und 465 für smtps) umstellen. Mittelfristig wird es jedoch noch eine Weile Mail-Anbieter geben, die STARTTLS verwenden (bis vor kurzem wurde dies als die Zukunft angesehen). Daher wäre es wahrscheinlich auch für j-lawyer sinnvoll, dieses verbreitete Setup zu unterstützen, sofern dies mit vertretbarem Aufwand umsetzbar ist.

Wie auch immer: danke an die Maintainer für die Entwicklung und Pflege einer ethisch vertretbaren und vertrauenswürdigen Alternative (in Form von AGPL-Software) für den juristischen Berufsstand!

**Comment by j-dimension** [comment]
@Wurzelkoch die 1.13 ist jetzt verfügbar. Bitte mal testen und Feedback geben. Ich lasse das Ticket noch 1 Woche offen.
