### ISSUE TITLE
[BUG] (1.13) [e-mail] Content-Fenster aktualisiert den Inhalt bei manchen E-Mails nicht

### ISSUE THREAD

**Issue by ReRo-G** [jlawyerorg/j-lawyer-org#960]
**Describe the bug / Fehlerbeschreibung**
Im E-Mail-Bereich von jl werden x E-Mails im Eingang angezeigt. Einzelne davon kann jl scheinbar nicht "lesen". In diesem Fall bleibt bei einem Klick auf die E-Mail im Content-Bereich des Fensters der Inhalt der vorherigen E-Mail stehen. Der Header-Bereich wird jedoch korrekt geladen.

Hinweis: das Verhalten tritt nur bei einzelnen E-Mails auf, sodass die Vermutung naheliegt, dass es mit der Formatierung des Absenders zu tun haben könne.

Hinweis 2: Für mich ist das keineswegs kritisch oder eilig!!

**Environment / verwendete Umgebung:**
 - OS / Betriebssystem: MacOS
 - j-lawyer.org Version: 1.13.0.1
 - Postfach bei mailbox.org

**Comment by j-dimension** [comment]
Kann ich ein client.log haben, zusammen mit dem ungefähren Zeitraum zu welchem der Fehler aufgetreten ist?

https://www.j-lawyer.org/?topic=wo-findet-man-die-fehlerprotokolle-des-j-lawyer-org-servers-und-clients

Bitte per E-Mail senden, nicht hier anhängen. Danke!

**Comment by j-dimension** [comment]
```
2020-11-23 09:14:43,626 ERROR [com.jdimension.jlawyer.client.mail.LoadEmailAction] java.lang.IllegalArgumentException: failed to parse:
2020-11-23 09:14:44,602 ERROR [com.jdimension.jlawyer.client.mail.MailContentUI] Error getting contents of IMAP message
javax.mail.MessagingException: E36 BAD Error in IMAP command FETCH: Invalid messageset (0.001 + 0.000 secs).;
  nested exception is:
	com.sun.mail.iap.BadCommandException: E36 BAD Error in IMAP command FETCH: Invalid messageset (0.001 + 0.000 secs).
	at com.sun.mail.imap.IMAPMessage.getMimeStream(IMAPMessage.java:886)
	at com.sun.mail.imap.IMAPMessage.writeTo(IMAPMessage.java:911)
	at com.jdimension.jlawyer.client.mail.MailContentUI.setMessageImpl(MailContentUI.java:889)
	at com.jdimension.jlawyer.client.mail.MailContentUI.setMessage(MailContentUI.java:825)
	at com.jdimension.jlawyer.client.mail.EmailInboxPanel.displayMessage(EmailInboxPanel.java:2298)
	at com.jdimension.jlawyer.client.mail.EmailInboxPanel.tblMailsMouseClicked(EmailInboxPanel.java:1599)
	at com.jdimension.jlawyer.client.mail.EmailInboxPanel.access$1900(EmailInboxPanel.java:750)
	at com.jdimension.jlawyer.client.mail.EmailInboxPanel$13.mouseClicked(EmailInboxPanel.java:1271)
	at java.awt.AWTEventMulticaster.mouseClicked(AWTEventMulticaster.java:270)
	at java.awt.AWTEventMulticaster.mouseClicked(AWTEventMulticaster.java:269)
	at java.awt.Component.processMouseEvent(Component.java:6542)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6304)
	at java.awt.Container.processEvent(Container.java:2239)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2297)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4904)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4544)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4476)
	at java.awt.Container.dispatchEventImpl(Container.java:2283)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:760)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:84)
	at java.awt.EventQueue$4.run(EventQueue.java:733)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:730)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: com.sun.mail.iap.BadCommandException: E36 BAD Error in IMAP command FETCH: Invalid messageset (0.001 + 0.000 secs).
	at com.sun.mail.iap.Protocol.handleResult(Protocol.java:439)
	at com.sun.mail.imap.protocol.IMAPProtocol.fetchSectionBody(IMAPProtocol.java:1884)
	at com.sun.mail.imap.protocol.IMAPProtocol.fetchBody(IMAPProtocol.java:1772)
	at com.sun.mail.imap.protocol.IMAPProtocol.fetchBody(IMAPProtocol.java:1762)
	at com.sun.mail.imap.IMAPMessage.getMimeStream(IMAPMessage.java:874)
	... 40 more

```

**Comment by j-dimension** [comment]
Hier fehlt es mir tatsächlich an einer Möglichkeit es zu reproduzieren. Ich schiebe es erstmal in die 1.14.

**Comment by j-dimension** [comment]
Eine Möglichkeit es zu reproduzieren:

1. Ordner in j-lawyer darstellen, keine E-Mail auswählen
2. Nachricht dieses Ordners mit externem Mailprogramm löschen
3. Im j-lawyer die gelöschte Nachricht darstellen / anklicken

In diesem Fall werden die Metadaten nun nicht mehr dargestellt und eine Fehlermeldung als im Nachrichteninhat angezeigt.
